### ISSUE TITLE
Add support for `getInitialProps` in `getAuth`

### ISSUE THREAD

**Issue by nahtnam** [supabase/auth-helpers#111]
I have a `Navigation` component defined in my `_app.tsx` and I would like to render different things based on if the user is signed in or not. However `useAuth` is client side rendered and shows a loading state. It would be nice if the `getAuth` function supported the `getInitialProps` context type in typescript such that we can fetch the data in `getInitialProps`

**Comment by thorwebdev** [comment]
Hey @nahtnam, terribly sorry for the crazy delay here. For the time being you have to do this routing client-side. E.g. see and example here: https://github.com/vercel/nextjs-subscription-payments/blob/main/pages/signin.tsx#L58-L62
