### ISSUE TITLE
Upcoming Next.js middleware changes

### ISSUE THREAD

**Issue by cursecodes** [supabase/auth-helpers#144]
In the Next.js package, there is a function which is `withMiddlewareAuth`. In the upcoming breaking changes to Next.js version 12.2, they completely alter how middleware works. I would just like to confirm that this update does not affect this package, as it is a crucial component of my app.

**Comment by Jordaneisenburger** [comment]
Been looking at  https://nextjs.org/docs/messages/middleware-upgrade-guide and I think placing the `middleware.js` at the same level as your `pages` folder will do the trick and than do something like:

```
middleware.js
import { withMiddlewareAuth } from '@supabase/auth-helpers-nextjs/middleware';

export function middleware(request) {
    withMiddlewareAuth({ redirectTo: '/login' });
}

export const config = {
    matcher: ['/dashboard/:path*'],
}
```

But weirdly enough I get the below error, which makes no sense to me
```
./middleware.js:1:0
Module not found: Can't resolve '@supabase/auth-helpers-nextjs/middleware'
> 1 | import { withMiddlewareAuth } from '@supabase/auth-helpers-nextjs/middleware';
```

**Comment by cursecodes** [comment]
Hey @Jordaneisenberger,

Try importing it from `@supabase/auth-helpers-nextjs/dist/middleware`. This seems to be where it is being exported from at the moment.
