### ISSUE TITLE
SvelteKit: onUserUpdate redirect don't work

### ISSUE THREAD

**Issue by finnstrand** [supabase/auth-helpers#147]
I can't get the redirect after sign up/sign in to work. The function triggers but it doesn't redirect.

`__layout.svelte`
```
const onUserUpdate = async (user) => {
    if (user) await goto('/')
  }
```

**Comment by Ak4zh** [comment]
The app get's stuck at navigating.
Navigating store changes with from and to value but it just stuck there, probably a sveltekit issue and not specific to `auth-helpers`.

**Comment by Ak4zh** [comment]
I am using this workaround for now, if you find a solution please update.

```javascript
const onUserUpdate = async (user) => {
  if (user) {
    await goto('/').then(() => {goto('/profile');})			
  }
}

```

**Comment by MrBryanBell** [comment]
Same problem, but in my case, it only happens when the route i'm trying to redirect have an enpoint, 

ex: profile.svelte --> profile.ts

**Comment by silentworks** [comment]
The library has changed quite a bit and this method is no longer necessary.
