### ISSUE TITLE
Cloudflare Workers doesn't allow modifying immutable headers to set cookie

### ISSUE THREAD

**Issue by MyraManes** [supabase/auth-helpers#165]
I am using the [@sveltejs/adapter-cloudflare-workers](https://www.npmjs.com/package/@sveltejs/adapter-cloudflare-workers) package to host a SvelteKit site on Cloudflare Workers.  On the initial load, everything looks good, but whenever I try to login, I receive the following error:

_Connected to supabase-auth-helpers-sveltekit, waiting for logs...
POST https://supabase-auth-helpers-sveltekit.workers.dev/api/auth/user - Ok @ 7/7/2022, 10:52:19 AM
  (error) {"type":"cookie_not_found","message":"No cookie was found!","source":"sb_auth_helpers"}
POST https://supabase-auth-helpers-sveltekit.workers.dev/api/auth/callback - Ok @ 7/7/2022, 10:52:28 AM
  (error) {"type":"cookie_not_found","message":"No cookie was found!","source":"sb_auth_helpers"}
  (error) TypeError: Can't modify immutable headers.
    at SvelteKitRequestAdapter.setRequestCookie (worker.js:963:26)
    at setCookies (worker.js:938:9)
    at handle2 (worker.js:6105:11)
    at async respond (worker.js:9320:22)
    at async Object.fetch (worker.js:9617:12)
POST https://supabase-auth-helpers-sveltekit.workers.dev/api/auth/user - Ok @ 7/7/2022, 10:52:29 AM
  (error) {"type":"cookie_not_found","message":"No cookie was found!","source":"sb_auth_helpers"}_

I created a minimal example here: [https://github.com/MyraManes/supabase-auth-helpers-sveltekit](https://github.com/MyraManes/supabase-auth-helpers-sveltekit)

According to the [Workers Docs](https://developers.cloudflare.com/workers/examples/alter-headers), the response has to be cloned so that it's no longer immutable.

**Comment by craigdrayton** [comment]
Also just hit this issue

**Comment by juanpujol** [comment]
I'm also having an issue with Cloudflare Pages. The Sveltekit helper works great locally but it fails to alter cookies when I try a deployed to Pages.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/30832/183548958-4e42466d-290e-492b-8d76-363dfd59a7c7.png">

**Comment by silentworks** [comment]
This should be fixed in the latest version (plenty of breaking changes).
