### ISSUE TITLE
NextJs - middleware import

### ISSUE THREAD

**Issue by official-carledwardfp** [supabase/auth-helpers#168]
### Description

`'@supabase/auth-helpers-nextjs/middleware'` is not found. I used `'@supabase/auth-helpers-nextjs/dist/middleware'` instead. Also, NextJs [replaced the middleware API](https://nextjs.org/docs/messages/nested-middleware) to only have a single root middleware file. [New API Link](https://nextjs.org/docs/advanced-features/middleware). This might have a breaking change for `withMiddlewareAuth`

**Comment by boredland** [comment]
> '@supabase/auth-helpers-nextjs/middleware' is not found. I used '@supabase/auth-helpers-nextjs/dist/middleware' instead. 

I wonder if that ever worked. Without hacky tricks afaik having path imports is still a nightmare in typescript.

**Comment by david-plugge** [comment]
Maybe the "typesVersions" key in package.json is what you are looking for

**Comment by boredland** [comment]
Not sure I understand how that could help. What could actually help IMO, is if we use the exports fields together with ts 4.7.x - Will give that a try.

**Comment by boredland** [comment]
hm. I don't get how to make that work.

**Comment by boredland** [comment]
thanks for the hint reg. typesVersions. Made it work in https://github.com/supabase-community/auth-helpers/pull/170 thanks to [this](https://antfu.me/notes#types-for-sub-modules) explanation.
