### ISSUE TITLE
NextJS - Invalid Refresh Token

### ISSUE THREAD

**Issue by ARMATAV** [supabase/auth-helpers#171]
On the latest release, using purely the example in `examples/nextjs`, after the `exp` time elapses, I'm getting the following error.

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/2433203/178402068-86a122e3-311e-46ce-bf32-51c8bf58cdde.png">

How can I make sure that the automatic token refresh fires off properly?

(Local development via `supabase start` and its associated container(s))

**Comment by ARMATAV** [comment]
Scratch that, this is with any and every example using NextJS and Supabase, with or without auth-helper. Very weird behavior.

**Comment by ARMATAV** [comment]
> @ARMATAV Do you know if there has been any updates about this?

None so far - just a bunch of closed issues surrounding it; perhaps they deprioritized in favor of something else.

**Comment by krtkeyan** [comment]
Facing a similar issue where the users get signed out after the expiry time, upon debugging seems the refresh token fails with the `Invalid Refresh token` in logger.

**Comment by ARMATAV** [comment]
Noting here, in production, setting the JWT refresh time to a week doesn't do anything - it seems like it's still gone after only an hour

**Comment by travispamaral** [comment]
This seems to be in a recent update. Im lowered my `auth-helpers-nextjs` to `0.2.1` from `0.2.5` and this worked as expected

**Comment by krtkeyan** [comment]
Tried downgrading to `0.2.1`, and even though I didn't get `Invalid Refresh Token` error message, still the token doesn't get refreshed and it logs `JWT expired`

**Comment by Bladeyy** [comment]
Any solution to this yet?

**Comment by mrolafsson** [comment]
I'm guessing does not work with `supabase-js@next (1.36.0-next.14)`?

**Comment by ARMATAV** [comment]
https://supabase.com/blog/supabase-js-v2

> This solves the “getting logged out” issue, which has been a recurring challenge in our GitHub Discussions.

Should be good to go here now, right?

**Comment by tourbillonlabs** [comment]
I've seen @thorwebdev reference #92 as resolving this issue but it still seems to be present.

I'm using `supabaseServerClient` on an unsecured `/api` endpoint, and every now and then I get the error `JWT expired` unless I hit a client-side route which refreshes the token.

I've tried with @latest and @rc of supabase-js

```
"@supabase/auth-helpers-nextjs": "^0.2.7",
"@supabase/auth-helpers-shared": "^0.1.3",
"@supabase/gotrue-js": "^1.22.22",
"@supabase/supabase-js": "^2.0.0-rc.8",
"@supabase/ui": "^0.36.5",
```

**Comment by thorwebdev** [comment]
The next release should make this more robust. You can already try it out with installing `npm install @supabase/auth-helpers-nextjs@next`  and you can find the migration guide here: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/MIGRATION_GUIDE.md#migrating-to-03x
