### ISSUE TITLE
SvelteKit Documentation doesn't include POST or other request methods

### ISSUE THREAD

**Issue by LucasWolke** [supabase/auth-helpers#188]
There are only server/client side examples for GET request method. withApiAuth also isn't documented as far as I can see. Example could also include how to access the user's id with locals.

**Comment by silentworks** [comment]
It's the same use with any method (GET, POST, PUT, DEL). The concept of locals is more SvelteKit related than auth helpers related. If you can provide more clearly what you are having problems with then I can get it documented or maybe someone in the community will document it.
