### ISSUE TITLE
Next.js Middleware `redirectTo` does not support outbound URLs

### ISSUE THREAD

**Issue by vhpx** [supabase/auth-helpers#207]
Currently, the middleware auth helper for Nextjs only allow redirect on the same domain route.
Use case: redirectTo: '**https://a.b/c**' leads to '**localhost:3000/https://a.b/c**'
Expectation: actually redirecting to the provided URL: '**https://a.b/c**'

Is there any solutions to this problem?

**Comment by thorwebdev** [comment]
This can likely be tackled together with https://github.com/supabase/auth-helpers/issues/96

**Comment by CA-MKSingh** [comment]
Hey @vhpx , if you still require this then, I would like to work.

**Comment by vhpx** [comment]
Sure, @thorwebdev. It is very much appreciated!

**Comment by CA-MKSingh** [comment]
can you please assign it to me?

**Comment by vhpx** [comment]
> can you please assign it to me?

I'm not a member of the Supabase team, so I cannot assign this issue to you. However, you can just focus on working out the solution, and someone on the team will check it out and make the necessary changes.

**Comment by thorwebdev** [comment]
This will be possible after https://github.com/supabase/auth-helpers/pull/364 is merged.
