### ISSUE TITLE
SupaAuthHelper typing error

### ISSUE THREAD

**Issue by Olyno** [supabase/auth-helpers#208]
Hi 👋🏻 

When following the Svelte Kit tutorial, the ``SupaAuthHelper`` has an issue with typing:

```
Type 'SupabaseClient | undefined' is not assignable to type 'SupabaseClient'.
  Type 'undefined' is not assignable to type 'SupabaseClient'.ts(2322)
```

**Comment by silentworks** [comment]
The library has changed quite a bit and this helper is no longer necessary.
