### ISSUE TITLE
Nextjs Auth Helpers: getUser returns type any for user and error

### ISSUE THREAD

**Issue by nickbrinser** [supabase/auth-helpers#213]
Hello,

I am using `@supabase/auth-helpers-nextjs: 0.2.5` and it appears that the return type for `getUser()` is not resolving correctly. It returns `ResponsePayload` which has this shape, 

```
interface ResponsePayload {
    user: User | null;
    accessToken: string | null;
    error?: ErrorPayload;
}
```

The issue it seems is that the imports for `User` and `ErrorPayload` are not resolving.

**Comment by nickbrinser** [comment]
To add to this, it looks like `getUser()` also returns `{user: null, accessToken: null}` when called with no logged in user (no accessToken). The error is caught, but this is the one error case that is not filled out and does nothing.

**Comment by Xananax** [comment]
There's additional detail and some feeble attempt at understanding what's going on in the referenced duplicate #249

**Comment by thorwebdev** [comment]
Thanks for reporting this. With the next release, `getUser` will be removed, so likely won't look into fixing this anymore. You can already test this out with `npm install @supabase/auth-helpers-nextjs@next` and find the migration guide here: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/MIGRATION_GUIDE.md#migrating-to-03x
