### ISSUE TITLE
Allow useUser to accept initial data for SSR requests

### ISSUE THREAD

**Issue by drewbietron** [supabase/auth-helpers#220]
# Feature request
It would be nice if the useUser hook could accept an argument for initial data in cases where a user is fetched on the server, and useUser it used on the client.

## Is your feature request related to a problem? Please describe.

A clear and concise description of what you want and what your use case is.

## Describe the solution you'd like

Allow the `<UserProvider>` to accept values for initial data where the hook can accept a single argument for a user so that there is a smooth handoff between a SSR user, and a client side user fetched via the hook

**Comment by thorwebdev** [comment]
This has been added to the `SessionContext` with the `initialSession` param: https://github.com/supabase/auth-helpers/blob/main/examples/nextjs/pages/_app.tsx#L24
