### ISSUE TITLE
Client Side DB queries don't work when refreshing the page

### ISSUE THREAD

**Issue by stukennedy** [supabase/auth-helpers#226]
# Bug report

I'm following the Magic Link sveltekit example code and got it working (there's actually a deprecated `skHelper` in there, but other than that it works)
I can login and it redirects to my protected "projects page" and loads my data from the authenticated Supabase DB API call (in the Svelte client-side script as shown in your sveltekit documentation).
However if you refresh the page, even though the `$session.user` is there it calls the API and it returns a 200, but with nothing in the response. If I navigate to the home page and navigate back using the apps routing, it all works great. Very confused.
The page I'm loading has no endpoint that is intercepting it, so I'm not quite sure what I'm missing here.

## System information

- OS: MacOS
- Browser: Firefox
- Version of supabase-js: 
		"@supabase/auth-helpers-svelte": "^0.4.5",
		"@supabase/supabase-js": "^1.35.4",
- Version of Node.js: 16.14.0

**Comment by dragonsnapx** [comment]
Having the same problem, I'm assuming the issue is that the query is performed without authentication.

**Comment by dragonsnapx** [comment]
So what I managed to do is [set the auth cookie manually](https://supabase.com/docs/reference/javascript/auth-setauth) before performing requests for tables that have RLS enabled:

```javascript
import { browser } from '$app/env'; 
import { supabaseClient } from '$lib/database';

export async function load({ params, session }){
    if (!browser){
        supabaseClient.auth.setAuth(session.accessToken);
    }
    // Your requests here...
}
```

I have to say, the docs for Supabase Auth Helpers for Svelte is pretty lackluster.

**Comment by david-plugge** [comment]
@dragonsnapx Is this still a thing after the latest release?
