### ISSUE TITLE
withMiddlewareAuth - passing req, res to isPermitted

### ISSUE THREAD

**Issue by KULTI1995** [supabase/auth-helpers#229]
# Feature request

Good day, is there a chance of a fast implementation, passing req, res to isPermitted (withMiddlewareAuth)?
By which it will be possible to build a little more advanced authGuard. It gives an example of what can be achieved with this and why it is so important. E.g. check if a user has a subscription and based on that give access to the panel, or send back to the subscription settings. Please let me know if we can implement this and add these 2 optional properties to isPermitted. Otherwise I will have to open a new custom project passing these properties. Needs under my project that I am writing for a client.

**Comment by KULTI1995** [comment]
I think it is even better to pass supabaseClient, something like:

const supabaseClient = supabaseServerClient({ req, res })

await options.authGuard.isPermitted(authResult.user, supabaseClient)

**Comment by thorwebdev** [comment]
From the next release onward, an authenticated supabase client with be returned in the `isPermitted` function, allowing you to run queries etc. You can already try it out with installing npm install @supabase/auth-helpers-nextjs@next and you can find the migration guide here: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/MIGRATION_GUIDE.md#migrating-to-03x
