### ISSUE TITLE
SvelteKit removed Session store

### ISSUE THREAD

**Issue by AlgorithmEnigma** [supabase/auth-helpers#230]
# Bug report

## Describe the bug

The latest version of SvelteKit removes the Session store, breaking the Svelte and SvelteKit auth helpers.
See: https://github.com/sveltejs/kit/discussions/5883#discussion-4302953

## Expected behavior

Be able to use auth-helpers with latest version of SvelteKit

**Comment by pilcrowOnPaper** [comment]
I don't use Supabase Auth Helpers, but I'm running into the same problem so it might be relevant.

Svelte stores are stored as global variables inside the server when server-rendering so it should be stored inside a context (`$session` was stored like so). Not sure how it'll be resolved, but something to be careful if you're implementing your own store for user data.

https://github.com/sveltejs/kit/discussions/4339

**Comment by david-plugge** [comment]
Rich said [this](https://github.com/sveltejs/kit/discussions/5883#discussioncomment-3393603) about the removal of the session store. I think the auth helpers should handle the login, signin, logout etc. on the server since a non JS fallback is the main benefit of sveltekit over plain svelte. I´m currently working on a solution using an [enhanced form](https://github.com/sveltejs/kit/issues/3533).

**Comment by david-plugge** [comment]
In the sveltekit repo they are talking about adding Actions, an easy way to implement progressive enhancement for forms. Since its not clear how the api will look like it doesn´t make sense to put much work into this. Lets wait for it and see how actions can make this easy.
There are some [solutions](https://github.com/sveltejs/kit/discussions/5883#discussioncomment-3430427) that may work for the moment.

**Comment by hmmh-benjamin-lewandowski** [comment]
did someone get it to work after the router changes?

**Comment by mattlehrer** [comment]
Yes, I think I have it working. One annoying part to figure out was the `invalidate` in the signin component, toward the bottom of this post. 

Here is my new setup:

```ts
// src/hooks.ts
import { handleAuth } from '@supabase/auth-helpers-sveltekit';
import type { Handle } from '@sveltejs/kit';
import { sequence } from '@sveltejs/kit/hooks';

export const handle: Handle = sequence(
	...handleAuth(),
);
```

```ts
// src/routes/layout.server.ts
import type { LayoutServerLoad } from './$types';

export const load: LayoutServerLoad = async ({ locals }: { locals: App.Locals }) => {
	return locals.user
		? {
			    session: {
				    user: locals.user,
				    accessToken: locals.accessToken,
				    error: locals.error,
			    },
		  }
		: {};
};
```

```ts
// src/lib/supabase.ts
import { PUBLIC_SUPABASE_ANON_KEY, PUBLIC_SUPABASE_URL } from '$env/static/public';
import { createSupabaseClient } from '@supabase/auth-helpers-sveltekit';

const { supabaseClient } = createSupabaseClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY);

export { supabaseClient };
```

```svelte
<!-- src/routes/layout.svelte -->
<script lang="ts">
	import { page } from '$app/stores';
	import { supabaseClient } from '$lib/supabase';
	import { SupaAuthHelper, type Session } from '@supabase/auth-helpers-svelte';
	import { writable } from 'svelte/store';

	import { setContext } from 'svelte';

	const session = writable<Session>();

	$: {
		// This solved a problem on first page load though I'm sure there's a better way, 
		// maybe with onMount
		
		$session = $page.data.session;
		setContext('session', session);
	}
</script>

{#if !$page.url.pathname.startsWith('/dashboard')}
		{#if supabaseClient}
			<SupaAuthHelper {supabaseClient} {session}>
				<slot />
			</SupaAuthHelper>
		{:else}
			<slot />
		{/if}
{/if}
```

```svelte
<!-- use session in a component, like nav -->
<script lang="ts">
	import { getContext } from 'svelte';
	import type { Session } from '@supabase/auth-helpers-svelte';
	import type { Writable } from 'svelte/store';

	const session = getContext<Writable<Session>>('session');
</script>
```

```svelte
<!-- sign in component -->
<script lang="ts">
	import { getContext } from 'svelte';

	import type { Session } from '@supabase/auth-helpers-svelte';
	import type { Writable } from 'svelte/store';

	const session = getContext<Writable<Session>>('session');

	import { goto, invalidate } from '$app/navigation';
	import { supabaseClient } from './supabase';

	let email: string;
	let password: string;

	async function signin() {
		let error, user, sbSession;
		try {
			if (!supabaseClient) throw new Error('supabaseClient is not defined');
			({
				error,
				user,
				session: sbSession,
			} = await supabaseClient.auth.signIn({
				email,
				password,
			}));
			if (error) throw error;
			$session = {
				user,
				accessToken: sbSession?.access_token,
			};
		} catch (error) {
			// ... handle error
		} finally {
		    if (error) {
			    // ... handle error
		    } else {
			    // *** this is the key to avoid having to reload after login
			    await invalidate();
			    // *** ^^^^
			    await goto('/somewhere');
		    }
		}
	}
</script>

<div>
	<div>
		<div>
			<h2>
				Sign in to your account
			</h2>
		</div>
		<form method="POST">
			<input type="hidden" name="remember" value="true" />
			<div>
				<div>
					<label for="email-address">Email address</label>
					<input
						id="email-address"
						name="email"
						type="email"
						autocomplete="email"
						bind:value={email}
						required
						placeholder="Email address"
					/>
				</div>
				<div>
					<label for="password">Password</label>
					<input
						id="password"
						name="password"
						type="password"
						autocomplete="current-password"
						bind:value={password}
						required
						placeholder="Password"
					/>
				</div>
			</div>

			<div>
				<button type="submit" on:click|preventDefault={signin}>
					Sign in
				</button>
			</div>
		</form>
	</div>
</div>
```

Any comments, suggestions or improvements extremely welcome.

**Comment by ryanrussell** [comment]
> Yes, I think I have it working. One annoying part to figure out was the `invalidate` in the signin component, toward the bottom of this post.
> 
> Here is my new setup:
> 
> ```ts
> // src/hooks.ts
> import { handleAuth } from '@supabase/auth-helpers-sveltekit';
> import type { Handle } from '@sveltejs/kit';
> import { sequence } from '@sveltejs/kit/hooks';
> 
> export const handle: Handle = sequence(
> 	...handleAuth(),
> );
> ```
> 
> ```ts
> // src/routes/layout.server.ts
> import type { LayoutServerLoad } from './$types';
> 
> export const load: LayoutServerLoad = async ({ locals }: { locals: App.Locals }) => {
> 	return locals.user
> 		? {
> 			    session: {
> 				    user: locals.user,
> 				    accessToken: locals.accessToken,
> 				    error: locals.error,
> 			    },
> 		  }
> 		: {};
> };
> ```
> 
> ```ts
> // src/lib/supabase.ts
> import { PUBLIC_SUPABASE_ANON_KEY, PUBLIC_SUPABASE_URL } from '$env/static/public';
> import { createSupabaseClient } from '@supabase/auth-helpers-sveltekit';
> 
> const { supabaseClient } = createSupabaseClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY);
> 
> export { supabaseClient };
> ```
> 
> ```svelte
> 
> <script lang="ts">
> 	import { page } from '$app/stores';
> 	import { supabaseClient } from '$lib/supabase';
> 	import { SupaAuthHelper, type Session } from '@supabase/auth-helpers-svelte';
> 	import { writable, Writable } from 'svelte/store';
> 	import { getContext, setContext } from 'svelte';
> 
> 	setContext('session', writable<Session>($page.data.session));
> 	const session = getContext<Writable<Session>>('session');
> </script>
> 
> {#if !$page.url.pathname.startsWith('/dashboard')}
> 		{#if supabaseClient}
> 			<SupaAuthHelper {supabaseClient} {session}>
> 				<slot />
> 			</SupaAuthHelper>
> 		{:else}
> 			<slot />
> 		{/if}
> {/if}
> ```
> 
> ```svelte
> 
> <script lang="ts">
> 	import { getContext } from 'svelte';
> 	import type { Session } from '@supabase/auth-helpers-svelte';
> 	import type { Writable } from 'svelte/store';
> 
> 	const session = getContext<Writable<Session>>('session');
> </script>
> ```
> 
> ```svelte
> 
> <script lang="ts">
> 	import { getContext } from 'svelte';
> 
> 	import type { Session } from '@supabase/auth-helpers-svelte';
> 	import type { Writable } from 'svelte/store';
> 
> 	const session = getContext<Writable<Session>>('session');
> 
> 	import { goto, invalidate } from '$app/navigation';
> 	import { supabaseClient } from './supabase';
> 
> 	let email: string;
> 	let password: string;
> 
> 	async function signin() {
> 		let error, user, sbSession;
> 		try {
> 			if (!supabaseClient) throw new Error('supabaseClient is not defined');
> 			({
> 				error,
> 				user,
> 				session: sbSession,
> 			} = await supabaseClient.auth.signIn({
> 				email,
> 				password,
> 			}));
> 			if (error) throw error;
> 			$session = {
> 				user,
> 				accessToken: sbSession?.access_token,
> 			};
> 		} catch (error) {
> 			// ... handle error
> 		} finally {
> 		    if (error) {
> 			    // ... handle error
> 		    } else {
> 			    // *** this is the key to avoid having to reload after login
> 			    await invalidate();
> 			    // *** ^^^^
> 			    await goto('/somewhere');
> 		    }
> 		}
> 	}
> </script>
> 
> <div>
> 	<div>
> 		<div>
> 			<h2>
> 				Sign in to your account
> 			</h2>
> 		</div>
> 		<form method="POST">
> 			<input type="hidden" name="remember" value="true" />
> 			<div>
> 				<div>
> 					<label for="email-address">Email address</label>
> 					<input
> 						id="email-address"
> 						name="email"
> 						type="email"
> 						autocomplete="email"
> 						bind:value={email}
> 						required
> 						placeholder="Email address"
> 					/>
> 				</div>
> 				<div>
> 					<label for="password">Password</label>
> 					<input
> 						id="password"
> 						name="password"
> 						type="password"
> 						autocomplete="current-password"
> 						bind:value={password}
> 						required
> 						placeholder="Password"
> 					/>
> 				</div>
> 			</div>
> 
> 			<div>
> 				<button type="submit" on:click|preventDefault={signin}>
> 					Sign in
> 				</button>
> 			</div>
> 		</form>
> 	</div>
> </div>
> ```
> 
> Any comments, suggestions or improvements extremely welcome. [updated to initialize store in setContext on suggestion from @pilcrowOnPaper]

Thanks for sharing! Are you planning on submitting this as a PR? I didn't see it in there currently...

**Comment by Maxson52** [comment]
If you're using magic links you could also update the session store on login like this:
```js
// +layout.svelte
supabaseClient.auth.onAuthStateChange((_, ses) => {
    $session = {
      user: ses.user,
      accessToken: ses?.access_token,
    };
});
```

**Comment by david-plugge** [comment]
I´ve been playing around with the solution from @mattlehrer and this is what i came up with: https://github.com/sveltejs/kit/discussions/5883#discussioncomment-3506850

I can create an example repo if needed

**Comment by ewilliam** [comment]
@david-plugge example repo would be helpful! appreciate

**Comment by david-plugge** [comment]
> @david-plugge example repo would be helpful! appreciate

I dont have much time atm, trying to get it done by the end of week :)

**Comment by esojrafael** [comment]
Session removed changes explained here: https://github.com/sveltejs/kit/discussions/5883

Here's the migration guide in case someone needs it: https://github.com/sveltejs/kit/discussions/5774

**Comment by esojrafael** [comment]
> Yes, I think I have it working. One annoying part to figure out was the `invalidate` in the signin component, toward the bottom of this post.
> 
> Here is my new setup:
> 
> ```ts
> // src/hooks.ts
> import { handleAuth } from '@supabase/auth-helpers-sveltekit';
> import type { Handle } from '@sveltejs/kit';
> import { sequence } from '@sveltejs/kit/hooks';
> 
> export const handle: Handle = sequence(
> 	...handleAuth(),
> );
> ```
> 
> ```ts
> // src/routes/layout.server.ts
> import type { LayoutServerLoad } from './$types';
> 
> export const load: LayoutServerLoad = async ({ locals }: { locals: App.Locals }) => {
> 	return locals.user
> 		? {
> 			    session: {
> 				    user: locals.user,
> 				    accessToken: locals.accessToken,
> 				    error: locals.error,
> 			    },
> 		  }
> 		: {};
> };
> ```
> 
> ```ts
> // src/lib/supabase.ts
> import { PUBLIC_SUPABASE_ANON_KEY, PUBLIC_SUPABASE_URL } from '$env/static/public';
> import { createSupabaseClient } from '@supabase/auth-helpers-sveltekit';
> 
> const { supabaseClient } = createSupabaseClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY);
> 
> export { supabaseClient };
> ```
> 
> ```svelte
> 
> <script lang="ts">
> 	import { page } from '$app/stores';
> 	import { supabaseClient } from '$lib/supabase';
> 	import { SupaAuthHelper, type Session } from '@supabase/auth-helpers-svelte';
> 	import { writable, Writable } from 'svelte/store';
> 	import { getContext, setContext } from 'svelte';
> 
> 	setContext('session', writable<Session>($page.data.session));
> 	const session = getContext<Writable<Session>>('session');
> </script>
> 
> {#if !$page.url.pathname.startsWith('/dashboard')}
> 		{#if supabaseClient}
> 			<SupaAuthHelper {supabaseClient} {session}>
> 				<slot />
> 			</SupaAuthHelper>
> 		{:else}
> 			<slot />
> 		{/if}
> {/if}
> ```
> 
> ```svelte
> 
> <script lang="ts">
> 	import { getContext } from 'svelte';
> 	import type { Session } from '@supabase/auth-helpers-svelte';
> 	import type { Writable } from 'svelte/store';
> 
> 	const session = getContext<Writable<Session>>('session');
> </script>
> ```
> 
> ```svelte
> 
> <script lang="ts">
> 	import { getContext } from 'svelte';
> 
> 	import type { Session } from '@supabase/auth-helpers-svelte';
> 	import type { Writable } from 'svelte/store';
> 
> 	const session = getContext<Writable<Session>>('session');
> 
> 	import { goto, invalidate } from '$app/navigation';
> 	import { supabaseClient } from './supabase';
> 
> 	let email: string;
> 	let password: string;
> 
> 	async function signin() {
> 		let error, user, sbSession;
> 		try {
> 			if (!supabaseClient) throw new Error('supabaseClient is not defined');
> 			({
> 				error,
> 				user,
> 				session: sbSession,
> 			} = await supabaseClient.auth.signIn({
> 				email,
> 				password,
> 			}));
> 			if (error) throw error;
> 			$session = {
> 				user,
> 				accessToken: sbSession?.access_token,
> 			};
> 		} catch (error) {
> 			// ... handle error
> 		} finally {
> 		    if (error) {
> 			    // ... handle error
> 		    } else {
> 			    // *** this is the key to avoid having to reload after login
> 			    await invalidate();
> 			    // *** ^^^^
> 			    await goto('/somewhere');
> 		    }
> 		}
> 	}
> </script>
> 
> <div>
> 	<div>
> 		<div>
> 			<h2>
> 				Sign in to your account
> 			</h2>
> 		</div>
> 		<form method="POST">
> 			<input type="hidden" name="remember" value="true" />
> 			<div>
> 				<div>
> 					<label for="email-address">Email address</label>
> 					<input
> 						id="email-address"
> 						name="email"
> 						type="email"
> 						autocomplete="email"
> 						bind:value={email}
> 						required
> 						placeholder="Email address"
> 					/>
> 				</div>
> 				<div>
> 					<label for="password">Password</label>
> 					<input
> 						id="password"
> 						name="password"
> 						type="password"
> 						autocomplete="current-password"
> 						bind:value={password}
> 						required
> 						placeholder="Password"
> 					/>
> 				</div>
> 			</div>
> 
> 			<div>
> 				<button type="submit" on:click|preventDefault={signin}>
> 					Sign in
> 				</button>
> 			</div>
> 		</form>
> 	</div>
> </div>
> ```
> 
> Any comments, suggestions or improvements extremely welcome. [updated to initialize store in setContext on suggestion from @pilcrowOnPaper]

This was very helpful!
Are you using `withApiAuth()` helper in endpoints?

**Comment by david-plugge** [comment]
Here we go https://github.com/david-plugge/supabase-auth-helpers-sk-new-api

@silentworks what do you think?

**Comment by ryanrussell** [comment]
Thanks for taking the time to put together a great template @david-plugge 

For casual readers, this approach **keeps the logic in `+page.server.ts` instead of `+page.ts`**  :1st_place_medal: 

Can confirm works out of the box with a simple `pnpm i && pnpm run dev` and was functional within 60 seconds of cloning. 

Longest part was pasting in the keys to `.env`

**Comment by david-plugge** [comment]
Glad you all seem to like what i´m doing :) Feel free to leave some ideas and tips!

**Comment by Adriman2** [comment]
Hey @david-plugge thanks for the repo! Sorry for the noob question, I'm trying to use your repo as guidance to migrate with the latest breaking changes since I also was using auth-helpers. 

I see that you have a [package](https://github.com/david-plugge/sveltekit-supabase/tree/main/packages/supabase-auth-helpers-sveltekit/src/package) folder inside your src folder. Do I need to copy that part to my current project as well to be able to use the minimal setup?

**Comment by david-plugge** [comment]
@Adriman2 you only need the code in _packages/supabase-auth-helpers-sveltekit/src/package_
I´ll add a section to the readme that explains it better :)

**Comment by saturnonearth** [comment]
Now that SvelteKit is in RC stage, maybe we can have this officially updated for the new changes?

**Comment by kvetoslavnovak** [comment]
Does it also reflect the [issue](https://github.com/sveltejs/kit/discussions/4339) of dangerous data leaking in SSR?
There is also [proposed solution](https://github.com/sveltejs/kit/discussions/4339#discussioncomment-3258927) of custom store - reinventing the session store which was recently removed from SvelteKit)

**Comment by pilcrowOnPaper** [comment]
@kvetoslavnovak 
@mattlehrer 's solution does

**Comment by david-plugge** [comment]
Since the updated sveltekit routing a writable session store doesn´t make a lot of sense. In **mattlehrer**´s solution he uses `invalidate()` (renamed to `invalidateAll()`) to refetch the data from the server which also gets the most recent session data from the cookie. The server is the single source of truth now, which is a good thing. If you want to modify the session you have to send it to the server and then get the updated session from the server.

If you want to use `$session` over `$page.data.session` you can create a derived store from the `page` store and write it to the context.
I created my own implementation [here](https://github.com/david-plugge/sveltekit-supabase/issues/4).

**Comment by eikaramba** [comment]
question: why do i even have to use `getContext('session')`. as far as i can see i can just use `$page.data.session` directly within any .svelte file.

**Comment by david-plugge** [comment]
> question: why do i even have to use `getContext('session')`. as far as i can see i can just use `$page.data.session` directly within any .svelte file.

you don´t have to, `$session` is just shorter and this discussion is more about the resulting changes in this package :)

**Comment by eikaramba** [comment]
okay thank you very much, i was just confused as there are basically 3 ways and multiple repos doing all stuff differently somehow:
- via `get/setContext`
- via `export let data`
- via `$page.data`

for now i will settle with $page.data everywhere and then if i want to optimize and only invalidate the session (not everything) i understand that some people use local stores. however for now i am happy if everything works again :)

**Comment by david-plugge** [comment]
The benefit of export let data is that you get type safety and autocompletion. I think the best way is using the export version for most things and $page.data for data returned somewhere down the tree but consumed in a parent.
I think sveltekit could provide a `best practice` example in the docs

**Comment by adonis2611** [comment]
@david-plugge whats the best way to get in contact with yoh?
