### ISSUE TITLE
Move @supabase/supabase-js in peerDependencies

### ISSUE THREAD

**Issue by Olyno** [supabase/auth-helpers#231]
# Feature request

## Is your feature request related to a problem? Please describe.

Let's take the example of the Hackathon. The new version of Supabase, the ``rc`` version, is still being tested. Therefore, it would not be a good idea to update the version in the helpers. At the same time, the developers want to use it to test the new features. Changing the dependency to "peerDependencies" would solve this problem.

## Describe the solution you'd like

Moving ``@supabase/supabase-js`` to peerDependencies, and let developers choose the version used.

## Describe alternatives you've considered

Publishing a ``rc`` version of helpers work too.

## Additional context

/

**Comment by silentworks** [comment]
If it was a peerDependency and the user was to install the rc version with this library, it would not work at all.

**Comment by Olyno** [comment]
How can we make it work better in this case? I know it was very unclear during the hackathon, and I had some compatibility issues between rc and latest
