### ISSUE TITLE
withPageAuth user undefined for authenticated user

### ISSUE THREAD

**Issue by lsbyerley** [supabase/auth-helpers#232]
[Closed prematurely](https://github.com/supabase/auth-helpers/issues/203), i am re-opening this issue as `withPageAuth` does not seem to work at all.

Issue regarding `withPageAuth`. I have setup a profile page using `withPageAuth` and the user data is always undefined in the component. Am I using it correctly or is there a bug? The user is not redirected if they are not authenticated

`"@supabase/auth-helpers-nextjs": "0.2.7"`
`"next": "12.2.5"`

```js
import Head from 'next/head';
import Layout from '@/components/Layout';
import {
  getUser,
  withPageAuth,
  supabaseServerClient,
} from '@supabase/auth-helpers-nextjs';

export const getServerSideProps = withPageAuth({
  redirectTo: '/',
  async getServerSideProps(ctx) {
    // this console log is never seen in the terminal
    console.log('LOG: ctx', ctx);
    const { user } = await getUser(ctx);
    return { props: { user } };
  },
});

const profile = ({ user }) => {
  // user is always null here
  console.log('LOG: user', user);

  return (
    <Layout>
      <Head>
        <title>User Profile</title>
      </Head>
      <div className='py-12 mx-auto max-w-7xl sm:px-6 lg:px-8'>
        <div className='max-w-4xl mx-auto'>
          <div className='overflow-hidden shadow bg-base-100 sm:rounded-lg'>
            <div className='px-4 py-5 sm:px-6'>
              <h3 className='text-lg font-medium leading-6 '>User Profile</h3>
              <p className='max-w-2xl mt-1 text-sm text-gray-500'>
                Profile Details.
              </p>
            </div>
            <div className='border-t border-base-300'>
              <dl>
                <div className='px-4 py-5 bg-base-200 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6'>
                  <dt className='text-sm font-medium text-gray-500'>Name</dt>
                  <dd className='mt-1 text-sm sm:mt-0 sm:col-span-2'>
                    {user?.email || '-'}
                  </dd>
                </div>
              </dl>
            </div>
          </div>
        </div>
      </div>
    </Layout>
  );
};

export default profile;
```

**Comment by nickbrinser** [comment]
I haven't had any issues with it returning null all the time, but if you are unauthenticated then it won't redirect properly. 
If `getUser() ` is called while not authenticated, the user is returned as null and no error is logged. The function catches this case but does nothing with the error.

```ts
    let response: ResponsePayload = { user: null, accessToken: null };
    if (e instanceof JWTPayloadFailed) {
      logger.info('JWTPayloadFailed error has happened!');
      response.error = e.toObj();
    } else if (e instanceof AuthHelperError) {
      // do nothing, these are all just to disrupt the control flow
    } else {
      const error = e as ApiError;
      logger.error(error.message);
    }
    return response;
  }
```

It's worth noting that `auth-helpers-nextjs` is not currently compatible with NextJS 12.2 and up. I have a PR open that will update this though.

**Comment by lsbyerley** [comment]
@nickbrinser okay thanks for clarifying. I was also seeing a null user when authenticated which is why i originally filed this issue. I'll try downgrading my nextjs version

**Comment by lsbyerley** [comment]
I'm still undefined on next version `12.2.1` ... not sure why.

**Comment by nickbrinser** [comment]
I'm not sure if this will solve your issue but, you'd need to be under `12.2.X`. I believe the helpers are currently on `12.1.5`. Are you using typescript or js? If you're using typescript, you'll need to cast your user in your profile props. 
So something like - 
``` ts
  import { withPageAuth, User } from '@supabase/auth-helpers-nextjs'

  const profile = ({ user }: {user: User}) => {...}
```

**Comment by lsbyerley** [comment]
I am using `js` right now. I downgraded to the following and it did not resolve the issue. Any other ideas? Or is there a working codesandbox example somewhere?

`"@supabase/auth-helpers-nextjs": "0.2.7",`
`"@supabase/auth-helpers-react": "0.2.3",`
`"next": "12.1.5",`

**Comment by nickbrinser** [comment]
Those versions should be fine, so I'm not sure why you're still getting undefined. I don't have a codesandbox handy for this. 
Have you tried logging the error object returned by `getUser`?

**Comment by lsbyerley** [comment]
@nickbrinser it does not appear it is even going into the `async getServerSideProps()` function. If you'll notice in my snippet below, the console log is never seen

```
export const getServerSideProps = withPageAuth({
  redirectTo: '/',
  async getServerSideProps(ctx) {
    const { user, error } = await getUser(ctx);
    // this console log is never seen in the terminal
    console.log('LOG: ctx and error', ctx, error);
    return { props: { user } };
  },
});
```
