### ISSUE TITLE
Ability to access user object with `getUser` in Next.js middleware

### ISSUE THREAD

**Issue by noahflk** [supabase/auth-helpers#233]
# Feature request

## Is your feature request related to a problem? Please describe.

I need direct access to the user object in my middleware to check if they are allowed access. For this I need `getUser` (from `@supabase/auth-helpers-nextjs`) in order to decide if a user gets access.

`getUser` wants `ctx` from `getServerSideProps` as an argument. In a Next.js middleware I only get `request: NextRequest` and not a full context. How can I stil access the user from a middleware?

## Describe the solution you'd like

I'd like to use `getUser` in a Next.js middleware.

## Describe alternatives you've considered

For now I'm using `getServerSideProps` instead of a middleware. It works fine there

I am aware of `withMiddlewareAuth`. However, this is not sufficient for me since I need access to the whole user object. And I depend on conditional statements inside by middleware.

**Comment by nickbrinser** [comment]
Depending on what version of NextJS your using, you should be able to use 
`const user = await supabaseClient.auth.api.getUserByCookie(request)`? 
This _should_ work as long as you're under nextjs 12.2. Post 12.2 updates need to be made to `getUserByCookie` in the `gotrue` api.

**Comment by noahflk** [comment]
That's what I was doing before. However, as you said, it's no longer possible to do it in 12.2+

**Comment by nickbrinser** [comment]
Might be worth throwing a feature request over here to update `getUserByCookie` as well. 
https://github.com/supabase/gotrue-js/issues

I would open a PR for it but, I'm not sure what considerations need to be made for other frameworks.

**Comment by nickbrinser** [comment]
Have you looked using the `authGuard` in `withMiddlwareAuth`? That gives you access to user in `isPermitted`. 

 
This is from the most recent Next.js middleware example in this repo.
``` ts
export const middleware = withMiddlewareAuth({
  redirectTo: '/login',
  authGuard: {
    isPermitted: async (user) => user.email?.endsWith('@example.com') ?? false,
    redirectTo: '/insufficient-permissions'
  }
});
```

**Comment by noahflk** [comment]
That's interesting and solves one part of the problem. But I do need to run some more logic in there. For example I want access to the current route that's being accessed.

**Comment by nickbrinser** [comment]
It doesn't look like you have access to the request right now unfortunately. I had a similar use case and it would definitely require `getUser` in the middlware as you described in this feature request. So fingers crossed this happens.

**Comment by thorwebdev** [comment]
The next release will return the user object and an authenticated supabase client in the `isPermitted` method. You can already try it out with installing npm install @supabase/auth-helpers-nextjs@next and you can find the migration guide here: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/MIGRATION_GUIDE.md#migrating-to-03x

**Comment by noahflk** [comment]
That's amazing, thank you @thorwebdev
