### ISSUE TITLE
UserContext does not work correctly with @supabase/supabase-js v2

### ISSUE THREAD

**Issue by lyqht** [supabase/auth-helpers#234]
# Bug report

## Describe the bug

In Next.js, UserContext does not populate with user if used with @supabase/supabase-js v2. 
It works as per normal if I revert the package to v1.35.6.

## Expected behavior

UserContext to be populated correctly after login.

## Screenshots

The following error will always show upon initialization of the UserContext, even before login. 

<img width="417" alt="image" src="https://user-images.githubusercontent.com/35736525/185561604-118cf715-ecc6-4767-87b1-9219f29278be.png">

## System information

Chrome, MacOS

## Additional context

Understand from the twitter space AMA that the auth-helpers have not updated to accomodate v2, but I wished there was a more extensive changelog/ caveat notes on what will still work and what won't, in this repository.

**Comment by silentworks** [comment]
This library doesn't work with v2 as yet. There are some changes that need to be made first.

**Comment by Cryrivers** [comment]
I'm working on a fix for v2 and nextjs 12.2. However I'm still figuring out how to handle the deprecated and removed `setAuth`

**Comment by silentworks** [comment]
This is v2 and NextJS 12.2 compatibility is currently being worked on for this library.

**Comment by pcardosolei** [comment]
is this fixed?

when using OAuth Logins the user context does not maintain the session of the user. Trying to figure it out.

**Comment by thorwebdev** [comment]
You can already try it out with installing npm install @supabase/auth-helpers-nextjs@next and you can find the migration guide here: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/MIGRATION_GUIDE.md#migrating-to-03x
