### ISSUE TITLE
Provider token cookie not set on login - Impossible to run getProviderToken

### ISSUE THREAD

**Issue by mdolr** [supabase/auth-helpers#236]
# Bug report

Hello, here is a problem I've been experiencing when using the supabase Nextjs auth helper. I don't see what I'm doing wrong as I've just followed the documentation on the README.

## Context

I'm running the local version of supabase through the latest version of the supabase CLI in my development environment. I'm developping a web app that uses Twitch as a 3rd party auth provider. Twitch is the only way to connect to the app (passwords, magic link and all other providers are disabled) 

I'm using Next.js Typescript with the supabase-auth-helpers for nextjs. I would need to store and use the `provider_token` to run requests from my API.

## Describe the bug

When l login with Twitch on my web app the `sb-provider-token` cookie is not set by the auth helper.

This leads to an error when calling the `getProviderToken(ctx)` : `error - ProviderTokenNotFound [Error]: No provider token was found!`as I'm trying to reproduce something similar to the [Github example](https://github.com/supabase/auth-helpers/blob/c81d74910800573069b31a9576e69e2c7dd20554/examples/nextjs/pages/github-provider-token.tsx#L36)

Ideally I would like to retrieve the provider token directly from my API routes within the `req.cookies` but as of now I'm just trying to replicate the example with a protected page and `getServerSideProps` (page pasted below)

Note: The `sb-access-token` and `sb-refresh-token` cookies are set successfully, but the `sb-provider-token` is missing. I can also confirm that the `provider_token` is returned from the OAuth flow as I see it in the return URL

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Follow the tutorial situated in the [Next.JS Documentation README](https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/README.md) to setup your auth-helper

`/api/auth/[...supabase].ts` :
```ts
import { handleAuth } from "@supabase/auth-helpers-nextjs";

export default handleAuth({ logout: { returnTo: "/" } });
```

2. Login with Twitch as a 3rd party provider, here's what I'm using
```ts
await supabaseClient.auth.signIn(
    { provider: "twitch" },
    {
      scopes:
        "user:read:email channel:read:redemptions channel:manage:redemptions channel:read:vips channel:manage:vips moderation:read channel:manage:moderators bits:read",
      redirectTo: `${process.env.APPLICATION_URL}/dashboard`,
    }
  );
```
3. Go through the OAuth authorization flow
4. Visit the protected page with the following code
```ts
import { Container } from "@mui/material";
import {
  getProviderToken,
  getUser,
  supabaseServerClient,
  withPageAuth,
} from "@supabase/auth-helpers-nextjs";
import { NextPage } from "next";
import { useEffect } from "react";

const ProviderToken: NextPage = () => {
  return (
    <Container maxWidth="lg" sx={{ marginBottom: "96px", marginTop: "24px" }}>
      <div>Text</div>
    </Container>
  );
};

export default ProviderToken;


export async function getServerSideProps(ctx: any) {
  const { user } = await getUser(ctx);
  if (user) {
    try {
      console.log("user", user);
      const provider_token = getProviderToken(ctx);
      console.log("Provider token");
      console.log(provider_token);
    } catch (e) {
      console.error(e);
    }
  } else {
    console.log("no user");
  }

  return { props: {} };
}
```
5. See error message when running `getProviderToken(ctx)`

```
ProviderTokenNotFound [Error]: No provider token was found!
    at getProviderToken (/Users/maxime/Documents/streamtweaks/node_modules/@supabase/auth-helpers-nextjs/dist/index.js:336:11)
    at getServerSideProps (webpack-internal:///./pages/index.tsx:625:115)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.renderToHTML (/Users/maxime/Documents/streamtweaks/node_modules/next/dist/server/render.js:573:20)
    at async doRender (/Users/maxime/Documents/streamtweaks/node_modules/next/dist/server/base-server.js:915:38)
    at async cacheEntry.responseCache.get.isManualRevalidate.isManualRevalidate (/Users/maxime/Documents/streamtweaks/node_modules/next/dist/server/base-server.js:1020:28)
    at async /Users/maxime/Documents/streamtweaks/node_modules/next/dist/server/response-cache.js:69:36 {
  errorType: 'cookie_not_found',
  source: 'sb_auth_helpers'
}
```

Note: When running a `getServerSideProps` with `withPageAuth` like this 
```ts
export const getServerSideProps = withPageAuth({
  redirectTo: "/",
  async getServerSideProps(ctx) {
    // Retrieve provider_token from cookies
    const provider_token = await getProviderToken(ctx);
    console.log("Provider token");
    console.log(provider_token);

    return { props: {} };
  },
});
```

I just don't get any error neither do I get the provider token

## Expected behavior

The `sb-provider-token` cookie gets attached and the `getProviderToken(ctx)` functions returns the provider token successfully when the user is logged in.

## Project information

- Supabase CLI : v1.0.5
- @supabase/auth-helpers-nextjs : v.0.2.7
- @supabase/auth-helpers-react : v0.2.3
- @supabase/supabase-js : v1.35.4
- react : v18.2.0

All of my local development is running on a M1 Mac through the Supabase CLI.

Thank you for looking into my issue 🙏

**Comment by dukesx** [comment]
Seconded, the oAuth flow is either very poorly documented or just has bugs in it. This has also caused hiccups in my project as well. I don't get it, how come dev.to can fetch the data after oAuth so fast while Supabase takes almost 2 seconds to fetch the cookie on client side. 

Here is a workaround i am using:

use a useEffect hook, wait for 2000ms using setTimeOut and then check for the tokens. You will have it. Don't do it server side, it will not work. Your only way in is client side and that too you have to wait for a few seconds. 

```tsx
  useEffect(() => {
    if (feedLoading == false) {
      setFeedLoading(true);
    }

    // setTimeout(() => getFeed(), 2000);
    if (isLoading == false) {
      getFeed();
    }
  }, [key, user, isLoading]);
```
In this example, i am determining if user is logged in or logged out. Depending on that, fetch the feed of articles. As you can see, being logged in matters a-lot in this case. if i wait under 2000ms, i get the wrong data. Waiting for appropriate amount of time makes it usable.

**Comment by mdolr** [comment]
> Seconded, the oAuth flow is either very poorly documented or just has bugs in it. This has also caused hiccups in my project as well. I don't get it, how come dev.to can fetch the data after oAuth so fast while Supabase takes almost 2 seconds to fetch the cookie on client side.

I think this particular issue is different from the one I'm experiencing because in the end after your timeout you get access to the cookie.

From what I've seen my issue only occurs on the local development environment and literally never sets the provider_cookie even after a timeout, it's not sent in server-side requests as well. However with the same code I don't have any problems once my app is deployed with the production Supabase environment.

**Comment by dukesx** [comment]
> > Seconded, the oAuth flow is either very poorly documented or just has bugs in it. This has also caused hiccups in my project as well. I don't get it, how come dev.to can fetch the data after oAuth so fast while Supabase takes almost 2 seconds to fetch the cookie on client side.
> 
> I think this particular issue is different from the one I'm experiencing because in the end after your timeout you get access to the cookie.
> 
> From what I've seen my issue only occurs on the local development environment and literally never sets the provider_cookie even after a timeout, it's not sent in server-side requests as well. However with the same code I don't have any problems once my app is deployed with the production Supabase environment.

From what I have seen, in Supabase V2 and Gotrue RC release has these issues solved. Since, the backend code is now async in V2 as compared to v1 and you also get a async method such as getUser to await a user, which will never return null unless you aren't logged in compared to v1 where user is still returned null initially when logged in.

As for server side, you can't do it. Just can't. The auth flow doesn't agree. When you get a success response from oAuth, the cookie has to be set and it can't be set server side since you are just returning from providers page. So when you land on client, only then can the cookie be set and then later on after full page refresh, the server can access cookie. You have to manage oAuth client side or you need to opt for email password auth/phone which can set the cookie on success immediately and then you can redirect without issues.

**Comment by dukesx** [comment]
You can technically do it server side too for oAuth but then you will need a custom middleware to intercept the success params but then you won't have the freedom to redirect on demand. The current middleware doesn't support that I think.

**Comment by thorwebdev** [comment]
Provider token is now persisted on the session object: https://github.com/supabase/auth-helpers/blob/main/examples/nextjs/pages/github-provider-token.tsx
