### ISSUE TITLE
withMiddlewareAuth to work with nextjs 12.2 new middleware

### ISSUE THREAD

**Issue by alexverdaguer** [supabase/auth-helpers#237]
With the introduction of the new Next.js middleware in version 12.2, withMiddlewareAuth doesn't work.

Is there a workaround right now ?

Thank you.

**Comment by megacherry** [comment]
There are two pull requests for this. I hope they will be merged soon.

https://github.com/supabase/auth-helpers/pull/227
https://github.com/supabase/auth-helpers/pull/170

**Comment by 413n** [comment]
Hey guys @thorwebdev @silentworks, hope you are doing well.
I would like to ask you to please take an action on this problem.
It has been nearly **2 months** that the 12.2 was released.
Currently there are 2 open PRs for supporting NextJS 12.2 and none of them are still approved/merged.
Unfortunately this repo is blocking us to go on with the new features that NextJS offers (without having to write our own SSR handler).
So I ask you if you could come up with the solution you prefer (also taking inspiration from the 2 PRs) and please ship it as soon as possible.
Thanks in advance

**Comment by alexverdaguer** [comment]
I join the comment of @413n., we are also blocked because of this issue.

Please could you have a look at the open PR.

Thanks in advance

**Comment by olegkorol** [comment]
I am using this workaround at the moment:

### /src/middleware.js

> Placed within `/src`, because nested middlewares are not allowed in Next.js 12.2. 
For instance, `/src/pages/with-middleware/_middleware.js` would not work (Next.js throws an error).
Using [conditional statements](https://nextjs.org/docs/advanced-features/middleware#conditional-statements) to get the same functionality as a nested middleware.

> Assuming the middleware needs to target `/middleware-protected/*` routes.

> Assuming unauthenticated users are redirected to `/login`.

```javascript
import { NextResponse } from 'next/server'

export async function middleware(request, event) {
  if (request.nextUrl.pathname.startsWith('/middleware-protected')) {
    const accessToken = request.cookies.get('sb-access-token')
    const refreshToken = request.cookies.get('sb-refresh-token')
    let sbUser

    if (!accessToken && !refreshToken) {
      // Not authenticated
      return NextResponse.redirect(new URL('/login', request.url))
    }
    
    try {
      const response = await fetch(String(new URL('/api/auth/user', request.url)), {
        headers: {
          Cookie: `sb-access-token=${accessToken}, sb-refresh-token=${refreshToken}`,
        },
      })
      const { user } = await response.json()
      sbUser = user
    } catch (error) {
      console.error({error})
      // Error fetching user data
      return NextResponse.redirect(new URL('/login', request.url))
    } finally {
      if (!sbUser) {
        // Not authenticated
        return NextResponse.redirect(new URL('/login', request.url))
      }
      // Authenticated
      return NextResponse.next()
    }

  }
}
```

**Comment by clodal** [comment]
Should this issue be closed by https://github.com/supabase/auth-helpers/pull/227?
