### ISSUE TITLE
Auth does not work on phone's browser

### ISSUE THREAD

**Issue by rafamessias** [supabase/auth-helpers#241]
# Bug report

## Describe the bug

Users are unable to login into App via iPhone (using google chrome or safari browser). The user object (from useUser) always returns null.
Authentication is via google as a provider.

It works on develpment env, but when deployed at Vercel and accessing it via phone's browser, user object is always null.

## To Reproduce

1. Go to login page
2. Login using google provider
3. Authenticate via google
4. The page returns to login and the user object remains null.

### Auth login page - src/pages/login/index.js
```
  const googleLogin = async () => {
    const { error: authError } = await supabaseClient.auth.signIn(
      {
        provider: "google",
      },
      {
        redirectTo: `${currentUrl}${_redirectToPlanPro ? "?plan=pro" : ""}`,
      }
    );

    if (authError) console.log(authError);
  };
```
### Auth api - src/pages/api/auth/[...supabase].js
```
import { handleAuth } from "@supabase/auth-helpers-nextjs";

export default handleAuth({
  logout: { returnTo: "/login" },
});
```

## Expected behavior

After the user authenticates via google, the app should be redirected to /

## System information

- OS: Ubuntu 22.04
- Browser: chrome and safari
- Version of supabase-js: 1.29.1
- Version of @supabase/auth-helpers-nextjs: 0.2.7
- Version of @supabase/auth-helpers-react: 0.2.3
- Version Next: 12.1.6
- Version next-pwa: 5.6.0
- Version of Node.js: 15.2.1

**Comment by thorwebdev** [comment]
Can you confirm that your app root is wrapped in the `<UserProvider>`? 

If yes, can you check that upon returning from Oauth, you're not hitting a SSR page but rather a client-side page and check the console for network requests to your auth route? 

E.g. after Oauth you need to return to the client and wait for the user to become set. Once set you can redirect to your gated pages: https://github.com/vercel/nextjs-subscription-payments/blob/main/pages/signin.tsx#L58-L62

**Comment by thorwebdev** [comment]
Closing out as stale. Please reopen with additional information if needed. Thanks.
