### ISSUE TITLE
Supabase + Twitter Auth Error : Failed Login / can't read user's email even with elevated account.

### ISSUE THREAD

**Issue by ethanchiasson** [supabase/auth-helpers#246]
# Bug report

## Describe the bug

There have been a few discussions on this topic regarding Twitter Authentication. 
https://github.com/supabase/auth-helpers/issues/100
and 
https://github.com/supabase/supabase/discussions/4677

It seems as though the consensus is that you must get an `elevated` account, which is required to read a user's email ( and thus, required for Supabase's Auth to work ).

The issue I have is, even after upgrading to an `elevated` twitter status, I still get the error `http://localhost:3000/?error=server_error&error_description=Error+getting+user+email+from+external+provider` when trying to login with Twitter.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a supabase project with twitter authentication enabled and upgrade your Twitter Developer Account to `elevated` status
2. Login with Twitter - watch Twitter auth flow work fine until...
3. User is redirected to the original login page ( not logged in ) , and sees this error message in the URL `http://localhost:3000/?error=server_error&error_description=Error+getting+user+email+from+external+provider`
4. Note: At this point, the user is not authenticated in Supabase

## Expected behavior

The user should be authenticated in Supabase. I first thought this error was happening because I did not have an `elevated` Twitter developer account, but after receiving it from Twitter I still get the same error as without the elevated status.

## Additional context

One user mentioned that they had to change some unspecified settings within Twitter's Developer Portal, but upon investigation it seems as though the user interface has changed and I did not see anything that seemed like it would fix the issue. These fixes more likely no longer apply.

I would appreciate any help on this. I am not sure why this is happening. My guess is that there is an update within Twitter / Auth that is causing the issues. I would also suggest updating the docs here : https://supabase.com/docs/guides/auth/auth-twitter - the current documentation has no reference to the account upgrade ( which is needed to obtain the email from a user's auth ; at least, according to the post linked above ).

**Comment by mikelxc** [comment]
Same issue here, able to get github and discord working without any problem. OAuth 2.0 keys would return {"message":"No API key found in request"}, and unable to get email address for consumer keys

**Comment by ethanchiasson** [comment]
> Same issue here, able to get github and discord working without any problem. OAuth 2.0 keys would return {"message":"No API key found in request"}, and unable to get email address for consumer keys

Sad to hear, but it also helpful knowing someone else is experiencing the same issues with Twitter *only* - that might help narrow down the cause of the issue. 

I also tried using the v2 Auth keys, and various mixed combinations of different key/secret pairs, but nothing seemed to work.

I made a discussion on this topic because Twitter Auth seems to have had a lot of bugs in the past and I thought I would try to make a centralized outline of various issues and their fixes in hopes it gets some attention.

https://github.com/supabase/supabase/discussions/8996

**Comment by kangmingtay** [comment]
Hey @ethanchiasson and @mikelxc, this seems like an issue with the oauth app being set up on twitter and not one with the auth-helpers library. Based on some of the previous issues we've encountered with developers setting up "sign-in with twitter", some of them missed out checking the following:

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/28647601/192719796-74b4c1cf-f387-4771-9b7a-845cc38efc46.png">

If you guys are still experiencing this issue, please reach out to us at [support](https://app.supabase.com/support/new).
