### ISSUE TITLE
`User` typing is unresolved in generated types in `auth-helpers-nextjs`

### ISSUE THREAD

**Issue by Xananax** [supabase/auth-helpers#249]
# Bug report

## Description

If I use `@supabase/auth-helpers-nextjs` in my Next + Typescript project, the function `getUser` does not resolve properly the returned type.

## To Reproduce

Create a file `test.js` inside a Next project. Write the following in it:

```ts
import { getUser } from '@supabase/auth-helpers-nextjs'
import { GetServerSidePropsContext } from 'next'

const test = async (context: GetServerSidePropsContext) => {
  const {user} = await getUser(context)
}
```

Hover the returned `user` variable, and verify it resolves to "any":
![image](https://user-images.githubusercontent.com/836082/190400311-28ec76eb-491b-4720-8340-564f26a2fccf.png)

This is not dependent on using `await`, "then style" has a similar behavior

```ts
const test2 = (context: GetServerSidePropsContext) => {
  getUser(context).then(({user}) => {
    user
  })
}
```

![image](https://user-images.githubusercontent.com/836082/190400466-3cb1b403-ed58-4fa5-8098-8be2f38211b8.png)

In both cases, `user` cannot autocomplete (expectedly):

![image](https://user-images.githubusercontent.com/836082/190400779-e7f1b8a5-a03d-49b4-8093-0e6a10ee67a6.png)

## Expected behavior

It's expected that `user` resolves to the `User` type and autocompletes/checks properly in typescript.

Adding this line in `node_modules/@supabase/auth-helpers-nextjs/dist/index.d.ts` fixes the problem:

```ts
import { User } from '@supabase/supabase-js';
```

![image](https://user-images.githubusercontent.com/836082/190401020-7849a109-ab69-4be1-9a67-b7d387d2c467.png)
![image](https://user-images.githubusercontent.com/836082/190401047-8fe273eb-487a-4e58-83a8-3ec3fb0c247c.png)

Another workaround is to explicitly cast `user` at call site:

```ts
import { getUser, User } from '@supabase/auth-helpers-nextjs'
import { GetServerSidePropsContext } from 'next'

const test = async (context: GetServerSidePropsContext) => {
  const {user} = (await getUser(context)) as { user: User }
}
```

## Hypothesis

It seems that the generated definition file only _exports_ the `User` type, since importing it and casting it works properly. Indeed, the definition file has the line:

```ts
export { SupabaseClient, User } from '@supabase/supabase-js';
```

But it never _imports_ the definition, and therefore, `ResponsePayload` cannot resolve it:
![image](https://user-images.githubusercontent.com/836082/190401594-efb1bad5-64ce-44fb-a502-83de257128a9.png)

This is puzzling because the original typescript file [`getUser.ts`](https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/src/utils/getUser.ts#L6) does specifically import those definitions.

This would lead me to think the error is in the way the definition file is created.

Of note: A (different?) `ResponsePayload` is present in [`user.ts`](https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/src/handlers/user.ts#L17) which seems to be flawed: the `user` member is specified as `null` even though the function can and does return a User in success cases.

## System information

- OS: Arch Linux
- Version of supabase-js: 1.35.4
- Version of auth-helpers-nextjs: 0.2.5
- Version of Node.js: v16.9.1

**Comment by nickbrinser** [comment]
Linking this issue for visibility. Really nice breakdown of the problem here. Definitely a strange issue.
#213

**Comment by Xananax** [comment]
Ah it's a duplicate then! Damn it, I was sure to have searched properly. I don't know how I missed your report. I'll close in favor of yours.

**Comment by nickbrinser** [comment]
No worries, I found your breakdown helpful. I think this is most likely an issue with the pnpm workspace and how dependencies are being managed between packages.
