### ISSUE TITLE
Middleware Helper no Longer Working

### ISSUE THREAD

**Issue by francistogram** [supabase/auth-helpers#251]
# Bug report

## Describe the bug

Using the `import { withMiddlewareAuth } from "@supabase/auth-helpers-nextjs/dist/middleware";` am getting `TypeError: req.cookies.get is not a function` which looks like it's coming from https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/src/middleware/withMiddlewareAuth.ts#L61

## To Reproduce

With `"@supabase/auth-helpers-nextjs": "0.2.8"` this will fail with the above errors. Downgrade to 0.2.7 and the error goes away

```javascript
import { NextFetchEvent, NextRequest, NextResponse } from "next/server";

import { withMiddlewareAuth } from "@supabase/auth-helpers-nextjs/dist/middleware";

export const middleware = async (req: NextRequest, event: NextFetchEvent) => {
  const { pathname } = req.nextUrl;

  if (
    pathname.startsWith("/api") ||
    pathname.startsWith("/static") ||
    pathname.startsWith("/login") ||
    pathname.startsWith("/loading-user") ||
    pathname.includes(".")
  ) {
    return NextResponse.next();
  }

  return withMiddlewareAuth({
    redirectTo: "/login",
    authGuard: {
      isPermitted: async (user) => {
        return user.email?.endsWith("@company.com") ?? false;
      },
      redirectTo: "/login",
    },
  })(req, event);
};
```

## Expected behavior

`withMiddlewareAuth` would be able to read from the cookies to get the user

## System information

- OS: macOS 12.5.1
- Browser (if applies): Brave
- Version of supabase-js: 1.35.4
- Version of Node.js: 18.9.0
- Version of @supabase/auth-helpers-nextjs: 0.2.8,

## Additional context

This was actually working for me for the last 3 months just fine and then all of a sudden started to fail. Timeline matches up to the most recent deploy 9 hours ago https://www.npmjs.com/package/@supabase/auth-helpers-nextjs

**Comment by nickbrinser** [comment]
What version of `nextjs` have you been using in your project with `@supabase/auth-helpers-nextjs: 0.2.7`? 

If you were using anything above nextjs v12.2 with `auth-helpers`, up until 0.2.8 it would not work properly. 0.2.8 fixes breaking changes introduced by updating nextjs in `auth-helpers`, and adopts the new middlware api from nextjs. The readme and nextjs examples should be updated to reflect this.

**Comment by francistogram** [comment]
Ah that sounds like it's it, I'm on `next@12.1.6`

Good to know, will close the "bug" and upgrade my `next` version. Thanks for the help!
