### ISSUE TITLE
Injecting type definition with supabase V2.

### ISSUE THREAD

**Issue by roker15** [supabase/auth-helpers#252]
Recently supabase V2 has given type support injection 

```
import { createClient } from '@supabase/supabase-js'
import { Database } from 'lib/database.types'

const supabase = createClient<Database>(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_ANON_KEY
)
```

How to do this with  `{ supabaseClient } from "@supabase/auth-helpers-nextjs";`

**Comment by kmiyashiro** [comment]
Apparently the auth helpers lib uses supabase client v1.35 so this is not possible until it is ported to 2.0.

**Comment by roker15** [comment]
> Apparently the auth helpers lib uses supabase client v1.35 so this is not possible until it is ported to 2.0.

when porting?

**Comment by silentworks** [comment]
There is a next branch which is making use of v2. You can install it by running

```sh
npm install @supabase/auth-helpers-nextjs@next
```

**Comment by roker15** [comment]
> There is a next branch which is making use of v2. You can install it by running
> 
> ```shell
> npm install @supabase/auth-helpers-nextjs@next
> ``

Yes but there is no documentation for this, is there?

**Comment by thorwebdev** [comment]
Documentation here: 
- Migration guide: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/MIGRATION_GUIDE.md#migrating-to-03x
- Docs: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/README.md#basic-setup

**Comment by roker15** [comment]
> Documentation here:
> 
> * Migration guide: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/MIGRATION_GUIDE.md#migrating-to-03x
> * Docs: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/README.md#basic-setup

I went through documentation and tried but no success 

See this issue [No typing available with supabase V2](https://github.com/supabase/auth-helpers/issues/273#issue-1391810079)
