### ISSUE TITLE
Error on building nextjs project with auth helpers

### ISSUE THREAD

**Issue by singh05** [supabase/auth-helpers#261]
```Shell
Failed to compile.

./node_modules/@supabase/auth-helpers-react/src/components/UserProvider.tsx
Module parse failed: Unexpected token (22:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| let networkRetries = 0;
> let refreshTokenTimer: ReturnType<typeof setTimeout>;
| 
| const UserContext = createContext<UserState | undefined>(undefined);

Import trace for requested module:
./node_modules/@supabase/auth-helpers-react/src/components/UserProvider.tsx


```

**Comment by silentworks** [comment]
Please provide more information like the version of nextjs you are using and which version of the auth helpers you are using.

**Comment by singh05** [comment]
"next": "12.3.1",
"react": "18.2.0",
"react-dom": "18.2.0",
"@supabase/supabase-js": "^1.35.7",
"@supabase/auth-helpers-nextjs": "^0.2.8",
 "@supabase/auth-helpers-react": "^0.2.4",

**Comment by singh05** [comment]
![Uploading Screenshot 2022-09-27 at 11.24.38 AM.png…]()

**Comment by thorwebdev** [comment]
Could you try installing the next release `npm install @supabase/auth-helpers-nextjs@next` and see if that works for you. You can see the migration guide here: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/MIGRATION_GUIDE.md#migrating-to-03x
