### ISSUE TITLE
Imports cause ERR_MODULE_NOT_FOUND due to no extensions

### ISSUE THREAD

**Issue by jamalmoir** [supabase/auth-helpers#268]
# Bug report

## Describe the bug

I'm trying to use the sveltekit helpers and am getting errors like the following for all imports:
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/.../node_modules/@supabase/auth-helpers-sveltekit/dist/config' imported from /Users/.../node_modules/@supabase/auth-helpers-sveltekit/dist/server/utils/cookies.js at new NodeError (node:internal/errors:393:5) at finalizeResolution (node:internal/modules/esm/resolve:305:11) at moduleResolve (node:internal/modules/esm/resolve:866:10) at defaultResolve (node:internal/modules/esm/resolve:1074:11) at nextResolve (node:internal/modules/esm/loader:163:28) at ESMLoader.resolve (node:internal/modules/esm/loader:838:30) at ESMLoader.getModuleJob (node:internal/modules/esm/loader:425:18) at ModuleWrap. (node:internal/modules/esm/module_job:76:40) at link (node:internal/modules/esm/module_job:75:36)

I believe this to be because of "type": "module", in my package.json and imports not using the .js extensions inside of this library.

## To Reproduce

Steps to reproduce the behaviour, please provide code snippets or a repository:

1. Create a sveltekit app
2. Follow auth-helpers sveltekit documentation
3. Go to a page that uses auth-helpers

## Expected behaviour

Imports work correctly

## Screenshots

![image](https://user-images.githubusercontent.com/5795359/192506466-c7302578-11c3-4a25-822d-5225a7a5beed.png)

## System information

- OS: macOS
- Browser: firefox
- Version of supabase-js: ^1.35.6
- Version of Node.js: 16.15.0 (have also tried 18.9.1)

## Additional context

N/A

**Comment by silentworks** [comment]
This should be fixed now thanks to the PR from @david-plugge https://github.com/supabase/auth-helpers/pull/267

**Comment by jamalmoir** [comment]
Confirmed Fixed - Thanks @david-plugge and @silentworks
