### ISSUE TITLE
Update auth-helpers-nextjs to supabase v2jrc

### ISSUE THREAD

**Issue by CsarChvz** [supabase/auth-helpers#279]
# Feature request
Try to update the update-helpers-nextjs for the version2
## Is your feature request related to a problem? Please describe.
I got a "TypeError: supabaseClient.auth.signIn is not a function" -- Only with these methods, because with the signUp wasn't a change

## Describe the solution you'd like
I'd like an update of auth-helpers version to v2

## Additional context
I was trying to use the auth-helper and i got an error when a i tried to signIn an user with email and password
"TypeError: supabaseClient.auth.signIn is not a function". I searched the error and i found this https://github.com/supabase/supabase-js/issues/526, they said that was a problem of the "auth-helpers" package...

**Comment by sid-js** [comment]
### New Auth Types

Supabase.js v2 removed the signIn() method in favor of more explicit function signatures: signInWithPassword(), signInWithPasswordless(), and signInWithOtp(). So you should use them instead.

```
// v2
const { data } = await supabase.auth.signInWithPassword({
  email: 'hello@example',
  password: 'pass',
})
// v1
const { data } = await supabase.auth.signIn({
  email: 'hello@example',
  password: 'pass',
})
```

Read more on [their migration guide ](https://supabase.com/docs/reference/javascript/next/release-notes)

**Comment by sid-js** [comment]
### New Auth Types

Supabase.js v2 removed the signIn() method in favor of more explicit function signatures: signInWithPassword(), signInWithPasswordless(), and signInWithOtp(). So you should use them instead.

```
// v2
const { data } = await supabase.auth.signInWithPassword({
  email: 'hello@example',
  password: 'pass',
})
// v1
const { data } = await supabase.auth.signIn({
  email: 'hello@example',
  password: 'pass',
})
```

Read more on [their migration guide ](https://supabase.com/docs/reference/javascript/next/release-notes)

**Comment by thorwebdev** [comment]
For usage with supabase-js V2 RC please use the next release `npm install @supabase/auth-helpers-nextjs@next` `npm install @supabase/auth-helpers-react@next`.

You'll want dependencies to look like this:
```js
"@supabase/auth-helpers-nextjs": "^0.4.0-next.3", 
"@supabase/auth-helpers-react": "^0.3.0-next.2",
"@supabase/supabase-js": "^2.0.0-rc.10",
```

You can find the migration docs here: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/MIGRATION_GUIDE.md and you can see the changes involved to an existing application here: https://github.com/vercel/nextjs-subscription-payments/pull/128/files

**Comment by MincePie** [comment]
Is there an example of how to include email/password auth in a nextjs supabase app. I can see this, but am looking to see how to connect the form to this.
```

"use client";

import {
  Session,
  createClientComponentClient,
} from "@supabase/auth-helpers-nextjs";
import { useRouter } from "next/navigation";

export default function AuthButtonEmail({
  session,
}: {
  session: Session | null;
}) {
  const supabase = createClientComponentClient();
  const router = useRouter();

  const handleSignOut = async () => {
    await supabase.auth.signOut();
    router.refresh();
  };

  const handleEmailLogin = async () => {
    const { error } = await supabase.auth.signInWithPassword({
        email: 'you@yourwork.com',
        password: 'password'
    });

    if (error) {
        console.log({ error });
    }
   };

  return session ? (
    <button onClick={handleSignOut}>Logout</button>
  ) : (
    <button onClick={handleEmailLogin}>Login</button>
  );
}
```
