### ISSUE TITLE
Unable to update user's password (Sveltekit)

### ISSUE THREAD

**Issue by maxkozlowski** [supabase/auth-helpers#280]
# Bug report

## Describe the bug

Updating user's password with `supabaseClient.auth.update` doesn't work. I've created a [minimal repo](https://github.com/maxkozlowski/auth-sveltekit-reset-password-test) where user can register/login and reset their password. Password reset fails and returns an error "User not logged in".

## To Reproduce

1. Go to [this repo](https://github.com/maxkozlowski/auth-sveltekit-reset-password-test) and download it.
2. Get from a Supabase project URL and API keys and paste into `.env` file.
3. Register a new user, log out and try resetting password by going to ".../reset-password".
4. Go to your email and hit the link.
5. Set the new password, log out the user and try using the new password. It won't work.

## Expected behavior

The password should get updated.

## System information

- OS: [Windows]
- Browser [firefox]
- Version of supabase-js: [1.35.6]
- Version of supabase/auth-helpers-sveltekit: [0.7.1]
- Version of Node.js: [18.10.0]

**Comment by david-plugge** [comment]
You need to use the authenticated supabase instance because how would supabase know which user wants to reset his password. Take a look at [protecting actions](https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/README.md#protecting-actions), tell me if it works :)

**Comment by maxkozlowski** [comment]
Thank you David! It did work.

The only thing is that I ended up using `supabaseClient.auth.api.updateUser` with accessToken parameter rather than the recommended `supabaseClient.auth.update`. Not too sure how to use the latter.

The code I used:

```
import type { Actions } from './$types';
import { withAuth } from '@supabase/auth-helpers-sveltekit';
import { supabaseClient } from '$lib/db';

export const actions: Actions = {
	sukces: withAuth(async ({ session, request }) => {

		const formData = await request.formData();
        const password = formData.get('password') as string;

		let accessToken = String(session.accessToken);

        const { user, error } = await supabaseClient.auth.api.updateUser(accessToken, {
			password: password,
		})

		return {
			success: true,
		};
	})
};
```

**Comment by david-plugge** [comment]
You can use `getSupabase(event)` now to get a supabase instance that is scoped to the current user

```
const { supabaseClient } = await getSupabase(event)
```
