### ISSUE TITLE
TypeError: authListener.unsubscribe is not a function

### ISSUE THREAD

**Issue by sid-js** [supabase/auth-helpers#281]
# authListener.unsubscribe is not a function

## Describe the bug

While using the UserProvider component from auth-helpers-react package, it gives the following error :
TypeError: authListener.unsubscribe is not a function

![image](https://user-images.githubusercontent.com/94698713/193580057-91097266-d3d4-4694-82f4-f1efcaf8240c.png)

## To Reproduce

Steps to reproduce the behavior,

1. Wrap the <App/> Component with <UserProvider> component from auth-helpers-react package.
2. Run the dev build script and visit the page.

## Expected behavior

The authListener should unsubscribe properly.

## System information

- OS: [Windows]
- Version of supabase-js: 2.0.0-rc.10
- Version of @supabase/auth-helpers-react - 0.2.4
- Version of Node.js: v16.13.0

#282

**Comment by sid-js** [comment]
Found the code which was causing this error. Fixed it and created a PR.
#262

**Comment by sid-js** [comment]
Found a workaround for this and created a pull request. 
#282

**Comment by adolfoportilla** [comment]
Running as well into the same issue

**Comment by sid-js** [comment]
> Running as well into the same issue

If you want a quick workaround until they update it, just copy the `UserProvider.tsx` into your src folder and import that into your `_app.js` from there.

In the UserProvider.tsx , find the `authListener.unsubscribe()` line and edit it to `authListener.subscription.unsubscribe()`.

This should do the work temporarily.

**Comment by thorwebdev** [comment]
For usage with supabase-js V2 RC please use the next release `npm install @supabase/auth-helpers-nextjs@next` `npm install @supabase/auth-helpers-react@next`.

You'll want dependencies to look like this:
```js
"@supabase/auth-helpers-nextjs": "^0.4.0-next.3", 
"@supabase/auth-helpers-react": "^0.3.0-next.2",
"@supabase/supabase-js": "^2.0.0-rc.10",
```

You can find the migration docs here: https://github.com/supabase/auth-helpers/blob/next/packages/nextjs/MIGRATION_GUIDE.md and you can see the changes involved to an existing application here: https://github.com/vercel/nextjs-subscription-payments/pull/128/files

**Comment by alexandargyurov-ka** [comment]
Using @thorwebdev's dependencies, here is the rest of the code to make everything work 🙂 

```
//package.json
"@supabase/auth-helpers-nextjs": "^0.4.0-next.3", 
"@supabase/auth-helpers-react": "^0.3.0-next.2",
"@supabase/supabase-js": "^2.0.0-rc.10"
```

```ts
//_app.tsx
import { createBrowserSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { SessionContextProvider } from "@supabase/auth-helpers-react";

import type { AppProps } from "next/app";
import { useState } from "react";

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  const [supabaseClient] = useState(() => createBrowserSupabaseClient());

  return (
    <SessionContextProvider supabaseClient={supabaseClient}>
      <Component {...pageProps} />
    </SessionContextProvider>
  );
}

export default MyApp;
```

To use `useUser()` and `supabaseClient`:

```ts
//Component.tsx
import { createBrowserSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { useUser } from "@supabase/auth-helpers-react";
import { useState } from "react";

export function Component(): JSX.Element {
  const [supabaseClient] = useState(() => createBrowserSupabaseClient());
  const user = useUser();
  
  return <>...</>
}
```

Hope this helps!

**Comment by alexandargyurov** [comment]
Using @thorwebdev's dependencies, here is the rest of the code to make everything work 🙂 

```
//package.json
"@supabase/auth-helpers-nextjs": "^0.4.0-next.3", 
"@supabase/auth-helpers-react": "^0.3.0-next.2",
"@supabase/supabase-js": "^2.0.0-rc.10"
```

```ts
//_app.tsx
import { createBrowserSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { SessionContextProvider } from "@supabase/auth-helpers-react";

import type { AppProps } from "next/app";
import { useState } from "react";

function MyApp({ Component, pageProps }: AppProps): JSX.Element {
  const [supabaseClient] = useState(() => createBrowserSupabaseClient());

  return (
    <SessionContextProvider supabaseClient={supabaseClient}>
      <Component {...pageProps} />
    </SessionContextProvider>
  );
}

export default MyApp;
```

To use `useUser()` and `supabaseClient`:

```ts
//Component.tsx
import { createBrowserSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { useUser } from "@supabase/auth-helpers-react";
import { useState } from "react";

export function Component(): JSX.Element {
  const [supabaseClient] = useState(() => createBrowserSupabaseClient());
  const user = useUser();
  
  return <>...</>
}
```

Hope this helps!

**Comment by OsmnShkh** [comment]
I had the same issue and following @alexandargyurov's comment resolved the error. Thanks!
