### ISSUE TITLE
Auth UI with social providers throws attribute error

### ISSUE THREAD

**Issue by lifedup** [supabase/auth-helpers#284]
# Bug report
Auth UI with social providers throws attribute error for the button.

## Describe the bug

The default Auth UI throws an error when social auth provider buttons are added.

```
next-dev.js?36dd:20 Warning: Received `false` for a non-boolean attribute `loading`.
If you want to write it to the DOM, pass a string instead: loading="false" or loading={value.toString()}.
If you used to conditionally omit it with loading={condition && value}, pass loading={condition ? value : undefined} instead.
    at button
    at Button (webpack-internal:///../../node_modules/@supabase/auth-ui-react/dist/esm/src/components/UI/Button.js:57:5)
   ...
```

## To Reproduce
Install the auth UI and add it to a page with social providers

```
import { Auth } from "@supabase/auth-ui-react";
<Auth providers={["google"]}  supabaseClient={supabase} />
```

**Comment by silentworks** [comment]
You've opened this issue in the wrong repo. The is an Auth UI issue and should be opened over at the https://github.com/supabase-community/auth-ui repo
