### ISSUE TITLE
Next.js: Cannot sign in with specfic `redirectTo` option

### ISSUE THREAD

**Issue by itta611** [supabase/auth-helpers#287]
# Bug report
Hi, I have a problem with signIn using auth.

When `redirectTo` is not the origin path (ex. http://localhost:3000/login), the redirect works properly but the sign in is not working.

The callback from the *****.supabase.co/auth/v1/user returns the correct session, while http://localhost:3000/api/auth/user don't returns the session.

I tested without using Next.js helper, and it works.

Code:
```JS
const signInWithGoogle = async () => {
  await supabase.auth.signIn(
    {
      provider: 'google',
    },
    { redirectTo: `${window.location.origin}` } // This works
  );
};
```
```JS
const signInWithGoogle = async () => {
  await supabase.auth.signIn(
    {
      provider: 'google',
    },
    { redirectTo: `${window.location.origin}/login` } // This doesn't works
  );
};
```

## To Reproduce

https://user-images.githubusercontent.com/86896657/194559160-6a27d802-5a56-426f-85fc-93ac2f69b8df.mov

## System information

- OS: macOS
- Browser (if applies) Google Chrome
- Version of supabase-js: latest
- Version of Node.js: 16.13.0

**Comment by danielvanc** [comment]
I have this issue as well, with trying to sign in with Github, but in a Remix app. When oAuth returns, and I console log the session in the loader of the page it returns too, the session is null. But on the client, there is an authenticated user object.

**Comment by silentworks** [comment]
This would either be due to the `redirectTo` url not being added to the allowlist of redirects inside the dashboard or due to the `/login` page being behind a server-side rendering (SSR) page which has auth protection.
