### ISSUE TITLE
setupSupabaseHelpers called multiple times

### ISSUE THREAD

**Issue by CanRau** [supabase/auth-helpers#288]
# Bug report

## Describe the bug

Every now and then I get

```
Error: `setupSupabaseHelpers` called multiple times
    at Proxy.setupSupabaseHelpers ([..]/node_modules/@supabase/auth-helpers-sveltekit/dist/config.js:8:15)
    at [..]/src/lib/db.ts:17:0
    at async instantiateModule ([..]/node_modules/vite/dist/node/chunks/dep-db16f19c.js:53436:9)
```

Still can't really pinpoint when it happens, though it's probably to do with hot reload in dev

Just found https://github.com/supabase/auth-helpers/blob/bead33e66320006630c80cb0a1a7eec14d4db482/packages/sveltekit/src/config.ts#L22

Does it have to `throw`, couldn't it "just" return the existing config?

I''m pretty sure I've set up `@supabase/auth-helpers-sveltekit` properly according to the [auth guide](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit)

## To Reproduce

Can't provide a repro right now, as stated I followed the [guide](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit) closely, just upgraded SvelteKit from `next.505` to `next.511`, error happens in both.

My idea opening this issue is that maybe someone can already point something out, and I could already share the "thought" about that it maybe doesn't have to `throw` in the first place.

Also I kinda see that I might've made a mistake, as I couldn't find anything regarding this issue on Google, Discord or any of the GitHub repos 🥲

In the next days I try to set up a repro repo if necessary.

## Expected behavior

No error on HMR.

## System information

- OS: macOS
- Version of supabase-js: 1.35.7
- Version of Node.js: 16.14.2

**Comment by Nisthar** [comment]
Yeah i got this error too. It happens when vite optimizes the dependencies.

**Comment by CanRau** [comment]
Yeah you're probably right, I remember seeing the deps optimization info when that happens.

Curious what the reasoning for `throw`ing an error there is, as I'd normally expect a singleton to just return the existing instance

**Comment by kakashy** [comment]
Hey @CanRau , did you find a work-around for this?

**Comment by CanRau** [comment]
Nope, so far I "just" restart dev server and an looking to update to v2 but so far can't get it working as the just released versions seem out of sync with docs 😬

**Comment by kakashy** [comment]
Thanks @CanRau 
I share you thoughts that `config` should be returned if it exists but I tried doing this but more errors occurred.

I'm using David's implementation of authentication, which involves passing the client to the `auth()` function and calling the client from inside that function. Please see: https://github.com/david-plugge/sveltekit-supabase/tree/main/packages/sveltekit-supabase-auth

Thanks though.

**Comment by Nisthar** [comment]
> Thanks @CanRau I share you thoughts that `config` should be returned if it exists but I tried doing this but more errors occurred.
> 
> I'm using David's implementation of authentication, which involves passing the client to the `auth()` function and calling the client from inside that function. Please see: https://github.com/david-plugge/sveltekit-supabase/tree/main/packages/sveltekit-supabase-auth
> 
> Thanks though.

are you using [this fork](https://github.com/david-plugge/sveltekit-supabase/tree/main/packages/sveltekit-supabase-auth) ?did you get it working?

**Comment by david-plugge** [comment]
I agree with you about removing the error. But now that supabase v2 + auth helpers are released you may want to take a lot at that.

**Comment by CanRau** [comment]
yeah just upgraded successfully yesterday and everything seems to be working fine also just looked into the source and the `throw Error` seems to be gone 😍

Closing than as I guess the idea is that people update, not sure anyone's going to "backport" this into v1
