### ISSUE TITLE
Update sveltekit auth helpers to v2

### ISSUE THREAD

**Issue by Nisthar** [supabase/auth-helpers#289]
Please update the sveltekit auth helpers to v2.

**Comment by MentalGear** [comment]
The have just done it, but is it working for you @Nisthar ? I get an `Cannot destructure property 'supabaseUrl' of 'getConfig(...)' as it is undefined.` error.

**Comment by f-gueguen** [comment]
@MentalGear I think in `lib/db.js` you are importing the `supabase-js` createClient function instead of from `auth-helpers-sveltekit`

**Comment by MentalGear** [comment]
Indeed, thanks again @f-gueguen !

**Comment by CanRau** [comment]
Yaaasss nice, also successfully upgraded to v2 today following the readme of SvelteKit auth-helpers

**Comment by braden-w** [comment]
Have been unable to pass `Database` via `createClient<Database>(supabaseUrl, supabaseAnonKey)` like in v2, @CanRau  could you elaborate on how you were able to upgrade to v2?

So far, in order to use types on selects and updates, I've done the following in my `lib/db.ts` : 

```ts
// From https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/README.md 
import { createClient } from '@supabase/auth-helpers-sveltekit';
import { createClient as createFetchClient } from '@supabase/supabase-js';
import { env } from '$env/dynamic/public'
import type { Database } from '$lib/types/DatabaseDefinitions';

const supabaseUrl = env.PUBLIC_SUPABASE_URL;
const supabaseAnonKey = env.PUBLIC_SUPABASE_ANON_KEY;

export const supabaseClient = createClient(supabaseUrl, supabaseAnonKey);
export const supabaseFetchClient = createFetchClient<Database>(supabaseUrl, supabaseAnonKey);
```

and use `supabaseClient` for most operations, and `supabaseFetchClient` for CRUD operations when I want types.

**Comment by CanRau** [comment]
I'm still not using types that's how 🙈
First time I tried to run locally with the CLI I ran into some issues and didn't try again so far 😅
