### ISSUE TITLE
Pass `request` to `withMiddlewareAuth`'s `isPermitted` function

### ISSUE THREAD

**Issue by 413n** [supabase/auth-helpers#308]
# Feature request

## Is your feature request related to a problem? Please describe.

I like the functionality of the `withMiddlewareAuth` helper, but in my use case I'm a bit limited. I would like to have multiple paths where I check the user authentication and for each I would like to check for a different user role.

## Describe the solution you'd like

Referring to the following code, I would suggest to pass the `request` in the `isPermitted` function, so that we could check also for the url and be more specific.

https://github.com/supabase/auth-helpers/blob/main/examples/nextjs/middleware.ts#L1-L15

**Comment by NanoCode012** [comment]
Yes! I have the same use case (check if user has role to access certain page). I used to do it via `getServerSideProp`, but it is inefficient and doesn't allow page caching.

With the new `12.2` nextjs middleware, we could use a single middleware to check, so it's faster.

The lines to change should be:
https://github.com/supabase/auth-helpers/blob/d65b8b4ac6bc6d5248328197dd458abd4e7d804d/packages/nextjs/src/middleware/withMiddlewareAuth.ts#L35
and 
https://github.com/supabase/auth-helpers/blob/d65b8b4ac6bc6d5248328197dd458abd4e7d804d/packages/nextjs/src/middleware/withMiddlewareAuth.ts#L140

I may open a PR targeting the `0.2.9` tag as I'm still using Supabase `v1`.

**Comment by NanoCode012** [comment]
Sorry for my late follow up, I have written the code for `0.2.9`, but it should also be applicable to latest `main` branch also with some modification.

https://github.com/NanoCode012/supabase-auth-helpers/commit/93405a21a36f208f1589248dff7c74725d008a8c

Changes from `0.2.9`: https://github.com/supabase/auth-helpers/compare/%40supabase/auth-helpers-nextjs%400.2.9...NanoCode012:supabase-auth-helpers:feat/add-middleware-req

If someone could point me to how I could also have this update for Supabase v1, that'd be great. If not, please tell me so I could adapt the code for latest main branch.

**Comment by NanoCode012** [comment]
I just saw a new PR https://github.com/supabase/auth-helpers/pull/364 which would solve this issue. Looking forward to it!
