### ISSUE TITLE
sveltekit: Protected Routes

### ISSUE THREAD

**Issue by MentalGear** [supabase/auth-helpers#312]
# Improve documentation
The code snippet in the guide describes how to protect routes.

## Link 
https://github.com/supabase/auth-helpers/blame/main/packages/sveltekit/README.md#L240

## Describe the problem
However, wouldn't this
- just protect the GET method
- any subroutes are still accessible.

## Describe the improvement
It would be great if a way is displayed that protects any HTTP method access, as well as blocking any sub path access.

**Comment by david-plugge** [comment]
There is no a clean way to solve auth for multiple routes currently, but that´s on sveltekit´s side since its missing some sort of middleware.
You can however create a handle hook to secure multiple pages in one place.

Here we check for POST requests that go to a url starting with `/protected-route`
```ts
// src/hooks.server.ts
export const handle = async ({ event, resolve }) => {
	if (event.url.pathname.startsWith('/protected-route' && event.request.method === 'POST') {
		const { session, supabaseClient } = await getSupabase(event);
		if (!session) {
			throw error(401);
		}
		// do your middleware stuff here
		// for example store the session in locals
		event.locals.session = session;
	}

	return resolve(event);
}
```

I think we can add this to the docs

**Comment by MentalGear** [comment]
Excellent, thanks David!

Just curious why add `&& event.request.method === 'POST')`, without this, it would protect from any HTTP method, right?

Yes, please add this to the docs - it's a common scenario for many use cases.

**Comment by david-plugge** [comment]
> Just curious: Without `&& event.request.method === 'POST')`, it would protect from any HTTP method, right?

Yeah, i just added it as an example.

> Also, this could as well work on hooks.client.ts ?

The handle hook only exists on the server. If you want client side authentication you need to use the layout and page load functions to restrict access to pages.
