### ISSUE TITLE
docs: outdated sveltekit setup guide in main supabase guide

### ISSUE THREAD

**Issue by MentalGear** [supabase/auth-helpers#317]
# Improve documentation

## Link 
https://supabase.com/docs/guides/auth/auth-helpers/sveltekit

## Describe the problem
This is confusing new developers.

The official guide still has the outdated setup guide for auth-helpers sveltekit, which includes several unavailable functions and steps which are not necessary anymore, for example:

https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#set-up-hooks
https://github.com/supabase/auth-helpers/tree/main/packages/sveltekit#supabaseclient-setup

## Describe the improvement
It should be synched with:
https://github.com/supabase/auth-helpers/tree/main/packages/sveltekit

**Comment by silentworks** [comment]
No longer the case.
