### ISSUE TITLE
Logging in with signInWithOTP() and using withPageAuth in Next SSR reroutes me to the unauthed route

### ISSUE THREAD

**Issue by devlukedreamstage** [supabase/auth-helpers#322]
# Bug report

## Describe the bug

When I log in with signInWithOTP(), I still get rerouted back to the unauthenticated route despite being authenticated from opening the magic login link. I can access pages just fine if I change the url my self.

It seems like the the withPageAuth is checking before auth data is cached

### Heres my code for ssr authentication

```
export const getServerSideProps: GetServerSideProps = withPageAuth({
  redirectTo: "/login",
  async getServerSideProps(ctx, supabase) {
    const {
      data: { user },
    } = await supabase.auth.getUser();
    const res = await supabase.rpc("user_has_any_role", {
      user_id_: user?.id,
    });

    return {
      redirect: !!res.data ? undefined : { destination: "/unauthorized" },
      props: {},
    };
  },
});
```

### Heres the login code

```
const handleLogin = async (email) => {
    try {
      setLoading(true);
      const { error } = await supabase.auth.signInWithOtp({
        email,
        options: { emailRedirectTo: "/" },
      });
      if (error) throw error;
      alert("Check your email for the login link!");
    } catch (error) {
      alert(error.error_description || error.message);
    } finally {
      setLoading(false);
    }
  };
```

## Expected behavior

Should be authenticated and let me into the emailRedirectTo page

## System information

Windows
Chrome
 "@supabase/supabase-js": "2.0.0-rc.10"

**Comment by tiniscule** [comment]
This is impacting the newer syntax as well, where the helpers are removed and we're meant to build it up ourselves.  I'm wondering if we need to look for a `token` param and let it pass through, but that seems not great. 

Here's an example I've got, it's mostly just copied out of the Next README.

```typescript
import { createMiddlewareSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { NextResponse } from "next/server";
import type { NextRequest } from "next/server";

export async function middleware(req: NextRequest) {
  // We need to create a response and hand it to the supabase client to be able to modify the response headers.
  const res = NextResponse.next();
  // Create authenticated Supabase Client.
  const supabase = createMiddlewareSupabaseClient({ req, res });
  // Check if we have a session
  const {
    data: { session },
  } = await supabase.auth.getSession();

  // Check auth condition
  if (session) {
    // Authentication successful, forward request to protected route.
    return res;
  }

  // Auth condition not met, redirect to home page.
  const redirectUrl = req.nextUrl.clone();
  redirectUrl.pathname = "/login";
  redirectUrl.searchParams.set(`redirectedFrom`, req.url);
  return NextResponse.redirect(redirectUrl);
}

export const config = {
  matcher: ["/authenticated/:path*"],
};
```

**Comment by silentworks** [comment]
This is due to the server not getting the authenticated cookie before the page loads. The token information is sent over from the client side to the server which requires that you have to land the user on a non-protected page first before redirecting them to the projected page. This will no longer be the case when PKCE lands.
