### ISSUE TITLE
Typescript Support for auth-helpers-sveltekit

### ISSUE THREAD

**Issue by Tihomir971** [supabase/auth-helpers#329]
# Feature request

createClient Database Types
https://supabase.com/docs/reference/javascript/typescript-support

**Comment by david-plugge** [comment]
Have you taken a look at the typings section in the docs?
https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/README.md#typings

**Comment by david-plugge** [comment]
The helpers use the same library (@supabase/supabase-js) under the hood, therefore the types are the same.
You just need to reference your genereted types inside `src/app.d.ts`

For example:
```ts
// src/schema.ts
interface Database {
  public: {
    Tables: {
      movies: {
        Row: {} // The data expected to be returned from a "select" statement.
        Insert: {} // The data expected passed to an "insert" statement.
        Update: {} // The data expected passed to an "update" statement.
      }
    }
  }
}

// src/app.d.ts
declare namespace App {
  interface Supabase {
    Database: import('./schema').Database;
    SchemaName: 'public';
  }
}
```

**Comment by Tihomir971** [comment]
With this I don't get Types. All variables are of type Any. I don't have same problems with @supabase/supabase-js

**Comment by Tihomir971** [comment]
> The helpers use the same library (@supabase/supabase-js) under the hood, therefore the types are the same. You just need to reference your genereted types inside `src/app.d.ts`
> 
> For example:
> 
> ```ts
> // src/schema.ts
> interface Database {
>   public: {
>     Tables: {
>       movies: {
>         Row: {} // The data expected to be returned from a "select" statement.
>         Insert: {} // The data expected passed to an "insert" statement.
>         Update: {} // The data expected passed to an "update" statement.
>       }
>     }
>   }
> }
> 
> // src/app.d.ts
> declare namespace App {
>   interface Supabase {
>     Database: import('./schema').Database;
>     SchemaName: 'public';
>   }
> }
> ```

This is from supabase\examples\user-management\sveltekit-user-management
![Snimak ekrana 2022-10-26 182059](https://user-images.githubusercontent.com/72653027/198080762-3b39ecb3-0ae0-48ca-8d5d-0e640d2d9c27.jpg)

**Comment by david-plugge** [comment]
What cli version are you using? We ran into the same problem because the types were generated with an older version.

**Comment by Tihomir971** [comment]
> What cli version are you using? We ran into the same problem because the types were generated with an older version.

Not using CLI. I'm manually written  schema.ts. Just one table for test. I have problem with supabase example as I mention.
https://github.com/supabase/supabase/tree/master/examples/user-management/sveltekit-user-management

**Comment by david-plugge** [comment]
I think that schema is outdated, the newer version includes `Views`.

See this [comment](https://github.com/supabase/supabase-js/commit/eff88f95ed18ef67ab5f8f333a3bbda1dd90dee2#commitcomment-84228347).

Try using the latest cli version to generate your types.

**Comment by david-plugge** [comment]
@isaacfink https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/README.md#typings

**Comment by Tihomir971** [comment]
> <Database>

You can't use `<Database>` with createClient. It's for @supabase/supabase-js, not @supabase/auth-helpers-sveltekit. In my case it still not working.

**Comment by silentworks** [comment]
Both myself and @david-plugge have tested the types stuff and it works as expected. Please state what you have done with code examples and how you are expecting it to work and what is not working.

**Comment by david-plugge** [comment]
The sveltekit auth helpers export a custom `createClient` method that doesn´t make use of Generics.
Instead you can define your Database types in your `src/app.d.ts` file which makes the types globally available.
This is documented [here](https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/README.md#typings) 
(replace `./DatabaseDefinitions` with the path to your Database types, maybe we should add this step to the docs)

**Comment by isaacfink** [comment]
@david-plugge I see that I already had my types in `app.d.ts` but now it worked, thanks

**Comment by Tihomir971** [comment]
> Both myself and @david-plugge have tested the types stuff and it works as expected. Please state what you have done with code examples and how you are expecting it to work and what is not working.

I find solution :( "pnpm rebuild"

**Comment by Tihomir971** [comment]
> The sveltekit auth helpers export a custom `createClient` method that doesn´t make use of Generics. Instead you can set up your Database types in your `src/app.d.ts` file which makes the types globally available. This is documented [here](https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/README.md#typings) (replace `./DatabaseDefinitions` with the path to your Database types, maybe we should add this step to the docs)

`const { data, error } = await supabaseClient
			.from('eav_attribute')
			.insert({ code, name })
			.select();`
data is of type any[]. insert is typed but select isn't?

**Comment by david-plugge** [comment]
@Tihomir971 do you have a link to a reproduction?

**Comment by Tihomir971** [comment]
> 
Github code>
[src/routes/(app)/catalog/attribute/create/+page.server.ts](https://github.com/Tihomir971/Assistant/blob/9dc0e1f86b00ccfc08b75dd1f4b828e6dee8fcd8/src/routes/(app)/catalog/attribute/create/+page.server.ts)

**Comment by Tihomir971** [comment]
> @Tihomir971 do you have a link to a reproduction?

Github code>
[src/routes/(app)/catalog/attribute/create/+page.server.ts](https://github.com/Tihomir971/Assistant/blob/9dc0e1f86b00ccfc08b75dd1f4b828e6dee8fcd8/src/routes/(app)/catalog/attribute/create/+page.server.ts)

**Comment by david-plugge** [comment]
You are linking to a non existing file here https://github.com/Tihomir971/Assistant/blob/9dc0e1f86b00ccfc08b75dd1f4b828e6dee8fcd8/src/app.d.ts#L6
You need to go back a directory level

```diff
declare namespace App {
	interface Supabase {
-		Database: import('./types/supabase').Database;
+		Database: import('../types/supabase').Database;
		SchemaName: 'public';
	}
}
```

**Comment by Tihomir971** [comment]
> You are linking to a non existing file here https://github.com/Tihomir971/Assistant/blob/9dc0e1f86b00ccfc08b75dd1f4b828e6dee8fcd8/src/app.d.ts#L6 You need to go up a directory level
> 
> ```diff
> declare namespace App {
> 	interface Supabase {
> -		Database: import('./types/supabase').Database;
> +		Database: import('../types/supabase').Database;
> 		SchemaName: 'public';
> 	}
> }
> ```

Hawkeye :)
