### ISSUE TITLE
Vercel Function timing out (504) when using withPageAuth.

### ISSUE THREAD

**Issue by adolfoportilla** [supabase/auth-helpers#332]
# Bug report

## Describe the bug

When using withPageAuth, Vercel throws 504 (Serverless Function timeout error) after the user has signed in (using google OAuth) and is redirected to my page. The moment I remove withPageAuth, the page works as expected.

It is important to note as well that this works when I run the code locally.

This is the page that times out /admin.
```
// admin.js
import { withPageAuth } from "@supabase/auth-helpers-nextjs";
export default function Admin() {
  return <div>Hello world</div>;
}

// NOTE: If I remove this (which I don't want since I want the page to be protected by auth), the page works fine.
export const getServerSideProps = withPageAuth({
  redirectTo: "/admin",
});
```
This is the signin page.
```
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import {
  useUser,
  useSupabaseClient,
} from "@supabase/auth-helpers-react";

const SignIn = () => {
  const router = useRouter();
  const user = useUser();
  const supabaseClient = useSupabaseClient();

  const handleOAuthSignIn = async (provider) => {
    setLoading(true);
    const { error } = await supabaseClient.auth.signInWithOAuth({
      provider,
      options: { redirectTo: getURL("/admin") },
    });
    if (error) {
      setMessage({ type: "error", content: error.message });
    }
    setLoading(false);
  };
  useEffect(() => {
    if (user) {
      router.replace("/admin");
    }
  }, [user]);


  if (!user) {
  // NOTE: I am using here a button that calls `handleOAuthSignIn` with `google`, as I am using google provider.
  }

  return {...loading...}
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `/signin`
2. Click on the google button
3. Enter google credentials
4. Wait for the signing to happen (redirect happens)
5. See vercel timeout error

## Expected behavior

The admin page should render after I sign in with google, I should not see a timeout.

## Screenshots

![image](https://user-images.githubusercontent.com/11667804/197574000-e2a46cc4-2b50-47e7-9771-0a5b47c9901d.png)

## System information

- Using Vercel (this is happening when I deploy to Vercel, not locally)
- Browser (if applies) [chrome]
- Version of supabase-js: [2.0.2]
- Version of Node.js: [16]
- Using google to authenticate

## Additional context

I am using Vercel + NextJS + Supabase + Google to authenticate.

I am cross-posting here since I believe this is the place instead of here https://github.com/supabase/supabase/issues/9742

**Comment by adolfoportilla** [comment]
I was able to find more info.

Vercel is converting my page to be a Serverless function when I use `withPageAuth`. I am not sure if this is expected behavior or not.

For anyone interested, I was able to create a workaround by using a middleware approach (docs: https://supabase.com/docs/guides/auth/auth-helpers/nextjs#protecting-routes-with-nextjs-middleware) instead.

**Comment by thorwebdev** [comment]
I think https://github.com/supabase/auth-helpers/pull/364 should resolve this.
