### ISSUE TITLE
Unable to SignOut after logging in with Spotify

### ISSUE THREAD

**Issue by oliver-tunebat** [supabase/auth-helpers#346]
# Bug report

## Describe the bug

After logging in with Spotify, it seems impossible to logout. Even manually deleting the cookie doesn't work.

## To Reproduce

1. Log in with Spotify
```
async function signInWithSpotify() {
    const { data, error } = await supabaseClient.auth.signInWithOAuth({
        provider: "spotify",
        options: {
            scopes: "user-top-read user-read-recently-played",
        },
    });
}
```
2. Sign out
```
const { error } = await supabaseClient.auth.signOut();
```
3. Refresh Page. Observe that getUser() still returns an authenticated user.

## Expected behavior

User should be logged out.

## System information

- OS: Windows
- Browser chrome
- "@supabase/auth-helpers-nextjs": "0.4.1",
- "@supabase/auth-helpers-react": "0.3.0",
- "@supabase/supabase-js": "2.0.2",
- "next": "12.3.1",
- Version of Node.js: 16.14.0

**Comment by olegkorol** [comment]
How do you import / initialise `supabaseClient`?

A:
```javascript
import { useSupabaseClient } from '@supabase/auth-helpers-react'

// inside the Component
const supabaseClient = useSupabaseClient()
```

B:
```javascript
import { createBrowserSupabaseClient } from '@supabase/auth-helpers-nextjs'

// inside the Component
const [supabaseClient] = useState(() => createBrowserSupabaseClient())
```

C: ?

**Comment by oliver-tunebat** [comment]
```
import { createBrowserSupabaseClient } from "@supabase/auth-helpers-nextjs";

export const supabaseClient = createBrowserSupabaseClient();
```

And then import it wherever it's being used.

**Comment by olegkorol** [comment]
Could give `A` a try?

**Comment by oliver-tunebat** [comment]
Looks like it was a different issue. The access token was in the url, so when logging out and then reloading the page with the access token url, it caused another login. So the solution is to clear the token from the url after logging in.

**Comment by thorwebdev** [comment]
> So the solution is to clear the token from the url after logging in.

This should happen automatically when the supabase browser client is initialised. I recommend doing that in the app root: https://github.com/supabase/auth-helpers/blob/main/examples/nextjs/pages/_app.tsx#L17-L19
