### ISSUE TITLE
Next.js: Migration guide to 0.4.X

### ISSUE THREAD

**Issue by olegkorol** [supabase/auth-helpers#348]
# Improve documentation

## Link 

[Next.js MIGRATION_GUIDE.md](https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/MIGRATION_GUIDE.md)

## Describe the problem

There are some breaking changes that are not described in the migration guide.

## Describe the improvement

While it is hard to mention all the breaking changes in the docs, it would probably be helpful to mention at least some important/common ones. It might take some time otherwise to figure everything out, IMO.

- `supabaseClient.auth.signIn()`  => `supabaseClient.auth.signInWithPassword()` (input params are different).
- When using `getServerSideProps` you don't need to import the `serverSideClient` anymore (now `createServerSupabaseClient`). It is included already:
```javascript
export const getServerSideProps = withPageAuth({
  async getServerSideProps(ctx, supabaseServerClient) {
    // do something
  }
})
```
- To get user data in SSR, you won't import and use `getUser` anymore. Instead:
```javascript
// inside `getServerSideProps`:
const { data: { user } } = await supabaseServerClient.auth.getUser()

// note that `user` is inside `data`. Not as it used to be with the `getUser` helper, i.e. the "old way":
const { user } = getUser(ctx)
```
- Subscriptions seem to have changed as well:
```javascript
// OLD subscription:
const subscription = supabase
  .from('table')
  .on('*', async (payload) => {
    // do something
  })
  .subscribe()

// OLD unsubscribe:
supabase.removeSubscription(subscription)
// or
supabase.removeAllSubscriptions()

// NEW subscription:
const subscription = supabase
    .channel('public:table')
    .on(
    'postgres_changes',
    { event: '*', schema: 'public', table: 'table' },
    async (payload) => {
      // do something
    } )
    .subscribe()

// NEW unsubscribe:
supabase.removeChannel(subscription)
// or
supabase.removeAllChannels()
```
- Supabase client within authenticated APIs:
```javascript
// NEW
import { withApiAuth } from '@supabase/auth-helpers-nextjs'

export default withApi(async (req, res, supabaseServerClient) => {
  // [...]
  const {
        data: { user },
      } = await supabaseServerClient.auth.getUser()
  // [...]
})

// OLD
import { withApiAuth, getUser } from '@supabase/auth-helpers-nextjs'

export default withApi(async (req, res) => {
  // [...]
  const { user } = await getUser({req, res})
  // [...]
})
```
- ...to name a few that I've encountered while performing the migration.
 
## Additional context

Do you agree? Maybe I am missing something and those changes are super intuitive for everyone :)

**Comment by thorwebdev** [comment]
Thanks for pointing these out! This should be all covered now via 

1. https://supabase.com/docs/reference/javascript/upgrade-guide
2. https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/MIGRATION_GUIDE.md#migrating-to-05x

**Comment by jordiup** [comment]
If anyone wants to add back in `withApiAuth` I've created a custom middle ware func. Will add below 🚀 

```
import { createServerSupabaseClient } from '@supabase/auth-helpers-nextjs';
import { NextApiHandler } from 'next';

/** middleware fn for withApiAuth */
export const withApiAuth =
	(handler: NextApiHandler) =>
	async ({ req, res }) => {
		// Extract the authorization header from the request headers
		const authorization = req.headers.authorization;

		if (!authorization) {
			// No authorization header was provided, so return a 401 Unauthorized response
			res.statusCode = 401;
			res.end('Unauthorized');
			return;
		}

		try {
			// Create authenticated Supabase Client
			const supabase = createServerSupabaseClient({ req, res });

			// Check if we have a session
			const {
				data: { session },
			} = await supabase.auth.getSession();

			if (!session) {
				// No session, so return a 401 Unauthorized response
				res.statusCode = 401;
				res.end('Unauthorized');
				return;
			}

			// The request is authorized, so execute the handler function
			return handler({ req, res });
		} catch (error) {
			console.log({
				error,
				message: 'withApiAuth error',
				reqHeaders: req.headers,
			});
			res.statusCode = 500;
			res.end('Internal Server Error');
			return;
		}
	};
```

**Comment by mryechkin** [comment]
> Thanks for pointing these out! This should be all covered now via
> 
> 1. https://supabase.com/docs/reference/javascript/upgrade-guide

Hi @thorwebdev - sorry to bump an old issue, but this link seems to no longer be available. Any reason that page was removed? I can't find the upgrade guide anywhere in the updated docs
