### ISSUE TITLE
Missing auth-helpers example for js-v2!

### ISSUE THREAD

**Issue by Afsarsoft** [supabase/auth-helpers#357]
Regarding supabase-js-v2, you don't have auth-helpers example for Vue. Can you create one for Vue?  It would be great if you use the latest “npm init vue@latest” .

Thank You,
Surush

**Comment by thorwebdev** [comment]
I'm afraid vue isn't covered here. We only have these atm

- https://github.com/supabase/supabase/tree/master/examples/user-management/vue3-user-management
- https://github.com/supabase/supabase/tree/master/examples/user-management/nuxtjs-user-management
- https://github.com/supabase/supabase/tree/master/examples/user-management/nuxt3-user-management
