### ISSUE TITLE
Protecting multiple routes with different authGuard.isPermitteds in nextjs middleware

### ISSUE THREAD

**Issue by jopfre** [supabase/auth-helpers#361]
# Improve documentation

## Link 

[Protecting routes with nextjs middleware](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#protecting-routes-with-nextjs-middleware)

## Describe the problem

The documentation shows how to protect multiple routes with one authGuard.isPermitted(). It is unclear how to use a different isPermitted() for different routes.

Perhaps the method is to use the request object and then check for the path within the single isPermitted(). However it seems the request object is not available within isPermitted or the available supabase object.

## Describe the improvement

Provide an example to show the intended method to use different checks with different paths. If this involves using the request object. Show how to access it from within isPermitted()

## Additional context

My use case:

I have multiple paths:

/admin
/consultant
/manager

These correspond to different user roles.

I want to allow access to the path which corresponds to the user's role but restrict access to all other paths.

The paths with have multiple sub paths.

**Comment by thorwebdev** [comment]
Via https://github.com/supabase/auth-helpers/pull/364 this will become a lot more flexible.
