### ISSUE TITLE
signOut does not clear session and useUser does not get latest until refresh once

### ISSUE THREAD

**Issue by NanoCode012** [supabase/auth-helpers#370]
# Bug report

## Describe the bug

Hello, I am currently upgrading from v1 to v2 and noticed some weird behaviors with auth-helpers and Nextjs after the exciting `0.5.1` update!

I have followed the migration guide from both supabase and auth-helpers. 

There are two weird behaviors:
- Once I login with email+password, `useUser` still returns null on my `/home` page **until I refresh** (waiting does nothing). I have done a session check on a `middleware.ts` before `home` loads, so I am sure that the user is valid/logged in.
```ts
// login.ts
const {
      data: { user },
      error,
    } = await supabaseClient.auth.signInWithPassword({
      email,
      password,
    });

router.push('/home');

// home.ts
const user = useUser(); // null
```
- Once I sign out, `/home` -> `/` (server-side checks that no session) ->  `/login`, the `useUser` on the `/login` page still detects `User` active and `SessionContext` has non-null  `Session` object **until I refresh** (waiting does nothing).
```ts
if (user) { const { error } = await supabaseClient.auth.signOut(); router.push('/'); }
```

## Expected behavior

`useUser` returns `null` THEN `User` when redirected to `/home`. 
`signOut` to clear session and `useUser` to return `null` instead of `User`.

## System information

- OS: Windows
- Browser: Firefox
- Version of Node.js: LTS 16

Version:
```json
"@supabase/auth-helpers-nextjs": "0.5.1",
"@supabase/auth-helpers-react": "0.3.1",
"@supabase/supabase-js": "2.0.5",
"next": "12.3.1",
"react": "^18.2.0",
```
```tsx
// Also tried with default Component prop with similar result
type ExtendedAppProps = AppProps<{ initialSession: Session }> & {
  Component: NextPage<{ initialSession: Session }>;
  emotionCache: EmotionCache;
};

const App = (props: ExtendedAppProps) => {
<SessionContextProvider
          supabaseClient={supabaseClient}
          initialSession={pageProps.initialSession}
        >
<Component {...pageProps} />
// ...
```

## Additional context

I have seen other threads in Discord, but they were v1. 

For github, this is half of my problem (no one answered) https://github.com/supabase/supabase/discussions/9558

There is another thread https://github.com/supabase/supabase/discussions/9639 which gary has answered but exhibits similar problem.

Potential alternatives:
- `getSession` instead as that will always get latest
    - Con: slower and may re-run each render

Current workaround: stop using `useUser` or `SessionContext` in checks or critical parts. Move all checks server-side in middleware.

**Comment by vincentjflorio** [comment]
I had the same experience. In my case since a logout kicks people to the homepage, I ran a useEffect on the homepage to try to scrub all the cookies out.

It was *extremely* confusing trying to nail down a flow because I have conditions on sign-in/sign-up that depend on whether or not the user is logged in or not and try to go between accounts and it was still holding onto the original user.

**Comment by NanoCode012** [comment]
>  I ran a useEffect on the homepage to try to scrub all the cookies out.

@vincentjflorio , in my case, I can see the cookies being placed (on login) and removed (on signout), BUT the `user`/`session` on the browser `useSessionContext` and `useUser` still detects an inactive/active user and session respectively.

A shallow dive into the code shows it loading from the `useContext(SessionContext);`, so I'd guess that this Context is NOT being updated onLogin/onSignout and only on refresh. https://github.com/supabase/auth-helpers/blob/6d72246ee3453518178f94222b710565cfa1e0df/packages/react/src/components/SessionContext.tsx#L169-L176

**Comment by NanoCode012** [comment]
I tried listening for events inside `_app.tsx` and noticed `SIGNED_OUT` is not emitted and `found session` is sometimes returned.

```tsx
useEffect(() => {
    const {
      data: { subscription },
    } = supabaseClient.auth.onAuthStateChange((event, session) => {
      if (session && (event === "SIGNED_IN" || event === "TOKEN_REFRESHED")) {
        console.log("found session");
      }

      if (event === "SIGNED_OUT") {
        console.log("signing out");
      }
    });

    return () => {
      subscription.unsubscribe();
    };
  }, []);
```

**Comment by AvidDabbler** [comment]
I am having the same issue. Signout seems to revoke the token, but user and session persist.

User is how I check to see if the user is logged in and redirect to my app if user is present.

I am also using withPageAuth which will sometimes create a loop between signIn and app.

Im curious as to what provider everyone is using. I have just been using magiclink and have had some problems with it. wondering if switching to user password would help>

**Comment by NanoCode012** [comment]
> Im curious as to what provider everyone is using. I have just been using magiclink and have had some problems with it. wondering if switching to user password would help>

@AvidDabbler I'm using user/password, and beside from SessionContext not persist/clear properly, everything else works.

Currently, I have removed any primary use of `useUser`. I have changed to redirecting via serverside instead (middleware for Nextjs) as the `ServerSide` and `Middleware` client are more reliable.

**Comment by AvidDabbler** [comment]
Ok I took the morning to see what I could do for a workaround for this. I am currently using this as my `_app.tsx` for my next app. Basically I have taken the sessionToken from localStorage and moved it to my redux store and then listen for that on the frontend. The app still mostly relies on user and session from supabase hooks, but it prevents the loop for the moment of going from signin to my app. The token is still invalidated so even if they get to the app they won't see anything, but its good enough for now.

What I initially tried to do is setup `supabaseClient` and/or `initialSession` on `<SessionContextProvider>` to be null which would make sense since most examples of `supabaseClient` are declared in a `useState`. Would love to see `setSupabaseClient` as the second arguement to manually update the context. or really just a clear context like others have requested. 

Happy to provide more context if needed.


```
// _app.tsx

import type { AppProps } from 'next/app';
import { Provider, useDispatch } from 'react-redux';
import { SessionContextProvider } from '@supabase/auth-helpers-react';
import { GoogleAnalytics } from 'nextjs-google-analytics';

import { Fragment, useEffect, useState } from 'react';
import { createBrowserSupabaseClient, Session } from '@supabase/auth-helpers-nextjs';

import { Database } from '../types/supabase';
import { store } from '../store';
import { setSession } from '../store/appSlice';
import '../styles/globals.css';
import '../styles/App.scss';
import '../styles/Landing.scss';
import '../styles/animate.css';
import 'draft-js/dist/Draft.css';

function MyApp({
  Component,
  pageProps,
}: AppProps<{
  initialSession: Session;
}>) {
  return (
    <Provider store={store}>
      <Providers
        pageProps={pageProps}
        initialSession={pageProps.initialSession}
        Component={Component}
      />
    </Provider>
  );
}

const Providers = ({
  initialSession,
  Component,
  pageProps,
}: {
  pageProps: any;
  initialSession: Session | null;
  Component: AppProps['Component'];
}) => {
  const dispatch = useDispatch();
  const [supabaseClient] = useState(() => createBrowserSupabaseClient<Database>());

  useEffect(() => {
    const token = localStorage.getItem(process.env.NEXT_PUBLIC_SUPABASE_LOCAL_KEY ?? '');
    const localsession: Session | null = token ? JSON.parse(token) : null;
    dispatch(setSession(localsession ?? null));
  }, [pageProps, localStorage]); // eslint-disable-line

    return (
      <SessionContextProvider supabaseClient={supabaseClient} initialSession={initialSession}>
        <Fragment>
          <GoogleAnalytics strategy="lazyOnload" />
          <Component {...pageProps} />
        </Fragment>
      </SessionContextProvider>
    );
};

export default MyApp;

// index.tsx
import React, { Fragment, useEffect } from 'react';
import { Toolcontainer } from '../../components/ui/Toolcontainer';
import { UserControls } from '../../components/ui';
import SocialFeed from '../../components/Feed/SocialFeed';
import { useUser } from '@supabase/auth-helpers-react';
import { getUserData } from '../../lib/auth';
import { useSelector } from 'react-redux';
import { RootState } from '../../store';
import Head from 'next/head';
import SignIn from '../../components/sign-in';

const App = () => {
  const user = useUser();

  const { currentAgency } = useSelector((state: RootState) => state.agency);
  const session = useSelector((state: RootState) => state.app.session);
  useEffect(() => {
    if (currentAgency.agencyId === '') getUserData(user);
  }, [currentAgency, session]); // eslint-disable-line

  return (
    <Fragment>
      <Head>
        <title>TransitChat</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      </Head>
      {session ? (
        <Toolcontainer>
          {user?.app_metadata.agency ? (
            <div className="App flex flex-row">
              <UserControls />
              {user.id !== '' && <SocialFeed />}
            </div>
          ) : (
            <h2></h2>
          )}
        </Toolcontainer>
      ) : (
        <SignIn />
      )}
    </Fragment>
  );
};

export default App;
```

Keep in mind that `process.env.NEXT_PUBLIC_SUPABASE_LOCAL_KEY` will need to be different for local vs production

**Comment by thorwebdev** [comment]
Do you experience this when running locally or when deployed? Or both?

**Comment by NanoCode012** [comment]
I only got to test mine locally.

**Comment by vincentjflorio** [comment]
For me it was both. My redirect  and site URL addresses in 
https://app.supabase.com/project/_____________________________/auth/url-configuration appear to be fine, and work for every other  purpose, if it's relevant.

**Comment by j4w8n** [comment]
@NanoCode012 @AvidDabbler @vincentjflorio @thorwebdev 

Regarding the signOut, this seems to be a gotrue-js issue. I was able to resolve with a local code change, but wasn't confident enough to create a PR for it. Hopefully a maintainer can verify or not.

https://github.com/supabase/gotrue-js/issues/524

**Comment by mrmikardo** [comment]
I have also experienced this issue, both locally and in deployments.

**Comment by mrmikardo** [comment]
@vincentjflorio 

>  In my case since a logout kicks people to the homepage, I ran a useEffect on the homepage to try to scrub all the cookies out.

Did this hack fix the issue for you? Keen to find a way that I can continue to use the `0.5.1` library rather than downgrade.

**Comment by NanoCode012** [comment]
> Keen to find a way that I can continue to use the 0.5.1 library rather than downgrade.

@mrmikardo , I changed all my redirection code to using Nextjs middleware instead of client-side. It works great for me.

**Comment by silentworks** [comment]
Can someone provide a minimal reproducible example repo of this issue? as I'm not able to replicate it on this side.

**Comment by vincentjflorio** [comment]
@mrmikardo It seems to, yeah. If nothing else it didn't noticeably hurt anything, for me.

**Comment by zakrza59** [comment]
Also have problem with this. I logout the user on one tab, on other tab I can see user logged in navbar where I use useUser hook.  Any other ideas for this or should I feed the navbar from server side code?

**Comment by j4w8n** [comment]
@NanoCode012 is this still an issue? There were some fixes a couple of months ago that may have resolved this.

**Comment by NanoCode012** [comment]
> @NanoCode012 is this still an issue? There were some fixes a couple of months ago that may have resolved this.

Hello @j4w8n , thanks for your comment. I saw the related Issue and fixes. Unfortunately, I will be a bit busy to test this for a while. I am currently still using my workaround. I will update the thread when I get to test it.

**Comment by avgupta456** [comment]
What is the current status with this? I think I am also running into the same issue...

**Comment by silentworks** [comment]
Can't reproduce and there are a number of example projects showing how to use the auth-helpers with different frameworks https://github.com/supabase-community/supabase-by-example.

**Comment by NanoCode012** [comment]
Sorry I just remembered about this again.

I tested on the setup (both locally and online), and I could not reproduce it again. What changed was `react` version, `nextjs` version, browser, and device OS despite same `auth-helpers` and `supabase` version..
