### ISSUE TITLE
SvelteKit Docs are outdated

### ISSUE THREAD

**Issue by arnu515** [supabase/auth-helpers#371]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#server-side-data-fetching-with-rls

## Describe the problem

The `withAuth` method is no longer available in `@supabase/auth-helpers-sveltekit`

## Describe the improvement

Can you please update the docs with the newer method of server side fetching with RLS? I'm new to this library, and just noticed it

## Additional context

The `withAuth` method is mentioned in the docs
![image](https://user-images.githubusercontent.com/52203828/200149014-af10c8c0-18f7-4bba-bd5c-2702768e4b11.png)

But it is not available in the library
![image](https://user-images.githubusercontent.com/52203828/200148991-c51c767c-7586-4e1d-9a8d-eb5b7fc7ac3b.png)

**Comment by cfowles** [comment]
@arnu515 Did you find the new method? I'm running into this issue now

**Comment by cfowles** [comment]
It looks like the documentation is updated here: https://github.com/supabase/auth-helpers/tree/main/packages/sveltekit 

I think the main issue is the site documentation (https://supabase.com/docs/guides/auth/auth-helpers/sveltekit) not being updated as it looks like is a separate issue.

**Comment by silentworks** [comment]
I've opened a PR to fix this https://github.com/supabase/supabase/pull/10229, this should be resolved soon.

**Comment by arnu515** [comment]
> @arnu515 Did you find the new method? I'm running into this issue now

No, unfortunately. I just got `session` from the `getSupabase()` function and checked if it was null or not.

**Comment by arnu515** [comment]
> I've opened a PR to fix this [supabase/supabase#10229](https://github.com/supabase/supabase/pull/10229), this should be resolved soon.

Thanks!

**Comment by silentworks** [comment]
Fixed.
