### ISSUE TITLE
Updating `@supabase/auth-ui-react` in Next JS example

### ISSUE THREAD

**Issue by AhmadSaman** [supabase/auth-helpers#372]
# Chore
Updating `@supabase/auth-ui-react` package from `0.1.8` to `0.2.5`
## Describe the chore
When running the NEXT JS example it gives a warning in the console that says `Received false for a non-boolean attribute loading`, the `@supabase/auth-ui-react` package causes this warning, it is fixed in version `0.2.3` in the `@supabase/auth-ui-react` and I will create a PR for it and update the `@supabase/auth-ui-react` in the NEXT JS example to latest one `0.2.5`.
## Additional context
![Screenshot 2022-11-06 193613](https://user-images.githubusercontent.com/55833403/200184199-c24e3bfc-56c2-40be-ae5e-b7bead9ffbcc.jpg)
![Screenshot 2022-11-06 193804](https://user-images.githubusercontent.com/55833403/200184202-5d8e566e-e8eb-4ae8-bc1c-3cdf667f95b8.jpg)
![Screenshot 2022-11-06 193935](https://user-images.githubusercontent.com/55833403/200184205-68a1856f-8936-418d-834a-a752da8355e7.jpg)

**Comment by thorwebdev** [comment]
Thanks, updated.
