### ISSUE TITLE
NextJS: types of ctx object passed to getServerSideProps are incorrect

### ISSUE THREAD

**Issue by mrmikardo** [supabase/auth-helpers#374]
# Bug report

In NextJS server-side views wrapped in the `withPageAuth` helper, the function passed as the second argument (`async getServerSideProps(ctx, supabase)`) takes a `ctx` parameter which includes `.req` and `.res` attributes. However, these attributes don't play nicely with the `NextApiRequest` and `NextApiResponse` types that `getServerSideProps` props typically expects.

## To Reproduce

1. Scaffold a fresh NextJS project `npx create-next-app@latest` with TypeScript support.
2. Install Supabase JS and auth helper deps.
3. Create a page and add the following piece of code;

```
export const getServerSideProps = withPageAuth({
  redirectTo: '/',
  async getServerSideProps(ctx, supabase) {
    const { req, res }: { req: NextApiRequest, res: NextApiResponse } = ctx
    return res.redirect('/')
  }
})
```

Make sure to import `withPageAuth`!

6. The TypeScript compiler should immediately report an error;

```
Type 'GetServerSidePropsContext<ParsedUrlQuery, PreviewData>' is not assignable to type '{ req: NextApiRequest; res: NextApiResponse<any>; }'.
  Types of property 'req' are incompatible.
    Type 'IncomingMessage & { cookies: Partial<{ [key: string]: string; }>; }' is missing the following properties from type 'NextApiRequest': query, body, envts(2322)
```

## Expected behavior

It should be possible to destructure `ctx` and get back `req` and `res` objects which have `NextApiRequest` and `NextApiResponse` types, respectively (the types should be compatible).

## System information

- OS: macOS 12.2.1
- Version of supabase-js: 2.0.4
- Version of Node.js: 14.18.2

**Comment by NanoCode012** [comment]
To my understanding, those functions will be deprecated in the [next minor release (v0.6.X)](https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/MIGRATION_GUIDE.md) due to the new update on middleware https://github.com/supabase/auth-helpers/commit/d8f7446b8661df02ef9ac8984ef972a766eb70db

**Comment by mrmikardo** [comment]
@NanoCode012 thanks, [this](https://github.com/supabase/auth-helpers/commit/d8f7446b8661df02ef9ac8984ef972a766eb70db#diff-e65a46e4b1105213e24b784fb224ac187a64fcba3b827b9ebe93a9fc9d43c89aR31) in particular does look as if it fixes the typing issue 😃
