### ISSUE TITLE
useSupabase is not a function

### ISSUE THREAD

**Issue by jopfre** [supabase/auth-helpers#375]
# Improve documentation

## Link 

https://www.npmjs.com/package/@supabase/auth-helpers-nextjs

## Describe the problem

The docs for client-side data fetching with RLS say to:

```
import {
  useUser,
  useSessionContext,
  useSupabase
} from '@supabase/auth-helpers-react';
```

and

```
  const { isLoading, session, error } = useSessionContext();
  const supabase = useSupabase();
```

Firstly, `useSupabase` isn't a function. Perhaps it should be` useSupabaseClient`.

Secondly, the docs say 

> you need to make sure to use the supabaseClient from the useSessionContext

however this is not what is shown in the example.

## Describe the improvement

If the intention is to use `useSupabaseClient()` update the docs to show this. Or if we should ge the client from `useSessionContext` show how this should be done.

**Comment by thorwebdev** [comment]
Yes, sorry, it's `useSupabaseClient`. Updating now.
