### ISSUE TITLE
It tells me that a method that should exist is not a function.

### ISSUE THREAD

**Issue by CesarGMEFA** [supabase/auth-helpers#381]
# Bug report

## Describe the bug
I download the dependencies, perform the Basic Setup as indicated in the documentation: https://supabase.com/docs/guides/auth/auth-helpers/nextjs#install-the-nextjs-helper-library

And instantly I get "Unhandled Runtime Error
TypeError: supabaseClient.auth.getSession is not a function"

## Expected behavior
My intention is to apply what appears in the documentation, in section Server-side rendering (SSR). Create the user redirection on the server.

## Code
```js
 // pages/_app.js
import { createBrowserSupabaseClient } from '@supabase/auth-helpers-nextjs'
import { SessionContextProvider } from '@supabase/auth-helpers-react'

import { useState } from 'react'

import '../styles/global.css'

import ProfileContext from '../utils/context/ProfileContext'
import useProfile from '../utils/hooks/useProfile'

const MyApp = ({ Component, pageProps }) => {

  const [supabaseClient] = useState(() => createBrowserSupabaseClient())
  console.log('supabaseClient', supabaseClient);
  
  return (
    <SessionContextProvider
      supabaseClient={supabaseClient}
      initialSession={pageProps.initialSession}
    >
      <ProfileContext.Provider value={useProfile()}>
        <Component {...pageProps} />
      </ProfileContext.Provider>
    </SessionContextProvider>
  )
}
export default MyApp
```

## Screenshots
![image](https://user-images.githubusercontent.com/83330595/201577017-fe7c9c4c-0eb7-4415-afa6-363832796108.png)
### console
![image](https://user-images.githubusercontent.com/83330595/201577074-3c13c18b-fb28-494a-975c-add537c390be.png)

## System information

- OS: Windows
- Browser: Chrome
- Version of supabase-js: ^1.35.6
- Version of Node.js: 16.13.2

**Comment by thorwebdev** [comment]
If you're using the latest version of `@supabase/auth-helpers-react` you will need the following peerdependecy: https://github.com/supabase/auth-helpers/blob/main/packages/react/package.json#L37-L39

```
"@supabase/supabase-js": "^2.0.4"
```

You can read about upgrading supabase-js here:
- https://supabase.com/docs/reference/javascript/upgrade-guide
