### ISSUE TITLE
[Next.js] Allow overwriting of client URL and key.

### ISSUE THREAD

**Issue by Alexnortung** [supabase/auth-helpers#384]
When using `createMiddlewareSupabaseClient` it is not possible to set api url and key. In the source code it seems like it takes it directly from the environment variables, which I think is fine for fallback.
However I would like to define my environment variables as I like and not be dependent on how library maintainers require my envrionment to be configured.

I suggest adding one or two paramenters more to the function such that the user can define api url and key.

Thanks in advance

Related code:
https://github.com/supabase/auth-helpers/blob/2be3f1001c5770db591d1d84cec02f4648ecfd75/packages/nextjs/src/index.ts#L123-L124

**Comment by thorwebdev** [comment]
The main thought behind this is to prevent folks from accidentally supplying the wrong keys. E.g. with the auth helpers you would never want to use the `SERVICE_ROLE_KEY`. By requiring specifically named env vars we can effectively communicate that. 

Can you provide some background on why this is problematic for you? We can consider allowing passing in of URL and key and documenting the anon key requirement.

**Comment by Alexnortung** [comment]
What if I use another library that wants me to name the `SUPABASE_ANON_KEY` something else in the environment variables, then I would need to declare it twice. And that's the part I want to avoid.

I understand the idea of making sure the user doesn't accidentally supply the wrong key, but I don't think that is a good enough argument not to make an overloaded function where the user can supply their own key and url.

My use case is that I want to deploy to vercel and use shared environment variables and to not confuse the different keys I would like to name my environment variables something else like: `NEXT_PUBLIC_PROJECT1_SUPABASE_ANON_KEY` or for another project `NEXT_PUBLIC_PROJECT2_SUPABASE_ANON_KEY`. This would greatly help the deployment process and management.

**Comment by cwierzbicki00** [comment]
@thorwebdev Hello, my team is having the same issue here. We utilize multiple project keys / URLs and have different names for them. In my opinion, it is an unreasonable protection to prevent the supplying of differently named keys. It is also inconsistent with the rest of the product. This is the only instance we've encountered that doesn't support this mechanism. Unfortunately, this is currently blocking us from using the Nextjs auth helpers provided. 

Is there any estimate on when this would be supported? I have never contributed to an open-source project myself, but would be willing to take a stab at it if need be.

**Comment by thorwebdev** [comment]
Fair, thanks everyone for the feedback! I think we can make this a non-breaking change by allowing you to overwrite the URL and key and falling back to the env vars if not provided.

**Comment by logemann** [comment]
@thorwebdev especially cause its not easy to say that with auth-helpers you always want to use anon-key. What if i have an API Route in NextJS (backend code) which does an inviteUserByEmail call. This call needs the service key. Furthermore its even safe to use the SERVICE_KEY there because its backend code and key wont ever be exposed. 

So at least for the createServerSupabaseClient() it would make massive sense to somehow say that i want to use the SERVICE_KEY.

**Comment by thorwebdev** [comment]
> @thorwebdev especially cause its not easy to say that with auth-helpers you always want to use anon-key. 

Yes, auth-helpers need to always use an anon key NEVER a service key! 

> What if i have an API Route in NextJS (backend code) which does an inviteUserByEmail call. This call needs the service key. Furthermore its even safe to use the SERVICE_KEY there because its backend code and key wont ever be exposed. 

In this scenario you need to use a plain supabase-js client with the service role key. If you use the auth-helpers here, your service role key will be replaced with the signed in user's JWT and your admin API call will fail. 

> So at least for the createServerSupabaseClient() it would make massive sense to somehow say that i want to use the SERVICE_KEY.

That's not true. You use createServerSupabaseClient to get a client that can act on the logged in users behalf on your server. If you need to do admin actions you need to use a normal supabase-js client. 

I hope it now makes sense why we decided to go the env var route. 

So I guess with enabling the override we also need to make sure we have docs that explain this well. Unfortunately folks don't always read the docs.

**Comment by logemann** [comment]
> > What if i have an API Route in NextJS (backend code) which does an inviteUserByEmail call. This call needs the service key. Furthermore its even safe to use the SERVICE_KEY there because its backend code and key wont ever be exposed.
> 
> In this scenario you need to use a plain supabase-js client with the service role key. If you use the auth-helpers here, your service role key will be replaced with the signed in user's JWT and your admin API call will fail.

Oh. You are right. I didnt thought about that. I somehow thought its even good to have also the user JWT so that i can check for a session in the API route but then of course, you cant have both in the resulting supabase call.

**Comment by thorwebdev** [comment]
@logemann yah, it's unfortunately not immediately clear what is happening under the hood. e.g. not everyone knows that the API keys are just JWTs with specific roles and that when a user logs in we swap the key for their JWT. Do you have any recommendations on how we can make that clearer?

**Comment by david-plugge** [comment]
We could run the key through a check, essentially parse it and check if it's a anon key or not and throw an error with a good explanation.

**Comment by david-plugge** [comment]
This however would add a bit of overhead that shouldnt be necessary with good documentation.

**Comment by logemann** [comment]
> @logemann yah, it's unfortunately not immediately clear what is happening under the hood. e.g. not everyone knows that the API keys are just JWTs with specific roles and that when a user logs in we swap the key for their JWT. Do you have any recommendations on how we can make that clearer?

To be honest... your explanation above was very precise and compact. Dont know if its written somewhere. Perhaps its already mentioned in your Auth docs but if not, something like what you ve just written wouldnt hurt. 

So the general idea that a normal supabase client bootstraps with an anon-key which itself is a JWT with basic permissions which gets replaced with a user JWT after login might help some people. But as i said, most likely exactly this is already mentioned somewhere and people like me just dont get it in the first run ;-) Authentication and Authorization is always the toughest part to explain and to digest.
