### ISSUE TITLE
Invalid `@supabase/auth-helpers-nextjs` exports layout/structure

### ISSUE THREAD

**Issue by Andarist** [supabase/auth-helpers#386]
When bundling this package using Next.js it kinda works so perhaps this won't be a big issue for you. It works there because how webpack polyfills node things etc. So my educated guess is that webpack replaces `__dirname` with something. It could be related to other bundler-specific things (like some tree-shaking) though.

Ok, but what's the actual problem? This package can't be correctly bundled by Vite, or rather - the created bundle can't be used in a browser.

The sample input file can look like this:
```ts
import { createBrowserSupabaseClient } from '@supabase/auth-helpers-nextjs';
console.log(createBrowserSupabaseClient())
```

You pack into this single module both server-related and browser-related functions and you import from `next/server` to make the former work:
https://github.com/supabase/auth-helpers/blob/9a0fb93abfdafcbeaea60efb76b910b04d9f522a/packages/nextjs/src/index.ts#L15

This in turn brings a lot of things with it from the `next/server` module. In my case the error manifested because of those things that are loaded by `next/server`:
https://github.com/vercel/next.js/blob/9fe5317417e69b59920296f88af273e3c58977e8/packages/next/server.js#L6-L9

That in turn leads to importing a compiled `ua-parser-js`:
https://github.com/vercel/next.js/blob/9fe5317417e69b59920296f88af273e3c58977e8/packages/next/server/web/spec-extension/user-agent.ts#L1

And that in turn leads to executing a line referencing to `__dirname`, somewhere there:
https://github.com/vercel/next.js/blob/9fe5317417e69b59920296f88af273e3c58977e8/packages/next/compiled/ua-parser-js/ua-parser.js#L10

And that results in a `ReferenceError` in the browser.

If you'd be willing to fix this I'm open to brainstorming ideas on how to fix this. I understand most of the peculiarities of JS bundling and I could help you with that.

**Comment by silentworks** [comment]
Since this is the NextJS auth helpers and NextJS doesn't use Vite this isn't an issue.

**Comment by Andarist** [comment]
I'm able to use a custom webpack config with NextJS and I could end up with the same problem this way.

**Comment by silentworks** [comment]
Please provide a reproducible example of this issue with a custom webpack config with NextJS and we'll have a look into it.

**Comment by Andarist** [comment]
@silentworks here you go, the repo can be found [here](https://github.com/Andarist/nextjs-supabase-browser-error).

1. I'm just creating the "browser" client [here](https://github.com/Andarist/nextjs-supabase-browser-error/blob/e885c4faded1d1387a16bc9d0feaf501d086efae/src/pages/_app.tsx#L4-L11).
2. I disabled node polyfills [here](https://github.com/Andarist/nextjs-supabase-browser-error/blob/e885c4faded1d1387a16bc9d0feaf501d086efae/next.config.js#L4-L6). I think it's a *reasonable* thing to do for a browser. I don't want my dependencies to accidentally pull in some extra cruft, I try to minimize the bundlesize after all.
3. Truth to be told, with this particular polyfill disabling I also had to patch `globalThis.global` [here](https://github.com/Andarist/nextjs-supabase-browser-error/blob/e885c4faded1d1387a16bc9d0feaf501d086efae/src/pages/index.tsx#L16-L20) to get Next running. That's a separate issue though. I could also disable polyfills more granularly, so I could disable `__dirname` without disabling `global`.

With this setting I get this error in the browser:
<img alt="ReferenceError: __dirname is not defined" width="431" alt="Screenshot 2023-04-08 at 13 03 55" src="https://user-images.githubusercontent.com/9800850/230717733-694cb5c4-cb8d-467a-8c6a-ba21b06bc1b1.png">

and we can easily trace it to this `createBrowserSupabaseClient` call:
<img alt="call stack leading to the error showing how createBrowserSupabaseClient call leads to the crash" width="1533" alt="Screenshot 2023-04-08 at 13 05 29" src="https://user-images.githubusercontent.com/9800850/230717806-96ab51e3-26eb-4959-8735-65b49b52c5c2.png">

Where the first stack frame in this call is the one that throws and which is showcased on the previous screenshot
