### ISSUE TITLE
Getting "No API key found in request","hint":"No `apikey` request header or url param was found." when calling any SignInWithOAuth method

### ISSUE THREAD

**Issue by Metaphysics0** [supabase/auth-helpers#388]
# Bug report

## Describe the bug

Using auth-helpers with Next.js13 and server components the app directory, and receiving a `{"message":"No API key found in request","hint":"No `apikey` request header or url param was found."}` error whenever calling any signInWithOAuth method from the `supabaseBrowserClient`

For Google OAuth, I am able to enter the initial email selection OAuth screen, however it crashes after selecting a profile.
For Spotify, it crashes immediately.

I made sure to include the .env.local variables in my directory.

See the very simple way I'm implementing it [here](https://github.com/Metaphysics0/bandmates/blob/2a6dfd6101062ad1156dd69406cd5b0c729e024a/ui/SignUpModal.tsx#L154):
which calls [this](https://github.com/Metaphysics0/bandmates/blob/2a6dfd6101062ad1156dd69406cd5b0c729e024a/lib/supabase/auth.ts#L5)

## To Reproduce

[See how I'm using it here:](https://github.com/Metaphysics0/bandmates/blob/2a6dfd6101062ad1156dd69406cd5b0c729e024a/ui/SignUpModal.tsx#L154)
which calls this method:

## Expected behavior

For it not to crash

## Screenshots

<img width="1512" alt="Screen Shot 2022-11-24 at 22 18 07" src="https://user-images.githubusercontent.com/47161696/203858747-11c279df-3336-40a1-aae9-75329abce96e.png">

## System information

- OS: macOS 12.2
- Packages:  "@supabase/auth-helpers-nextjs": "^0.5.2", "@supabase/auth-helpers-react": "^0.3.1", "@supabase/supabase-js": "^2.1.0",
- 
- Version of Node.js: [e.g. 18.12.0]

**Comment by kyang6** [comment]
I'm also seeing this bug. Any tips on how you fixed this Metaphysics0?

**Comment by MajesticGray** [comment]
I am also experiencing this bug
using:
```
supabase_flutter: ^1.5.0

**Comment by kibitheM** [comment]
why close without offering a solution..experiencing the same here too

**Comment by DanisJa** [comment]
Still having this issue at Next.js 14 and using `@supabase/ssr` instead of auth helpers. Redirecting to `data.url` after calling ```const {data} = await supabase.auth.signInWithOAuth({provider: 'google', options: 
{redirectTo: 'auth/callback'}})```

**Comment by TomasSestak** [comment]
I specified urls without the http/s

https://github.com/supabase/supabase-flutter/issues/327
