### ISSUE TITLE
Debugging not possible with example: nextjs-server-components

### ISSUE THREAD

**Issue by z33bs** [supabase/auth-helpers#390]
# Bug report

## Describe the bug
This example runs fine with `npm run dev`, but crashes when debugging on Webstorm or VsCode. The following error is copied from Webstorm.

TypeError: Cannot read properties of undefined (reading 'cookies') at cookies (webpack-internal:///(sc_server)/./node_modules/next/dist/client/components/headers.js:23:25) at getCookie (webpack-internal:///(sc_server)/./node_modules/@supabase/auth-helpers-nextjs/dist/index.js:355:33) at createServerSupabaseClient (webpack-internal:///(sc_server)/./node_modules/@supabase/auth-helpers-shared/dist/index.js:355:52) at createServerComponentSupabaseClient (webpack-internal:///(sc_server)/./node_modules/@supabase/auth-helpers-nextjs/dist/index.js:346:71) at RootLayout (webpack-internal:///(sc_server)/./app/layout.tsx:25:120) at preloadComponent (/Users/zeebs/GitRepos/supabase-next13-auth-example/examples/nextjs-server-components/node_modules/next/dist/server/app-render.js:79:22) at /Users/zeebs/GitRepos/supabase-next13-auth-example/examples/nextjs-server-components/node_modules/next/dist/server/app-render.js:750:24 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async createComponentTree (/Users/zeebs/GitRepos/supabase-next13-auth-example/examples/nextjs-server-components/node_modules/next/dist/server/app-render.js:749:25) at async wrappedRender (/Users/zeebs/GitRepos/supabase-next13-auth-example/examples/nextjs-server-components/node_modules/next/dist/server/app-render.js:891:47) {digest: "1536623941", stack: "TypeError: Cannot read properties of undefined (re…de_modules/next/dist/server/app-render.js:891:47)", message: "Cannot read properties of undefined (reading 'cookies')"}

## To Reproduce

clone and run the nextjs-server-components example (run's fine with npm run dev)
Then try and run with debugger attached (i've tried both Webstorm and VSCode)
-> should crash with Unhandled Runtime Error: Cannot read properties of undefined (reading 'cookies')

## Expected behavior
Should run same in debugger as in dev mode

## System information

- MacOS
- Chrome, Brave, Safari
- Version of supabase-js: 2.0.4
- Version of Node.js:  18.7.0

## Additional context

Am looking to migrate to server-components architecture, but won't until I'm confident that I can debug my code easily

**Comment by dimassrio** [comment]
`  createServerComponentSupabaseClient({
        headers,
        cookies,
    })`
    
    I'm having the same error.

**Comment by silentworks** [comment]
The debugger likely has no understand of a monorepo and this could potentially be causing the issue. Closing this as its more related to the debugging tool than the codebase.
