### ISSUE TITLE
Docs improvement suggestions for SvelteKit

### ISSUE THREAD

**Issue by Darkness-2** [supabase/auth-helpers#392]
# Improve documentation

As I was trying to wrap my head around using this for auth in SvelteKit both server and client-side, I got a bit confused at a few things I wanted to point out.

## Links

https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/README.md
https://supabase.com/docs/guides/auth/auth-helpers/sveltekit

## Use of both +layout.ts and +layout.server.ts

In the documentation for the SvelteKit Helper, it's a bit confusing as to whether you should use +layout.server.ts or +layout.ts. If you create both of those load functions, the shared version (+layout.ts) will simply override the server version, thus it is not required. However, the docs state this is an optional addition, not a replacement.

I imagine in general it is simply better to use the shared (+layout.ts) in all cases? Not entirely sure the +layout.server.ts is required if you choose to also use the +layout.ts version. Are there any advantages to doing it the server-only way?

## Use of older-style "$app/stores"

This is a relatively minor improvement - is there any reason why not to use the new way of importing data returned from a load function? The way currently used in the docs of using "$app/stores" seems slightly outdated with the new direction SvelteKit is going. 

I believe instead of using the store you can simply do the following:

```ts
<script lang="ts">
  import type { PageData } from "./$types";

  export let data: PageData;

  if (data.session) {
    console.log("There is a user!");
  }
</script>
```

## Not sure this check is needed?

Related to the above, I am not sure if this statement in the docs is true:

> For [row level security](https://supabase.com/docs/learn/auth-deep-dive/auth-row-level-security) to work properly when fetching data client-side, you need to make sure to import the { supabaseClient } from $lib/db and only run your query once the session is defined client-side in $page.data

Given we're passing the session into $page.data (or as I suggested above, simply into data), the session should already be set upon rendering of the page in my understanding. Therefore, no need to check it before using it.

### Additional questions

Was just wondering if there is any reason why the approach of this package was not to use the handle function on both hooks.client.ts and hooks.server.ts? In other frameworks it seems they usually go this route for SvelteKit and provide things like the supabaseClient and session in locals. (example: https://lucia-auth.vercel.app/sveltekit/start-here/getting-started)

**Comment by david-plugge** [comment]
> However, the docs state this is an optional addition, not a replacement.

It actually is an addition! Maybe we need to clarify it a bit more.
The server load is used on the first request, then the shared load takes over. This makes sure we dont call the server every time we go to a different page.
The server load is necessary at the moment as we need to pass the session to the shared load functions and the ui.

> Use of older-style "$app/stores"

Both ways are valid and it´s up to the user to decide which way they want to go.
In a `+page.svelte` or `+layout.svelte` file the export `export let data: PageData` should be prefered but in Components `

**Comment by ethanfox** [comment]
There needs to be a complete overhaul on the auth documentation. Everything is scattered across GitHub projects and some of the docs are outdated.

**Comment by david-plugge** [comment]
> There needs to be a complete overhaul on the auth documentation. Everything is scattered across GitHub projects and some of the docs are outdated.

Yeah many things changed in sveltekit. I will take a look at the sveltekit docs and examples in the next week and open a new issue to accumulate all the changes we need to account for.

**Comment by Darkness-2** [comment]
> > However, the docs state this is an optional addition, not a replacement.
> 
> It actually is an addition! Maybe we need to clarify it a bit more. The server load is used on the first request, then the shared load takes over. This makes sure we dont call the server every time we go to a different page. The server load is necessary at the moment as we need to pass the session to the shared load functions and the ui.
> 
> > Use of older-style "$app/stores"
> 
> Both ways are valid and it´s up to the user to decide which way they want to go. In a `+page.svelte` or `+layout.svelte` file the export `export let data: PageData` should be prefered but in Components we have to use the `page` store from `$app/stores`.

Ah I see that explains the requirement for the server load! And agreed things are changing very quickly with SvelteKit so it is hard to keep up with the latest ways of doing everything.

**Comment by chanmathew** [comment]
I also want to point out this section here on Server side RLS: https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#server-side-data-fetching-with-rls

For the example in the second paragraph:
`For [row level security](https://supabase.com/docs/learn/auth-deep-dive/auth-row-level-security) to work in a server environment, you need to use the getSupabase helper to check if the user is authenticated. The helper requires the event and returns session and supabaseClient:`

I believe the code below be importing `PageServerLoad` instead of `PageLoad`?
```
import type { PageLoad } from './$types'
import { getSupabase } from '@supabase/auth-helpers-sveltekit'
import { redirect } from '@sveltejs/kit'

export const load: PageLoad = async (event) => {
  const { session, supabaseClient } = await getSupabase(event)
  if (!session) {
    throw redirect(303, '/')
  }
  const { data: tableData } = await supabaseClient.from('test').select('*')

  return {
    user: session.user,
    tableData,
  }
}
```

**Comment by gkatsanos** [comment]
I read the OP's message and I was wondering if part of it could be related to my issue ? https://github.com/supabase/supabase/issues/11663 
The documentation chooses to override the out of the box form SSR submission and do things inside the client - which is fine but doesnt feel so 'svelte-kit'-y?

**Comment by silentworks** [comment]
@gkatsanos Svelte Kit is both client side and server side, some people uses it purely in SPA form or even in a dual way of client-side and server-side mix, that's the flexibility of Svelte Kit. There is not much of a 'svelte-kit'-y way. Also your issue is covered quite well in the documentation as I've linked in your other issue you opened.

**Comment by silentworks** [comment]
No longer applicable as the API has changed.
