### ISSUE TITLE
[Next13/App directory]: Root layout requires refresh for middleware to detect session with signInWithPassword()

### ISSUE THREAD

**Issue by hjaber** [supabase/auth-helpers#393]
# Bug report
After authenticating with `signInWithPassword()`, you must refresh the page for middleware to pick up the session. 

The example [repo](https://github.com/supabase/auth-helpers/tree/main/examples/nextjs-server-components) in the supabase auth helpers does not require a refresh because it utilizes an `<a>` instead of `<Link> from "next/link"`. `<a>` will force the root layout to refresh on navigating while `<Link>` does not

I believe that `signInWithPassword()` is not an OAuth redirect method, so I thought the server should be able to access the session immediately. See @thorwebdev's [comment](https://github.com/supabase/auth-helpers/issues/341#issuecomment-1319502599) regarding OAuth (redirect methods).

If this is not the case, please close my issue.

## To Reproduce

Clone this [repo](https://github.com/supabase/auth-helpers/tree/main/examples/nextjs-server-components) or follow the [docs](https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components) to create a Next.js 13 with the app directory. Login in with `signInWithPassword()` and then navigate using a `<Link>` to a route protected by middleware `/required-session`

## Expected behavior

After logging on with `signInWithPassword()`, middleware should be able to detect the session without refreshing the root layout. Middleware cannot auth guard APIs or protected routes unless the user manually refreshes. A benefit of Nextjs.13 app directory, is to avoid refreshes so data is cached.

## Screenshot

https://user-images.githubusercontent.com/41503068/205347162-b6c64bf5-20e8-4f58-8ebf-7abe6965e571.mov

## System information

- OS: macOS 13.0.1
- Browser: Brave, Chrome
- Version of supabase-js: `"@supabase/auth-helpers-nextjs": "^0.5.2"` `"@supabase/supabase-js": "^2.1.1"` `next": "13.0.6"`
- Version of Node.js: v18.12.1

**Comment by hjaber** [comment]
This issue was not a bug in either supabase or nextjs.

This is expected behavior of the `<Link>` component from nextjs.

`<Link>` prefetches on render so when navigating to a protected route, `<Link>` already prefetched and determined if you are authenticated or not. 

This fix is to prevent prefetching which defeats the purpose of using `<Link>` and it not recommended.
` <Link prefetch={false} />`

or the better solution, prevent middleware preflight [cache](https://github.com/vercel/next.js/pull/32767):
```
response.headers.set(`x-middleware-cache`, `no-cache`);
```

**Comment by frankspin89** [comment]
@hjaber can you share how you implemented the x-middleware-cache header? My implementation doesn't work:

```
export async function middleware(req: NextRequest) {
  const res = NextResponse.next();

  res.headers.set("x-middleware-cache", "no-cache");

  // @ts-ignore
  const supabase = createMiddlewareSupabaseClient({ req, res });

  const {
    data: { session }
  } = await supabase.auth.getSession();

  console.log("Session:", session);
  //console.log("Request:", req);
  console.log("Response:", res);

  if (!session && req.nextUrl.pathname.startsWith('/profile')) {

    // Auth condition not met, redirect to home page.
    const redirectUrl = req.nextUrl.clone();
    redirectUrl.pathname = '/';
    redirectUrl.searchParams.set(`redirectedFrom`, req.nextUrl.pathname);
    return NextResponse.redirect(redirectUrl);
  }


  return res;
}
```

**Comment by hjaber** [comment]
> @hjaber can you share how you implemented the x-middleware-cache header? My implementation doesn't work:
> 
> ```
> export async function middleware(req: NextRequest) {
>   const res = NextResponse.next();
> 
>   res.headers.set("x-middleware-cache", "no-cache");
> 
>   // @ts-ignore
>   const supabase = createMiddlewareSupabaseClient({ req, res });
> 
>   const {
>     data: { session }
>   } = await supabase.auth.getSession();
> 
>   console.log("Session:", session);
>   //console.log("Request:", req);
>   console.log("Response:", res);
> 
>   if (!session && req.nextUrl.pathname.startsWith('/profile')) {
> 
>     // Auth condition not met, redirect to home page.
>     const redirectUrl = req.nextUrl.clone();
>     redirectUrl.pathname = '/';
>     redirectUrl.searchParams.set(`redirectedFrom`, req.nextUrl.pathname);
>     return NextResponse.redirect(redirectUrl);
>   }
> 
> 
>   return res;
> }
> ```
> 

https://github.com/vercel/next.js/discussions/43675

No luck either. 

I ultimately didn't think it was an elegant solution to rerun middleware on every single route change so I decided not to continue this path. 

For now, I reverted back to a provider context until they add read/write cookies with server components. Or a better way to cache the auth in server components.
