### ISSUE TITLE
signInWithPassword() returns null

### ISSUE THREAD

**Issue by ethanfox** [supabase/auth-helpers#394]
# Bug report

I have been able to create a successful signup flow but now I cannot sign in. 
The signup triggers my user database to insert a row with their uuid as the key.

### From the documentation:

```
const { data, error } = await supabase.auth.signInWithPassword({
  email: 'example@email.com',
  password: 'example-password',
})
```
### My Code:
```
  async function handleLogin() {
        console.log("Login Function running")
    if (title == "Login") {
      const { user, error } = await supabaseClient.auth.signInWithPassword({
        email: email,
        password: password,
      });
      if (user) {
        showAlert = false
        goto("/");
      } else {
        showAlert = true
        console.log("NOT A USER");
        console.log(error);
      }
    } 
  }
```
## Describe the bug
Returns null 

## To Reproduce
Use the function yourself.

## Expected behavior
Gets user data.

## Additional context
Better documentation is needed on virtually every feature of this product.

**Comment by hjaber** [comment]
Could you please add additional context?

What is the `title` variable in `if (title == "Login")`?

For example, Im not sure why you only used a `==` vs a `===`

Also, `signInWithPassword()` is not part of the auth helpers library, it is from the supabase-js library so putting an issue here will not help you find an answer.

**Comment by thorwebdev** [comment]
`signInWithPassword` does not return a `user` object but rather a `data` object that contains a `user` object: https://supabase.com/docs/reference/javascript/auth-signinwithpassword

So you need to do the following instead:

```js
const { data: { user }, error } = await supabaseClient.auth.signInWithPassword({
        email: email,
        password: password,
      });
```
