### ISSUE TITLE
Accept client options when creating a client using the auth helpers

### ISSUE THREAD

**Issue by Murkrage** [supabase/auth-helpers#396]
# Feature request

## Is your feature request related to a problem? Please describe.
When creating a client using `supabase-js` you have the option to use a [custom fetch implementation](https://supabase.com/docs/reference/javascript/initializing#custom-fetch-implementation). This currently isn't possible when creating either a browser or server client using the auth helpers.

## Describe the solution you'd like

In order to make use of Next 13's caching capabilities, I would like to be able to use their fetch implementation (which extends the native Fetch) with Supabase through the auth helpers. I think the best way to go about this is to allow us to provide the same client options we can provide using `createClient()` directly from the main library.

## Additional context

Info on Next 13's fetch: https://beta.nextjs.org/docs/api-reference/fetch

**Comment by thorwebdev** [comment]
The supabase client uses the native fetch by default. So you don't need to pass it in for Next.js 13. You can see some examples here: https://github.com/supabase/auth-helpers/blob/main/examples/nextjs-server-components/app/optional-session/page.tsx#L7-L8
