### ISSUE TITLE
Bug in older Safari browsers: "SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list"

### ISSUE THREAD

**Issue by m-deacon** [supabase/auth-helpers#398]
# Bug report

## Describe the bug

When trying to run `createBrowserSupabaseClient` the browser gives the following error: "SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.". I found [the following stackoverflow on the issue](https://stackoverflow.com/questions/60026651/safari-unexpected-token-expected-an-opening-before-a-methods-paramet)

## To Reproduce

Include the line `const [supabaseClient] = useState(() => createBrowserSupabaseClient<Database>());` and open the app in an older version of safari than v14.1 

## Expected behavior

The application should run without errorring out

## Screenshots

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/35782774/205898184-aaf2e416-3d57-42e3-aee8-d570291083b3.png">

Further down the stack trace has this line: 
<img width="594" alt="image" src="https://user-images.githubusercontent.com/35782774/205898254-304d410b-d47e-4c2d-9e0e-94772c7fff2f.png">

## System information

- OS: macOS
- Browser (if applies): Safari v13.1.3
- Version of supabase-js:
   ``` "@supabase/auth-helpers-nextjs": "^0.5.2",
    "@supabase/auth-helpers-react": "^0.3.1",
    "@supabase/supabase-js": "^2.1.2",```
- Version of Node.js: tried on both 16.13.0 and 18.12.1

## Additional context

If I comment out the line of code that creates the supabase instance the app loads fine.

**Comment by silentworks** [comment]
@m-deacon please provide a reproducible repo to make this easier to test out. I haven't ran into this issue before so a repository with the issue happening would be good to have.
