### ISSUE TITLE
Implement a way to update session in state using tokens

### ISSUE THREAD

**Issue by floatingdino** [supabase/auth-helpers#404]
# Feature request

Using `supabaseClient.auth.setSession()` seems to be the only way to use an access token and/or refresh token to manually update the client's knowledge of your auth session, however this does not affect the React context's session state. All of the Supabase client / Supabase context / GoTrue client functions that might achieve this appear to be private / internal.

I'd propose exposing the `setSession` function on the `useSession` or `useSessionContext` to solve for this, although having a `loginWithAccessToken` function on GoTrue that triggers "SIGNED_IN" listeners would also do the trick.

## Is your feature request related to a problem? Please describe.

This has come about because I'm trying to use Supabase auth inside a Capacitor app. Because the Auth UI opens in a new app pane, when it re-opens the app with the token URLs it doesn't reload the app and subsequently trigger GoTrue's `initialize` function. Login works when using live reload inside Capacitor (perhaps due to it re-rendering the app root on `visibilityChange`?) but not when using a compiled app.

## Describe the solution you'd like

Expose a function to update the session state in React context.

## Describe alternatives you've considered

This could potentially be achieved further up the chain (in `supabase-js` or `gotrue-js`). My specific issue is around having up to date session data in context state though.

**Comment by j4w8n** [comment]
@floatingdino This functionality was merged in gotrue-js a couple of days ago. The version will likely be bumped in the supabase-js client this week.

https://github.com/supabase/gotrue-js/pull/581

**Comment by silentworks** [comment]
Closing as this seem to have been resolved and OP hasn't replied since.
