### ISSUE TITLE
The webpage at http://localhost:3000/#access_token=ey...

### ISSUE THREAD

**Issue by MrlolDev** [supabase/auth-helpers#406]
# Bug report

## Describe the bug

I have followed the supabase guide to use next.js v13 https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components and I also trying clonning https://github.com/supabase/auth-helpers/tree/main/examples/nextjs-server-components And always after clicking in the login and login it give me the following error: 
![image](https://user-images.githubusercontent.com/65485999/209481050-357d21cc-e49f-4785-bdc2-fded4c5ac2b5.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to 'https://github.com/supabase/auth-helpers/tree/main/examples/nextjs-server-components'
2. Copy all the files
3. Run the code

## Expected behavior
It should log in and redirect to /

## System information

- OS: Windows
- Version of supabase-js: last version
- Version of Node.js: 18.12.1

**Comment by JoshElgar** [comment]
Any luck with this?

**Comment by jfischoff** [comment]
I'm getting this as well. It works locally but fails in production as it still tries to redirect to localhost

**Comment by silentworks** [comment]
Can't replicate. Also you shouldn't be copying example projects from this repo to use outside of it as they were built to work in a monorepo setting and could become broken outside of this setting. These examples are for developers working on the `auth-helpers` to test if a features is working.
