### ISSUE TITLE
Injecting type definitions does not work

### ISSUE THREAD

**Issue by TomsPoint** [supabase/auth-helpers#407]
# Bug report / Feature request

## Describe the bug / missing feature

 Typescript throws  error "Expected 0 type arguments, but got 1" and types do not get injected when import { createClient } from "@supabase/auth-helpers-sveltekit"

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

`
import { createClient } from "@supabase/auth-helpers-sveltekit"
import type { Database } from "./database.types";

export const supabaseClient = createClient<Database>{PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY,}
`

## Expected behavior

Same behaviour when importing { createClient } from "@supabase/supabase-js"

## System information

- Version of supabase-js': 2.2.2
- Version of auth-helpers-sveltekit': 0.8.6
-  Version of sveltekit: 1.0.0

## Additional context

When importing from "@supabase/supabase-js" type injecting works but logout functionality does not work any more

## Workaround

Create 2 clients one with the import from "@supabase/supabase-js" and one with the import from "@supabase/auth-helpers-sveltekit"

**Comment by yoont4** [comment]
Same issue here. The docs recommended way of overriding the module types doesn't work for me either: https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/README.md#typings

Nothing happens when I do this, it still thinks everything is untyped.

**Comment by alvinsga** [comment]
Any update on when this will be fixed?

**Comment by david-plugge** [comment]
The types must be injected into `src/app.d.ts`

https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#typings

This way you get autocompletion in every place without the need of passing the database types

**Comment by TomsPoint** [comment]
Thx @david-plugge that works :)

**Comment by mmmmillar** [comment]
Is there something else you need to run to make this work? Have updated `app.d.ts` but still getting the error
