### ISSUE TITLE
TypedSupabaseClient should be moved directly to `@supabase/auth-helpers-sveltekit`

### ISSUE THREAD

**Issue by zlepper** [supabase/auth-helpers#409]
# Bug report

## Describe the bug

The type `TypedSupabaseClient` is currently in `@supabase/auth-helpers-sveltekit/dist/types`, when imported. 

## To Reproduce

Try to import `TypedSupabaseClient`

## Expected behavior

It should be imported from `@supabase/auth-helpers-sveltekit` instead.

## System information

- OS: Windows
```
		"@supabase/auth-helpers-sveltekit": "0.8.6",
		"@supabase/supabase-js": "2.2.2"
```

**Comment by silentworks** [comment]
This has been fixed in d3366e4bfc19f09049709e8ab7f83e4f9273e231 and should be available in the latest version (0.8.7) of the library.
