### ISSUE TITLE
useSession/useUser returns null initially when reloading page for a logged-in user

### ISSUE THREAD

**Issue by vymao** [supabase/auth-helpers#412]
# Bug report
useSession/useUser returns null initially when reloading page for a logged-in user. 

## Describe the bug

I am trying to conditionally render a login page with Supabase, whereby if the user is already logged in, there should be a redirect to the home page. I am using NextJS 13. 

Right now, I have this: 
```
import {
    Auth,
    // Import predefined theme
    ThemeSupa,
} from '@supabase/auth-ui-react'
import { useSession, useSupabaseClient } from '@supabase/auth-helpers-react'
import { Box } from '@mantine/core';
import { useRouter } from 'next/router'

export default function AuthComp() {
    const supabase = useSupabaseClient()
    const session = useSession()
    const router = useRouter()

    console.log(session)

    if (session) {
        router.push('/')
    } else {
        return (
            <Box sx={{
                paddingLeft: '35vw',
                paddingRight: '35vw',
                paddingTop: '10vh',
            }}>
                <Auth
                    redirectTo="http://localhost:3000"
                    supabaseClient={supabase}
                    theme="dark"
                    appearance={{ theme: ThemeSupa }}
                    providers={['google', 'github', 'linkedin']}
                />
            </Box>
        )
    }
}
```
However, it seems that `useSession` may be returning null at first, leading to the Auth-UI rendering for a split second, and then returning the session, leading to the redirect.
![image](https://user-images.githubusercontent.com/18024303/210153396-68f69adc-3a1d-4658-92a4-c0ed87334e57.png)

 I want to make it so that the Auth-UI rendering for a split second does not happen. Is this possible? The docs are unclear about this. 

I have confirmed this happens if I use `useUser` as well. 

## Expected behavior

The hooks should only provide null if there is no user/session, and should not return null at all when the user is logged in. 

## System information

- OS: macOS
- Browser (if applies) chrome
- Version of supabase-js: 2.2.2
- Version of next-js: 13.0.0

**Comment by thorwebdev** [comment]
There is a `isLoading` flag on the `useSessionContext` hook:

```
const { isLoading, session, error } = useSessionContext();
```

See an example here: https://github.com/supabase/auth-helpers/blob/main/examples/nextjs/pages/index.tsx#L13
