### ISSUE TITLE
Next.js 13 dynamic routes app directory not working with createServerComponentSupabaseClient

### ISSUE THREAD

**Issue by ludwigfrank** [supabase/auth-helpers#413]
# Bug report

## Describe the bug
When using `createServerComponentSupabaseClient` in the RootLayout, trying to access dynamically generated pages throws the following error: 

`Dynamic server usage: cookies.`

The code from the example project was used.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:
- Add a dynamic route to the example project using the new app directory 
- Running the project in development mode
- Accessing a dynamically generated page in the browser

## Expected behavior
Dynamic routes are generated just as static routes in the app directory.

**Comment by ludwigfrank** [comment]
Seems to be next.js related https://github.com/vercel/next.js/issues/43181

**Comment by logemann** [comment]
@ludwigfrank How did you solve that issue on your side? There wont be a fix as it seems.

**Comment by feliche93** [comment]
@ludwigfrank I also just thought about this: https://twitter.com/cryptoneur_eth/status/1641392806106112001?s=20
