### ISSUE TITLE
auth-helpers-remix missing auth type on createBrowserClient

### ISSUE THREAD

**Issue by TranquilMarmot** [supabase/auth-helpers#416]
# Bug report

## To Reproduce

```ts
import { createBrowserClient } from "@supabase/auth-helpers-remix";

// same as from the example repo
import { createServerClient } from "utils/supabase.server";

// ...

const supabase = createServerClient({ request, response });

const {
    data: { session },
} = await supabase.auth.getSession();
```

`supabase.auth` here has an `any` type, so `session` is an `any` as well.

## Expected behavior

`supabase.auth` should be a `SupabaseAuthClient`

Doing the following is a workaround:

```ts
import type { SupabaseAuthClient } from "@supabase/supabase-js/dist/module/lib/SupabaseAuthClient";

// ...
const {
  data: { session },
} = await (supabase.auth as SupabaseAuthClient).getSession();
```

## System information

Versions:
```json
"@remix-run/node": "^1.9.0",
"@remix-run/react": "^1.9.0",
"@remix-run/serve": "^1.9.0",
"@supabase/auth-helpers-remix": "^0.1.3",
"@supabase/supabase-js": "^2.2.3",
"typescript": "^4.8.4"
```

- OS: Ubuntu
- Version of supabase-js: `2.2.3`
- Version of Node.js: `v16.13.0`

## Additional context

I'm using `pnpm` instead of `npm` but that shouldn't be causing any issues?

**Comment by david-plugge** [comment]
I can't reproduce this. Can you share the code, preferably a full reproduction?

**Comment by silentworks** [comment]
This is likely a VS Code issue, just restart the Typescript Language Server and it should resolve it.
