### ISSUE TITLE
Wrong variable name and type in docs

### ISSUE THREAD

**Issue by Olyno** [supabase/auth-helpers#418]
# Improve documentation

## Link 

https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit#account-component

## Describe the problem

In this code, we're using ``export let session: AuthSession``, but to get access to the ``session`` export from the server, the variable must be named ``data``, otherwise it will be ``undefined`` every time.

## Describe the improvement

Renaming the variable and name it ``data`` to make it works. Also the type should be ``PageData`` imported from ``./$types``, or using JSDoc ``/** @type {import('./$types').PageData} */``.

Good to know: the ``session`` variable is already types from the server.

## Additional context

/

**Comment by silentworks** [comment]
This is no longer the case as the tutorial has changed.
