### ISSUE TITLE
Allow passing of client options

### ISSUE THREAD

**Issue by thorwebdev** [supabase/auth-helpers#420]
`createBrwoserClient` in Remix and `createBrowserSupabaseClient` in Next.js currently don't support passing of supabase-js client options.

We should update them to be coherent with the Seveltekit implementation: https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/src/createClient.ts

**Comment by silentworks** [comment]
This was fixed in d3366e4bfc19f09049709e8ab7f83e4f9273e231.
