### ISSUE TITLE
Cannot use with `getStaticProps()` method in NextJS

### ISSUE THREAD

**Issue by laubonghaudoi** [supabase/auth-helpers#422]
I am trying to fetch data with NextJS's `getStaticProps()`, but I can't use the `createServerSupabaseClient()` to create a Supabase client in a page:

```tsx
import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { GetStaticPropsContext } from "next";

export const getStaticProps = async (ctx: GetStaticPropsContext ) => {
    // Cannot create a client like this
    const supabase = createServerSupabaseClient(ctx);
}
```

I got error:
```
Argument of type 'GetStaticPropsContext<ParsedUrlQuery, PreviewData>' is not assignable to parameter of type 'GetServerSidePropsContext<ParsedUrlQuery, PreviewData> | { req: NextApiRequest; res: NextApiResponse<any>; }'.
  Type 'GetStaticPropsContext<ParsedUrlQuery, PreviewData>' is missing the following properties from type 'GetServerSidePropsContext<ParsedUrlQuery, PreviewData>': req, res, query, resolvedUrlts(2345)
```

So how to use auth-helpers with `getStaticProps()`? I looked for examples, and most of them are using `createClient()` to create the client in another file, like this https://jonmeyers.io/blog/use-next-js-12-2-on-demand-isr-and-supabase-function-hooks-to-automatically-refresh-stale-data

I checked the  docs, and it only talks about how to use it with `getServerSideProps()`, doesn't mention `getStaticProps()` or `getStaticPaths()` at all: https://supabase.com/docs/guides/auth/auth-helpers/nextjs#server-side-rendering-ssr

`getStaticPaths()` has no context param, and I wonder how to create a server client in it. So, what is the best practice of using auth-helpers with `getStaticProps()` and `getStaticPaths()`?

**Comment by silentworks** [comment]
Auth Helpers is only for server side stuff in NextJS hence why it works in `getServerSideProps()`, you can just use the normal supabase client for the static props methods. This isn't a bug, its how it's intended to work.

**Comment by laubonghaudoi** [comment]
Thanks for explaining! If that's the case, can there be some documentations about this? I read the doc of [auth-helpers in NextJS](https://supabase.com/docs/guides/auth/auth-helpers/nextjs) and [tutorials in NextJS](https://supabase.com/docs/guides/getting-started/tutorials/with-nextjs) none of them mention the `getStaticProps()` or SSG.

**Comment by chhuang** [comment]
> Auth Helpers is only for server side stuff in NextJS

Doesn't `getStaticProps` also run on the server side?
