### ISSUE TITLE
Cookie not set when using the Sveltekit Auth helper and Server-Side forms

### ISSUE THREAD

**Issue by gkatsanos** [supabase/auth-helpers#424]

**Comment by gkatsanos** [comment]
@silentworks especially when following the quickstart ( https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit ) , at least myself , I was under the impression that : 
<img width="666" alt="image" src="https://user-images.githubusercontent.com/1768834/212524114-d7247ff8-5fc5-4cde-9baa-b5c413171e71.png">
the above imports the 'correct' client for both server/client side. 

I'm willing to make a new PR in the docs if that helps as while looking around for this I saw quite some confusion :) 

That would look a bit like: 

> Be advised that for every server side request to supabase, one should import the `getSupabase` function while for client side requests you'll need the `createClient`. Ensure you are importing these from `@supabase/auth-helpers-sveltekit` and not from the generic js SDK library.

WDYT?

**Comment by silentworks** [comment]
> Be advised that for every server side request to supabase, one should import the getSupabase function while for client side requests you'll need the createClient. Ensure you are importing these from @supabase/auth-helpers-sveltekit and not from the generic js SDK library.

This advice would be incorrect as you would not be creating a client other than the one you created in `db.ts` in the quickstart guide. Currently we are working to change how this work which should simplify a lot of this and remove a lot of confusion.
