### ISSUE TITLE
Logic error in determining mount state

### ISSUE THREAD

**Issue by sroussey** [supabase/auth-helpers#426]
https://github.com/supabase/auth-helpers/blob/7ddaa6a1dbb9262ea15620d661b6d1691a23623f/packages/react/src/components/SessionContext.tsx#L59

the `mounted` variable will never change.

**Comment by sroussey** [comment]
You might be looking for something like this:

https://github.com/trajano/react-hooks/tree/master/src/useMounted

**Comment by silentworks** [comment]
Please update the title of this issue with something more appropriate. Saying _This does not do anything_ as a title isn't very helpful.

**Comment by kjmph** [comment]
I happened to be reading over the code, and the same thing popped out to me.

The useEffect call should return an unmount function so when unmounted there aren't any race conditions with updating the state.

In other words, the return of the useEffect that @sroussey linked to should be:

```js
getSession();
return () => { mounted = false; };
```

**Comment by sroussey** [comment]
I mean, you are correct. Will do, but not sure how to test.

**Comment by sroussey** [comment]
> I happened to be reading over the code, and the same thing popped out to me.
> 
> The useEffect call should return an unmount function so when unmounted there aren't any race conditions with updating the state.
> 
> In other words, the return of the useEffect that @sroussey linked to should be:
> 
> ```js
> getSession();
> return () => { mounted = false; };
> ```

Needs a ref to work as expected, that won't work either.
