### ISSUE TITLE
nextjs 13 RootLayout example and SSG

### ISSUE THREAD

**Issue by logemann** [supabase/auth-helpers#434]
# Bug report

When applying the nextJS 13 (ServerComponents) RootLayout example, its not possible to use SSG anywhere in the NextJS 13 project cause of the use of createServerComponentSupabaseClient(). 

## Describe the bug

The outlined approach will lead to the following on any dynamic route with SSG (generateStaticParams()) enabled. 

<img width="994" alt="Bildschirm­foto 2023-01-23 um 15 32 41" src="https://user-images.githubusercontent.com/346353/214065534-5d05cc6f-eb7c-49c5-81de-d3f3f1befe57.png">

You will only be able to see that error in "yarn dev" of NextJS because with "yarn build" NextJS seems to do some fallback magic.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. use nextJS 13 (ServerComponents) example from this repo
2. add a dynamic route with SSG (generateStaticParams() function)
4. yarn dev
5. go to the route

## Expected behavior

a better blueprint for a nextJS 13 application together with Supabase Client. To me it seems that with the example provided, its not possible to use SSG at all.

**Comment by david-plugge** [comment]
When building a static site the helpers aren´t needed. Simply use `@supabase/supabase-js` to get your data from supabase.

**Comment by logemann** [comment]
its not a static site. Only because parts of a webpage are SSG, its not generally a static site.

**Comment by david-plugge** [comment]
That shouldn't be a problem. Just make sure you are not using the helpers for any static page.

**Comment by logemann** [comment]
So you think that people reading the Auth Helpers docs on the supabase site or using the examples from this repo, dont use it as a blueprint for their projects? And all those projects never contain SSG parts? I mean, thats the strength of NextJS to do exactly that. So i stand by it that "teaching" using a serverComponent at the RootLayout level, will pretty sure get a lot of people into trouble.

**Comment by david-plugge** [comment]
The auth helpers should be used where you need authentication on the server side like in NextJS server components. For SSG however you can´t use authentication as the pages will look the same for every request/user. As the auth helpers rely on cookies, NextJS throws an error because the sites content may depend on a cookie´s value.
SSG is still possible by creating a standalone supabase client that queries the data you want to display on the page.

I agree that this should get added to the docs so thanks for reporting.

**Comment by logemann** [comment]
Agreed. Something like "With this project RootLayout, you will never be able to use SSG inside your application" :-)
