### ISSUE TITLE
isLoading from SessionContextProvider always seems to be false

### ISSUE THREAD

**Issue by panduananto** [supabase/auth-helpers#438]
# Bug report

## Describe the bug

What is the purpose of the `isLoading` variable in the `SessionContextProvider`? i am assuming it is to indicate a loading process when we try to do some authentication process, right? So, I wanted to display a loading state when the user is trying to log in to my app. However, the `isLoading` value from `SessionContextProvider `always seems to be false so that the loading state can't be displayed. Is it because the loading process is so fast? Even if it is, i've tried toggling the network into slow 3G simulating a slow network, but still, observing the value from React Developer Tools, it is always false.

## To Reproduce

Built my own app at first, but then i just tried it using the nextjs example from the [repo](https://github.com/supabase/auth-helpers/tree/main/examples/nextjs). The 'Loaded' text never turn to 'Loading...'

## Expected behavior

isLoading value became true when the user tried to do authentication process.

**Comment by silentworks** [comment]
This should now be fixed in the latest version of 0.4.1 of `auth-helpers-react`.
