### ISSUE TITLE
Client Cookies not set in sveltekit when using auth helper 

### ISSUE THREAD

**Issue by amorfati254** [supabase/auth-helpers#439]
# Bug report

## Describe the bug

When in development mode. If I sign in to supabase using localhost or 127.0.0.1 it updates the client cookies. However, when using vite dev --host and use the network ip as url, the client side cookie is not updated when user signs in but server side shows that the sign in process was successfull as it returns user and session

## To Reproduce
Follow the supabase sveltekit tutorial to set up auth then instead of using localhost expose network ip and connect through that instead ie 192.168.31.104:5173 and client side cookies wont be updated

## Expected behavior
Should send client supabase cookies same way as using localhost

## Tried Solutions
I have changed the site url in supabase dashboard from localhost to ip address provided by vite but issue persists

## Screenshots
<img width="441" alt="Screenshot 2023-01-31 at 17 21 25" src="https://user-images.githubusercontent.com/97120767/215786157-7816de9f-6029-4336-b269-5b3850e30282.png">
<img width="441" alt="Screenshot 2023-01-31 at 17 22 00" src="https://user-images.githubusercontent.com/97120767/215786160-566a5d2d-7931-4f6a-aa31-bd13b8a5797f.png">

## System information

- OS: mac os
- Browser: chrom
- Version of supabase-js: ^2.5
-  Version of auth-helpers-sveltekit: "^0.8.7"
- Version of Node.js: 19.4.0

**Comment by david-plugge** [comment]
You have to set the `secure` option manually for the supabase client when developing outside of `localhost`
Set it to true if you use https.

_src/lib/supabase.js_
```ts
import { createClient } from '@supabase/auth-helpers-sveltekit'
import { env } from '$env/dynamic/public'
import { dev } from '$app/environment'
// or use the static env
// import { PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY } from '$env/static/public';

export const supabaseClient = createClient(
	env.PUBLIC_SUPABASE_URL,
	env.PUBLIC_SUPABASE_ANON_KEY,
	{}, // supabase client configuration
	{	// cookie options
		secure: !dev
	}
)
```

**Comment by amorfati254** [comment]
@david-plugge Thanks for the reply. I solved it by setting the secure to false but your solution is more clean.
