### ISSUE TITLE
bump supabase-js

### ISSUE THREAD

**Issue by wattsjs** [supabase/auth-helpers#440]
Hi, not sure where to post this so opening an issue

Is there a reason we are are stuck on ~`2.0.4` of supabase-js? `2.7.0` has been released which includes `gotrue-js` `2.10.0` which fixes https://github.com/supabase/gotrue-js/issues/564, which I think this would of great benefit in the `auth-helpers` 🙂

**Comment by silentworks** [comment]
Version bumped, but as David has stated here this shouldn't matter unless new Typescript changes were introduced.
