### ISSUE TITLE
Unable to use service key for createServerSupabaseClient

### ISSUE THREAD

**Issue by adamzerner** [supabase/auth-helpers#442]
# Bug report

## Describe the bug

In order to [bypass row level security](https://supabase.com/docs/guides/auth/row-level-security#you-dont-have-to-use-policies) (RLS), I would like to use the service key instead of the anon key. I'm not seeing a way to do that with `createServerSupabaseClient` from [`@supabase/auth-helpers-nextjs`](https://supabase.com/docs/guides/auth/auth-helpers/nextjs) though (nothing mentioning it in the docs).

The shape of the arguments seems to be something like this (on version `0.5.4`):
```
const supabase = createServerSupabaseClient(
  { req, res },
  {
    supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL,
    supabaseKey: process.env.SUPABASE_SERVICE_ROLE_KEY,
    options: {
      db: "foo",
      global: "bar",
      realtime: "baz",
    },
    cookieOptions: {
      ...
    }
  }
);
```
So nothing in `options` or `cookieOptions`. If anything it'd be `supabaseKey`. This code doesn't work though (I verified that `process.env.SUPABASE_SERVICE_ROLE_KEY` is correct).

```
import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";
import { NextApiRequest, NextApiResponse } from "next";

const handler = async (req: NextApiRequest, res: NextApiResponse) => {
  try {
    console.log(process.env.SUPABASE_SERVICE_ROLE_KEY);
    const supabase = createServerSupabaseClient(
      { req, res },
      {
        supabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL,
        supabaseKey: process.env.SUPABASE_SERVICE_ROLE_KEY,
      }
    );
    const response = await supabase
      .from("customers")
      .select("stripe_customer_id")
      .eq("stripe_customer_id", "cus_NFqeiuo0dGZx1A");

    res.status(200).json(response);
  } catch (e: any) {
    res.status(500).json(e);
  }
};

export default handler;
```

I just get back:
```
{
  "error": null,
  "data": [],
  "count": null,
  "status": 200,
  "statusText": "OK"
}
```

But from [this question](https://github.com/supabase/supabase/discussions/12010) I think that means the RLS is not being bypassed like it is supposed to. The table in question has RLS enabled but no policies.

## To Reproduce

n/a

## Expected behavior

The service key is used, row level security is bypassed, and the response contains the `stripe_customer_id`.

## Screenshots

None.

## System information

- OS: n/a
- Browser: n/a
- Version of supabase-js: 2.4.0
- Version of @supabase/auth-helpers-nextjs: 0.5.4
- Version of Node.js: 16.11.1

## Additional context

Using `createClient` works, so the issue seems to be specific to `createServerSupabaseClient`.

```
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL || "",
  process.env.SUPABASE_SERVICE_ROLE_KEY || ""
);
```

**Comment by thorwebdev** [comment]
Auth helpers always need to use an anon key: https://github.com/supabase/auth-helpers/issues/384#issuecomment-1396250270

If you're doing admin actions server side, simply use the normal supabase-js client with the service role key.
