### ISSUE TITLE
Explain usage of `invalidateAll` in README

### ISSUE THREAD

**Issue by brunobely** [supabase/auth-helpers#445]
# Improve documentation

## Link 

[Synchronizing the Page Store](https://github.com/supabase/auth-helpers/blob/main/packages/sveltekit/README.md#synchronizing-the-page-store)

## Describe the problem

The following line is confusing:

> If some data is not updated on signin/signout you can fall back to `invalidateAll()`.

As a new user of Supabase (and experienced with SvelteKit and Firebase but not super familiar with usage of `invalidate`/`invalidateAll`) I don't understand what that line is telling me to do. Specifically this bit: "If some data is not updated".

I think it would be helpful to expand on:

- When could data potentially not be updated? What data/where?
- How can I tell that that's happening and how can I call `invalidateAll` properly?

If the example could handle that case, that would be helpful as well.

**Comment by silentworks** [comment]
This is a SvelteKit function and we shouldn't need to document this as its already documented.
