### ISSUE TITLE
Next.js middleware sometimes doesn't have a user session after signin

### ISSUE THREAD

**Issue by jonathanwilke** [supabase/auth-helpers#446]
# Bug report

## Describe the bug

So I have a Next.js app with middleware to protect certain routes.

This is what the middleware looks like:

```typescript
import { createMiddlewareSupabaseClient } from '@supabase/auth-helpers-nextjs';
import { NextRequest, NextResponse } from 'next/server';

export async function middleware(req: NextRequest) {
  const res = NextResponse.next();
  const supabase = createMiddlewareSupabaseClient({ req, res });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session) {
    const redirectUrl = req.nextUrl.clone();
    redirectUrl.pathname = '/auth/signin';
    redirectUrl.searchParams.set(`redirectedFrom`, req.nextUrl.pathname);
    return NextResponse.redirect(redirectUrl);
  }

  return res;
}

export const config = {
  matcher: ['/app/:path*'],
};
```

On my signin page I have an effect to redirect the user after successful signin:

```typescript
useEffect(() => {
    const {
      data: { subscription },
    } = supabaseClient.auth.onAuthStateChange((event) => {
      if (event === 'SIGNED_IN') router.replace(redirectAfterSignin);
    });

    return () => subscription.unsubscribe();
  }, [supabaseClient, redirectAfterSignin]);
```

For some reason (and sorry not being able to define this more concrete) sometimes the middleware redirects back to signin even though the user was signed in successfully before. It seems like the token is maybe not set yet or not sent correctly. But I don't really know.

This app is being deployed on Vercel and the error only occur on production deployment.

**Comment by colinclerk** [comment]
Before the calling router.replace in your `useEffect`, try clearing the Next.js client-side cache:
https://github.com/clerkinc/javascript/blob/712c8ea792693a335d9bf39c28e550216cb71bcb/packages/nextjs/src/client/invalidateNextRouterCache.ts

**Comment by jonathanwilke** [comment]
Seems like this really fixed the issue! Thanks so much for your tip, Colin! 

Maybe we should mention this somewhere in the docs ?

**Comment by silentworks** [comment]
@colinclerk how would this work on a `<Link>` instead of programmatically? I found that I had to change my `<Link>` to a `<a>` instead to get this to work but if there is a more nextjs kind of way I would love to learn that way.

**Comment by colinclerk** [comment]
You want to run the cache-busting snippet any time the user signs in or signs out. I think if you can identify those moments in time using `onAuthStateChange` per Jonathan's snippet above
