### ISSUE TITLE
@supabase/auth-helpers-nextjs: upgrade devDependencies to Next.js v13

### ISSUE THREAD

**Issue by chhuang** [supabase/auth-helpers#450]
# Chore

## Describe the chore

`@supabase/auth-helpers-nextjs` has a `devDependencies` of `"next": "^12.2.5"`.

I think this is causing a TypeScript issue with the `context` object (`unstable_revalidate` has been deprecated in v13):

<img width="1132" alt="Screen Shot 2023-02-13 at 5 23 19 pm" src="https://user-images.githubusercontent.com/78710/218385710-0d1fa98b-7260-4da2-8012-e2923280b76f.png">

**Comment by silentworks** [comment]
Done.
