### ISSUE TITLE
[nextjs] Auth is not responding to changes in cookie set by server

### ISSUE THREAD

**Issue by tonyxiao** [supabase/auth-helpers#451]
# Bug report

## Describe the bug

When server does `supabase.auth.logout()` on a given request, supabase client does not pick it up until the next page reload, and still show user as logged for the current request. We should probably listen to change in cookie storage and update auth state accordingly.

**Comment by thorwebdev** [comment]
That shouldn't be the case. `supabase.auth.logout` calls the `removeItem` method which deletes the cookie. 

Can you please provide a reproducible example?

**Comment by tonyxiao** [comment]
`supabase.auth.logout` is called on server side, not client side, so it comes back with a `set-cookie` header which does not immediately affect the client . 
<img width="356" alt="image" src="https://user-images.githubusercontent.com/696842/218407747-d3ac860f-0e07-41de-8145-15bf22ef3ca0.png">

**Comment by silentworks** [comment]
I'm closing this one out as a reproducible example wasn't provided.
