### ISSUE TITLE
SvelteKit Auth Helper - Can't Invite New Users

### ISSUE THREAD

**Issue by rogadev** [supabase/auth-helpers#452]
# Bug report

## Describe the bug

Using the `@supabase/auth-helpers-sveltekit` package to create my Supabase client, logged in users are unable to invite new users to the app.

## To Reproduce

Following the instructions for setup from the [official Supabase documentation for SvelteKit](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit), I've created a basic workflow to allow me to log into my account and navigate around using auth guarded routes. Things work fine.

I've created an "invite new user" form for a logged-in user to send an invite using the async `supabase.auth.admin.inviteUserByEmail('<email_adress_here>')` function, as outlined in the [official Supabase docs](https://supabase.com/docs/reference/javascript/auth-admin-inviteuserbyemail).

However, the docs also state that **"any method under the supabase.auth.admin namespace requires a `service_role` key"** and the documentation to do so can be [found here](https://supabase.com/docs/reference/javascript/admin-api).

The problem is that if we follow the directions for setting up our Supabase client using the `auth-helpers-sveltekit` package, we don't ever enter a `service_role` key, and therefore seem not to have any ability to invite a new user to our app.

## Expected behavior

a) If functionality exists in the Supabase auth helper for SvelteKit, documentation needs to be updated to inform us of how to accomplish this.
b) If no such functionality exists in the helper, one should be created so that we can use important `supabase.auth.admin` methods in our app without having to create a separate client instance to gain access to this functionality.

## System information

- OS: Windows 10
- Version of supabase-js:
  - "@supabase/auth-helpers-sveltekit": "^0.8.7"
  - "@supabase/supabase-js": "^2.4.1"
- Version of Node.js: 18.13.0

**Comment by thorwebdev** [comment]
@rogadev the auth helpers are intended to get an authenticated supabase client that can act with the permissions of the user who is logged in. You never want to give any of your users admin permissions, that why you don't use the auth helpers with the service_role key.

Inviting users by email is an action that requires admin permissions, therefore it is under the `auth.admin` namespace, and therefore is an action that cannot be taken by any user, and therefore is not in scope of the auth helpers.

If you want to perform admin actions, you will need to create a normal supabase-js client with your service-role key, but do make sure that this is an admin action that should not be triggered client-side by users.

I hope this helps clarify.
