### ISSUE TITLE
Error injecting type definitions with auth-helpers-sveltekit

### ISSUE THREAD

**Issue by mmmmillar** [supabase/auth-helpers#456]
# Bug report

## Describe the bug

Typescript error "Expected 0 type arguments, but got 1" when doing type injection as described [here](https://supabase.com/docs/reference/javascript/typescript-support#injecting-type-definitions) but with "@supabase/auth-helpers-sveltekit"

There was a previous ticket https://github.com/supabase/auth-helpers/issues/407 which is marked as closed but this does not work for me.

## To Reproduce

1. Run `supabase gen types typescript --local > ./app/src/lib/generated/definitions.ts`

2. Add Superbase interface to `app.d.ts` and reference the generated types
![image](https://user-images.githubusercontent.com/52740958/221934633-443b1922-5ff6-4cf1-a8d9-99caa7885437.png)

3. Add type argument to createClient()
![image](https://user-images.githubusercontent.com/52740958/221935061-b880c3d5-e769-4f9f-9008-a3e8b41e2f1d.png)

## System information

- Version of supabase-js: 2.8.0
- Version of auth-helpers-sveltekit: 0.8.7

**Comment by david-plugge** [comment]
No need to add the types in `createClient`, they are automatically set by the type in `app.d.ts`

**Comment by mmmmillar** [comment]
Ah! Thank you!
