### ISSUE TITLE
[nextjs] Buffer is not supported in the Edge Runtime, other alternatives?

### ISSUE THREAD

**Issue by kamto7** [supabase/auth-helpers#469]
./node_modules/@supabase/auth-helpers-shared/dist/index.mjs
A Node.js API is used (Buffer at line: 200) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime

https://github.com/supabase/auth-helpers/blob/33c8a81770d5a6b376c658b16bb6a2ec46dcb71b/packages/shared/src/utils/cookies.ts#L65

**Comment by j4w8n** [comment]
We worked around this in the gotrue-js repo by using a slightly verbose and hard-to-read function, but it seems to work. Repo maintainers might consider it. Maybe someone can re-write it more efficiently.

https://github.com/supabase/gotrue-js/blob/master/src/lib/helpers.ts#L126

```js
export function decodeBase64URL(value: string): string {
  const key = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/='
  let base64 = ''
  let chr1, chr2, chr3
  let enc1, enc2, enc3, enc4
  let i = 0
  value = value.replace('-', '+').replace('_', '/')

  while (i < value.length) {
    enc1 = key.indexOf(value.charAt(i++))
    enc2 = key.indexOf(value.charAt(i++))
    enc3 = key.indexOf(value.charAt(i++))
    enc4 = key.indexOf(value.charAt(i++))
    chr1 = (enc1 << 2) | (enc2 >> 4)
    chr2 = ((enc2 & 15) << 4) | (enc3 >> 2)
    chr3 = ((enc3 & 3) << 6) | enc4
    base64 = base64 + String.fromCharCode(chr1)

    if (enc3 != 64 && chr2 != 0) {
      base64 = base64 + String.fromCharCode(chr2)
    }
    if (enc4 != 64 && chr3 != 0) {
      base64 = base64 + String.fromCharCode(chr3)
    }
  }
  return base64
}
```

**Comment by imownbey** [comment]
I am running into a similar error, but am slightly confused because if you look at the code it first tries to use `atob` which is available on edge runtime, I am not totally sure why I am hitting the error then. The error I am getting is:
```
./node_modules/@supabase/auth-helpers-shared/dist/index.mjs:200:0
Module not found: Can't resolve 'buffer'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@supabase/auth-helpers-nextjs/dist/index.js
./src/lib/supabase/supabase-browser.ts
./src/components/SupabaseProvider.tsx
```
This is after following https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components

**Comment by kamto7** [comment]
Is no one maintainer it?

**Comment by TedAce** [comment]
Same problem here. If a page is set to run on the edge, deploying to Vercel is not working.

`import type { NextPage } from "next";

export const config = {
  runtime: "experimental-edge",
};

// get users geo location from middleware and pass to this page
export const getServerSideProps = ({ query }: { query: any }) => ({
  props: query,
});

const Geo: NextPage = ({ country }: { country?: any }) => {
  return (
    <div className="flex h-screen flex-col">
      <main className="mx-auto max-w-7xl flex-grow px-4 py-12 sm:px-6 lg:px-8">
        <div className="sm:mx-auto sm:w-full sm:max-w-md">
          <h2 className="mt-6 text-center text-3xl text-sblack">
            Country: {country}
          </h2>
        </div>
      </main>
    </div>
  );
};

export default Geo;`

<img width="1097" alt="Screenshot 2023-03-23 at 17 07 03" src="https://user-images.githubusercontent.com/17507478/227246577-42fea9a4-015d-45c8-aa78-0620d90a7180.png">

**Comment by silentworks** [comment]
Yeah this behavior is a little odd since `atob` is available on edge runtime. Also this was working previously in edge runtime so I wonder if Vercel changed something in their setup. I will look into this a bit more and work out the best solution.

**Comment by spegoraro** [comment]
I'm also seeing this after following the Supabase docs for NextJS server components. In this guide some middleware is added to the Next.JS project. Since Vercel executes this middleware on the edge runtime it fails to deploy.

**Comment by silentworks** [comment]
Looking into this a bit more and this gets even weirder. Buffer is available globally in Edge Runtime according to the NextJS docs.

<img width="685" alt="Screenshot 2023-04-03 at 00 58 21" src="https://user-images.githubusercontent.com/79497/229389631-eb2c68a5-5d1f-4723-bdac-6c73f5255b8d.png">

**Comment by silentworks** [comment]
This has been fixed in the latest release of the auth-helpers.
