### ISSUE TITLE
Page refresh loop on 404 when using auth-helpers-sveltekit

### ISSUE THREAD

**Issue by mmmmillar** [supabase/auth-helpers#470]
# Bug report

## Describe the bug

When I go to a non-existent url, the page goes into a refresh loop. I can stop this happening if I don't call `invalidate()` inside `onAuthStateChange()`

```
// src/routes/+layout.ts
export const load: LayoutLoad = async ({ fetch, data, depends }) => {
  depends('supabase:auth');

  const supabase = createSupabaseLoadClient<Database>({
    supabaseUrl: PUBLIC_SUPABASE_URL,
    supabaseKey: PUBLIC_SUPABASE_ANON_KEY,
    event: { fetch },
    serverSession: data.session,
    onAuthStateChange() {
      invalidate('supabase:auth');
    }
  });
```

## To Reproduce

Steps to reproduce the behaviour, please provide code snippets or a repository:

1. Create an app using the sample code provided at https://www.npmjs.com/package/@supabase/auth-helpers-sveltekit
2. Go to a non-existent url

**Comment by david-plugge** [comment]
This is a known issue, we updated the docs https://supabase.com/docs/guides/auth/auth-helpers/sveltekit but since this does not require a new release of the auth helpers the README on npm isn´t updated yet.
