### ISSUE TITLE
bug: missing file is being imported in Deno using ESM

### ISSUE THREAD

**Issue by iuioiua** [supabase/auth-helpers#471]
# Bug report

## Describe the bug

A seemingly missing file is imported when importing this package from [esm](https://esm.sh/) in Deno. This behaviour causes Deno to attempt to download the file on each run, slowing down development.

## To Reproduce

Steps to reproduce the behaviour while Deno is installed:

1. Run `deno info https://esm.sh/@supabase/auth-helpers-shared@0.3.0`.
2. Observe Deno attempting to download the non-existent `https://esm.sh/v110/@supabase/supabase-js@2.10.0/dist/module/lib/types/dist/module/index.d.ts` file and reporting it as missing from the printed file list.

## Expected behaviour

Imports don't point to non-existent files.

## Screenshots

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/29347852/224573430-f23cca95-4caf-4253-99fa-5c0ed571c421.png">

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/29347852/224573455-f72bb793-4688-4661-bdca-8b132008273d.png">

## System information

- OS: macOS
- Version of @supabase/auth-helpers-shared: 0.3.0
- Version of Deno: 1.31.2

## Additional context

CC @thorwebdev, this issue comes from my findings originating in https://github.com/iuioiua/fresh-saas-toolkit/issues/8.

**Comment by SergeyLuashkov** [comment]
Hello, I also faced this problem.
Here is a temporary solution which I use the flag: `deno run --cached-only`

**Comment by iuioiua** [comment]
> Hello, I also faced this problem.
> Here is a temporary solution which I use the flag: `deno run --cached-only`

The workaround works! Thank you.

**Comment by iuioiua** [comment]
Gently pinging @david-plugge. Have you had a chance to look into this?

**Comment by david-plugge** [comment]
I didn´t yet try to replicate this. Does this error not appear when using just supabase-js?

**Comment by silentworks** [comment]
This issue has been fixed in the latest release of the auth-helpers.

**Comment by iuioiua** [comment]
This issue was fixed in esm-dev/esm.sh#572. Thanks for looking into this either way, guys 🙏🏾
