### ISSUE TITLE
Losing refresh tokens when changing subdomain

### ISSUE THREAD

**Issue by jabza** [supabase/auth-helpers#475]
My application authenticates users on the root domain, and sets the auth token cookieOptions with a wildcard subdomain.

(like ".myproject.com" ect.)

This works. "supabase-auth-token" cookie is available on all subdomains of my application.

The problem is for the two refresh cookies - these only appear of the root domain, but once the user goes to say "app.myproject.com", both the refresh cookies are no longer there. Only "supabase-auth-token".

This seems to cause problems once the refresh token is needed, with the auth middleware complaining there are none.

**Comment by thorwebdev** [comment]
The auth-helpers only set one cookie `supabase-auth-token` which encodes the refresh-token in it as well. So things seem to be working as expected.

Can you reopen this with more information about the errors your are seeing?
