### ISSUE TITLE
[Sveltekit] Setup according to docs causes infinite loop with invalidation in onAuthStateChange

### ISSUE THREAD

**Issue by bhark** [supabase/auth-helpers#477]
## StackBlitz

~~I've set up a Stackblitz with the same issue [here](https://stackblitz.com/edit/sveltejs-kit-template-default-8wp3ya?file=src/routes/+layout.svelte). Create a .env and link it with a stock Supabase project of yours.~~

## Describe the bug

After signing in using valid credentials, the `invalidate('supabase:auth')` in `+layout.svelte` is called rapidly, many times a second, until the API locks you out due to the rate limit being exceeded and the session is destroyed. If `invalidate('supabase:auth')` is commented out and replaced with a `console.log`, it is fired about every other second and the session is maintained without issues. 

Network log shows a flood of (successful) requests to `/auth/v1/token?grant_type=refresh_token`, until the rate limiter steps in. 

## Steps To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Set up a new Sveltekit project (`npm create svelte@latest new-project`)
2. Follow the Sveltekit auth helper docs [here](https://github.com/supabase/auth-helpers/tree/main/packages/sveltekit) or [here](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit) precisely 
3. Set up a form action to sign in, also as described in the docs
4. Create a `+page.svelte` with a form element and submit the sign in form using valid credentials

## Expected behavior

After setting up as according to the documentation [here](https://github.com/supabase/auth-helpers/tree/main/packages/sveltekit) or [here](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit), I should be able to sign in and have a healthy session, which should be kept in sync and be available both server-side and client-side. 

## System information

- OS: Arch Linux
- Version of supabase-js: 2.12.0
- Version of supabase-js/auth-helpers-sveltekit: 0.9.0
- Version of Node.js: 19.8.0 (also tested with 16.19.1)
- Version of Sveltekit: 1.13.0
- Version of Vite: 4.2.1
- Version of Svelte: 3.57.0

## Additional context

No typescript, no extra packages.

**Comment by silentworks** [comment]
I can't replicate this in any of the example repos I have. Also the stackblitz example doesn't work because there are CORS issues with stackblitz. You can view one of the example repo here https://github.com/supabase-community/supabase-by-example/tree/main/reset-flow/sveltekit

**Comment by bhark** [comment]
@silentworks I tried cloning the repo you linked, and am getting the exact same issue there.

**Comment by huntabyte** [comment]
I'm experiencing this exact issue. 

Reproduce:

1. Setup everything exactly as stated in the documentation
2. In the root `+layout.svelte`, add a link to a page that doesn't exist (/whatever).
3. Click the '/whatever' `<a>` element
4. Experience infinite loop of `invalidate('supabase:auth')`

**Comment by ralphwest1** [comment]
I'm running into the same issue described above.

Whenever hitting a 404 page. it starts an infinite loop of invalidating `invalidate('supabase:auth')` and then reloading over and over.

If I comment out `invalidate('supabase:auth')` in ./src/routes/+layout.svelte and restart the project the infinite ceases.

**Comment by ralphwest1** [comment]
@silentworks I was able to recreate the issue in the example repo you reference: https://github.com/supabase-community/supabase-by-example/tree/main/reset-flow/sveltekit by upgrading @supabase/supabase-js from `v2.10.0` to `v2.12.1` with `pnpm i @supabase/supabase-js@latest`

Issue seems to be directly related to underlying `@supabase/gotrue-js` going from `v2.15.0` to  `v2.16.0`

https://github.com/supabase/gotrue-js/releases/tag/v2.16.0

### To recreate
1. clone repo: https://github.com/supabase-community/supabase-by-example/tree/main/reset-flow/sveltekit
2. `pnpm i @supabase/supabase-js@latest`
3. `pnpm dev`
4. navigate to any route that will produce a 404 error such as: `http://localhost:5174/not-there`

### Temp fix until a patch
@huntabyte, @bhark 

For other running into this you can resolve by adding the below to your root package.json

```json
{
...
"pnpm": {
    "overrides": {
      "@supabase/supabase-js@2.12.1>@supabase/gotrue-js": "2.15.0"
    }
  }
}
```

**Comment by adonis2611** [comment]
@ralphwest1 tried this and still got the same issue

**Comment by ralphwest1** [comment]
@adonis2611 

The settings for overriding a nested depend package varies based on:
- Are you using pnpm or npm?
- Are you using a monorepo or single repo?
- What version of @supabase/supabse-js do you have installed?

**Comment by bhark** [comment]
I think we're talking about two different issues here, although they both seem to stem from gotrue. 

It turns out that the main issue i posted can't be reliably reproduced. A colleague of mine with the exact same version of node and npm was able to run my codebase as is without issue. 

The 404 loop that @ralphwest1 is talking about *can* apparently be reliably reproduced. My colleague had this issue too, and I can reproduce it on another workstation of mine.

**Comment by silentworks** [comment]
> I'm also experiencing an infinite invalidation loop in `onAuthStateChange` except it occurs when an error boundary is rendered @silentworks. I discovered it by clicking a link to a page in my app that doesn't exist. Currently trying to determine the root cause of this and will report back if I'm able to identify it this evening.
> 
> Reproduction Repo: [StackBlitz](https://stackblitz.com/github/huntabyte/supabase-invalidate-loop-repro) - Just add a .env with `PUBLIC_SUPABASE_ANON_KEY` & `PUBLIC_SUPABASE_URL`
> 
> Manual Repro Steps:
> 
>     1. Setup everything exactly as stated in the documentation
> 
>     2. In the root `+layout.svelte`, add a link to a page that doesn't exist (/whatever).
> 
>     3. Click the '/whatever' `<a>` element
> 
>     4. Experience infinite loop of `invalidate('supabase:auth')`

@ralphwest1 and @huntabyte yeah I can replicate this. You can fix it by updating the `script` section to be this instead, we will update the guides soon.
```ts
        import { invalidate } from '$app/navigation';
	import { onMount } from 'svelte';
	import type { LayoutData } from './$types';

	export let data: LayoutData;

	$: ({ supabase, session } = data);

	onMount(() => {
		const {
			data: { subscription }
		} = supabase.auth.onAuthStateChange((event, _session) => {
			if (_session?.expires_at !== session?.expires_at) {
				invalidate('supabase:auth');
			}
		});

		return () => {
			subscription.unsubscribe();
		};
	});
```

**Comment by huntabyte** [comment]
Awesome, thanks for the swift response & solution!

**Comment by kvetoslavnovak** [comment]
Having the same problem here. Going to non existing route causes the infinite loop. The problem seems to be caused by `invalidate('supabase:auth')` in +layout.svelte file. 
If I comment `invalidate('supabase:auth')`  out the loop stops to occur.
