### ISSUE TITLE
Initialising supabaseClient in Next.js app failing if using createBrowserSupabaseClient()

### ISSUE THREAD

**Issue by jonnicholson94** [supabase/auth-helpers#479]
# Improve documentation

## Link 

https://supabase.com/docs/guides/auth/auth-helpers/nextjs

## Describe the problem

When I am attempting to initialise my supabaseClient using createBrowserSupabaseClient(), and passing that into the SessionContextProvider, the useUser() hook is returning null. This is what the docs linked above currently recommend.

However, if I just directly pass in my supabase instance (initialised using @supabase/supabase-js package), then it works.

I figured this out by looking directly at the packages installed in my project.

As a result, it's a little confusing as the two packages don't seem like they should be mixed if a supabase instance is initialised elsewhere in the project.

## Describe the improvement

Recommend users to initialise the supabase client in a separate helper file in the linked docs above.

## Additional context

**Comment by silentworks** [comment]
The documentation is correct, however if you are using the app directory things might have changed slightly or if you are using server-side rendering (SSR) in your application this might differ. But you should only be making use of the supabase client from the `createBrowserSupabaseClient()` in your codebase. We recommend against using the normal client unless its fully client-side code.

**Comment by strangecarr** [comment]
hi @silentworks i was using createBrowserSupabaseClient() and useSupabaseClient exclusively in my codebase, but now have a need for custom headers on some requests (to use RLS with non-authenticated users), which means i need to use the normal client in some parts. Are there any plans to enable custom headers to be set using the auth-helpers?

**Comment by silentworks** [comment]
@strangecarr this is already supported by the current auth-helpers. You can see the options parameter that allows you to set headers on the `createBrowserSupabaseClient` https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/src/index.ts#L57

**Comment by jonnicholson94** [comment]
@silentworks - thanks for the response. It might just be me misunderstanding, but the docs really aren't clear about how the different types of auth helpers work with one another in my opinion - I'm still having to fiddle around to figure out how it works, and my auth functions (which I have in a separate lib) have to use the standard JS supabase package, so I can't use SSR with how this is currently implemented as an example, because the two conflict. Doesn't make sense, they should be able to work in tandem.

**Comment by silentworks** [comment]
@jonnicholson94 I'm not sure what you mean by the standard JS supabase package should work with the auth-helpers. One is stores its session in a localStorage (which is available in the browser only) while the other stores it in a cookie (which is available in both the browser and server). The two cannot work in tandem in the sense of reading the same session stored, this isn't really a auth-helpers or supabase specific issue its just how the browser/server works. If you need to do anything that requires the service_role key on the server you create a new `@supabase/supabase-js` client and use that, this is the only time you would be using both in the same project. In any other case you should be using only the `@supabase/auth-helpers-nextjs` for everything as it works on both browser and server.

**Comment by ajmeraaxesh** [comment]
Facing  fs module not found  when invoking "createBrowserSupabaseClient"  directly as shown in code in video

https://www.youtube.com/watch?v=Bh1TOpOcGJQ&list=PL5S4mPUpp4OuMkz8qqJpiTSaX9Fp0429T&index=3

Around 9.50 mark in the above video

Attached is code  and error screenshot 

![Screenshot 2023-04-08 at 1 58 02 PM](https://user-images.githubusercontent.com/831046/230711826-364e90db-4cb7-4938-b8cd-7d848292b5c6.png)
![Screenshot 2023-04-08 at 1 57 33 PM](https://user-images.githubusercontent.com/831046/230711829-59e9020f-1705-4be7-8280-b73337d55fbe.png)
![Screenshot 2023-04-08 at 1 53 54 PM](https://user-images.githubusercontent.com/831046/230711660-93be486e-2eae-4c83-a210-253cb92b56f8.png)

**Comment by ajmeraaxesh** [comment]
Confirmed with the example in the Supabase Nextjs Helper

https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components#client-components

The same issue of fs module

**Comment by lucasriondel** [comment]
same issue as @ajmeraaxesh here. constantly getting errors about the "fs" module.
<img width="580" alt="CleanShot 2023-04-08 at 14 56 19@2x" src="https://user-images.githubusercontent.com/7773454/230722340-a65029ed-b2f7-4378-b104-64c00a77b8b0.png">

**Comment by jonnicholson94** [comment]
Also having same issue as above ^

**Comment by jonnicholson94** [comment]
> Same issue here. I found that everything works when downgrading to next@13.2.4

Tried that, didn't work for me

**Comment by silentworks** [comment]
The `fs` issue was fixed in the latest version of auth-helpers-nextjs. You can see a duplicate issue with a reproducible that was created by someone on the NextJS team that got fixed https://github.com/supabase/auth-helpers/issues/493.
