### ISSUE TITLE
Service role key for createServerComponentSupabaseClient isn't working

### ISSUE THREAD

**Issue by solsonl** [supabase/auth-helpers#480]
I am trying to use
`export const createServerClient = () =>
  createServerComponentSupabaseClient({
    supabaseUrl: "my sb url;
    supabaseKey: "sb service role key";
    headers,
    cookies,
  });`

But seems like sb client created by this function still use anon key, so that I got Postgresql permission issue.
Does anyone get the same issue? Any solution to work around?

**Comment by thorwebdev** [comment]
Actually, reopening to track that we need to improve the docs around this, as this seems to come up every once in a while.

**Comment by silentworks** [comment]
I've opened a PR with documentation for this https://github.com/supabase/supabase/pull/15806, I will close this ticket out once the PR has been merged.

**Comment by silentworks** [comment]
This has now been documented in the Troubleshooting section of our GitHub Discussions. https://github.com/orgs/supabase/discussions/15860
