### ISSUE TITLE
createServerComponentSupabaseClient doesn't work correctly on server side

### ISSUE THREAD

**Issue by deleau-victor** [supabase/auth-helpers#499]
## Describe the bug

When I try to use the auth-helper to make server side fetching with the new nextJS app directory it return me an error when i use the createServerComponentSupabaseClient helper on server side. Which is attempt to do not cause error on server side, you can view this error below :

error - Error: Attempted to call createServerComponentSupabaseClient() from the server but createServerComponentSupabaseClient is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.

## To Reproduce

1. Create a project with NextJS app dir and supabase auth helper
2. Try to fetch data on server side with the createServerComponentSupabaseClient() method

## Expected behavior

It musn't return error that say the function is on client side.

## Screenshots

<img width="1440" alt="Capture d’écran 2023-04-11 à 16 27 46" src="https://user-images.githubusercontent.com/112159305/231195829-377b99c2-8979-4edf-85e5-dcefb78fd5a8.png">

## System information

- OS: macOS & Windows
- Browser: Chrome & Mozilla Firefox
- Version of supabase-js: 2.7.1
- Version of auth-helpers-nextjs: 0.5.4
- Version of next JS: 13.3.0
- Version of Node.js: LTS Hydrogen (v18.15.0)

**Comment by silentworks** [comment]
Please upgrade to the latest auth-helpers-nextjs and also follow the guide for usage with app directory https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components.

**Comment by silentworks** [comment]
Can't replicate and no follow up has happened.
