### ISSUE TITLE
Helpers do not seem to work in NextJS 13.3

### ISSUE THREAD

**Issue by anargiris** [supabase/auth-helpers#509]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I tried to setup an app with NextJS 13.3 and Supabase using the app router. I tried to implement Auth using the official example that can be found here:
https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Setup a project using NextJS and install the Supabase library.
2. Follow the steps documented on the official example, linked above

## Expected behavior

App should be up and running with Auth like in the example

## Screenshots
![image](https://user-images.githubusercontent.com/73837702/231509138-1ef63ff1-274c-4604-85d6-fa9b44efefbf.png)

![image](https://user-images.githubusercontent.com/73837702/231509274-eaee6497-a1f6-4a9d-8bf3-cf25188408f8.png)

## System information

- OS: Windows
- Browser: Google Chrome
- Version of supabase-js: "@supabase/auth-helpers-nextjs": "^0.6.0",
    "@supabase/supabase-js": "^2.15.0",
- Version of Node.js:v16.17.0

## Additional context
I think this issue should be pretty straight forward since I didn't add any customizations to the app yet and wanted to start fresh with the example provided in the docs but ran into the error.

**Comment by londonadagio** [comment]
For what it's worth, there seem to be a bug in NextJS itself, as upgrading to 13.3.1-canary.4 (or 5 now) fixes this specific issue.

However I'm facing other issues with the auth helpers, so there might be more bugs to dig up.

**Comment by silentworks** [comment]
Please provide a reproducible example repo of the issue as this isn't something we have seen or have been able to replicate. We are using auth-helpers-nextjs inside the examples in this repo and haven't hit this issue.

**Comment by anargiris** [comment]
Here is the repo I am having the issue with. I have commented out the context provider in the app layout file. There is nothing else other than the simple implementation of the docs (excluding some simple elements on the home page).

https://github.com/anargiris/health-app

**Comment by i-am-the-slime** [comment]
> Please provide a reproducible example repo of the issue as this isn't something we have seen or have been able to replicate. We are using auth-helpers-nextjs inside the examples in this repo and haven't hit this issue.

One example uses NextJS 12 and the other `13.0`. This problem only occurs from `13.3` onwards.

**Comment by silentworks** [comment]
@anargiris I can't seem to view that repo, maybe it is a private repo as GitHub is giving me a 404 Page not found error when I click the link.

**Comment by anargiris** [comment]
Just to let you know, in the end this wasn't a problem with Supabase but a problem with NextJS. Part of it is documented on this issue:

https://github.com/vercel/next.js/issues/48070

In the end, upgrading the NextJS version solved the issue.

**Comment by silentworks** [comment]
@anargiris thank you for the update on this issue. Also happy to hear you got it resolved.
