### ISSUE TITLE
type error in auth data object

### ISSUE THREAD

**Issue by bessim-dev** [supabase/auth-helpers#520]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

if a user enters a password less than 6 characters and this is not handled by the frontend, Supabase will not have the error in the error object but rather in the data object and if you try to get access to the code and msg properties typescript will yell.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. create a route file in Nextjs to handle registration
2. create a supabase routehandle instance with the **createRouteHandlerSupabaseClient**
3. setup signup function with a password less than 6 characters

## Expected behavior

i expect all errors to be in the error object or at least for now add correct types to the data object.

**Comment by silentworks** [comment]
I cannot replicate this, the error is returned in the error property. All the auth methods return an object with two properties a `data` and `error` property. You might not be destructuring them hence why you think the error is returning in the data property. This is normally how the properties are accessed:

```js
const { data, error } = await supabase.auth.signUp({
    email: "hello@example.com",
    password: "pass",
});
```
