### ISSUE TITLE
[NextJS] Error fetching data from a Server Component

### ISSUE THREAD

**Issue by zzev** [supabase/auth-helpers#525]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I’m trying to set up Supabase authentication in a multi-tenant NextJS 13 app with experimental appDir enabled, based on [this example](https://github.com/vercel/platforms/blob/main/middleware.ts) and [this one](https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components#configure-middleware).

However, when trying to fetch data from the server, it fails with the following error:

```
{
  error: {
    message: 'TypeError: fetch failed',
    details: 'TypeError: fetch failed\n' +
      '    at Object.fetch (node:internal/deps/undici/undici:11457:11)\n' +
      '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)',
    hint: '',
    code: ''
  },
  data: null,
  count: null,
  status: 0,
  statusText: ''
}
```

[A post in the Discussions section](https://github.com/orgs/supabase/discussions/13989) is also available, with a little more information.

## To Reproduce

I've created a repo with minimum configuration to reproduce the issue.

1. Clone [the repo](https://github.com/zzev/nextjs-supabase/tree/main).
2. Copy `.env.local.example` to `.env.local` and fill the values.
3. Since it is using GitHub login, point a GitHub app to [http://app.localhost:3000](http://app.localhost:3000).
4. Execute the app with `npm run dev`.
5. Go to [app.localhost:3000/login](http://app.localhost:3000/login).
6. Perform login.
7. If session is present, then [app.localhost:3000](http://app.localhost:3000) will try to fetch data from the server and will raise the error, so it will be seen in the console.

## Expected behavior

Info from Supabase being returned.

## System information

- OS: macOS
- Version of Node.js: 20.0.0
- @supabase/auth-helpers-nextjs: ^0.6.1
- @supabase/auth-helpers-react: ^0.3.1
- @supabase/supabase-js: ^2.21.0

**Comment by zzev** [comment]
Had a complex setup based on self hosted configuration. I made it work changing the urls for the server helper method.

**Comment by joaopedrosdmm** [comment]
Can you provide more context to your resolution? I'm having the same problem
