### ISSUE TITLE
SupabaseClientOptionsWithoutAuth should still include auth

### ISSUE THREAD

**Issue by TannerHolladay** [supabase/auth-helpers#528]
# Bug report

## Describe the bug

There are some options in auth that I'm wanting to use like "detectSessionInUrl", but can't because the auth option has been removed. I'm having to create the client, cast to an any type to set the properties to get around this.

## To Reproduce

1. Use one of the auth-helpers functions with SupabaseClientOptionsWithoutAuth
2. The "auth" property does not exist.

## Expected behavior

Auth property should either be re-added or the important properties should be exposed.

## System information

- OS: N/A
- Version of supabase-js: 2.20.0
- Version of Node.js: N/A

## Additional context

- @supabase/auth-helpers-react: 0.3.1
- @supabase/auth-helpers-nextjs: 0.6.0

**Comment by j4w8n** [comment]
In the browser client, you need `detectSessionInUrl` to be `true` in order to grab the session info after a login. In a server client, it makes no sense to have it be `true` because there's no browser to grab url info from.

What's your use case for wanting to tweak the settings?

**Comment by silentworks** [comment]
Not planned as this is an opinionated library with sane defaults for the server-side rendering (SSR) environment.
