### ISSUE TITLE
Sveltekit + Supabase +  Netlify Edge Functions - site fails on deploy but works fine(ish) locally

### ISSUE THREAD

**Issue by sortofsleepy** [supabase/auth-helpers#529]
I've already asked on the Netlify support forum. Unfortunately I'm only on a free tier so I figured I'd post here too since as far as I can tell, the Supabase/SvelteKit integration is the cause of the issue.

# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. (though I'm not entirely sure to be honest)
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

It's a little bit of a weird one that I haven't found any documentation on. Basically, if edge functions are enabled, a 500 error gets thrown when running the deployed site due to, as far as I can tell, the Supabase helper trying to access the `document` variable while running the server code of the SvelteKit app. 

The exact error from Netlify is : 
```
Apr 28, 09:38:13 AM: error  [render] ReferenceError: document is not defined
    at Object.getItem (file:///root/.netlify/edge-functions/render.js:8118:46)
    at file:///root/.netlify/edge-functions/render.js:4790:36
    at Generator.next (<anonymous>)
    at file:///root/.netlify/edge-functions/render.js:4736:71
    at new Promise (<anonymous>)
    at __awaiter10 (file:///root/.netlify/edge-functions/render.js:4718:14)
    at getItemAsync (file:///root/.netlify/edge-functions/render.js:4789:39)
    at SupabaseAuthClient.<anonymous> (file:///root/.netlify/edge-functions/render.js:5944:40)
    at Generator.next (<anonymous>)
    at fulfilled (file:///root/.netlify/edge-functions/render.js:5462:28)
```

Which seems to point here
```
 ...const sessionStr = export_parseCookies(document.cookie)[name];
```
which looks like it's part of a function called `supabaseAuthStorageAdapterSveltekitLoad`. After a bit of testing, it seems like everything is originating from the `createSupabaseLoadClient` function call described in the tutorial(see below).

The really weird part is that everything works fine locally. Things still work fine if I try running a dev server with Netlify's cli tool(yes I made sure to visit the url pointing to the server that is supposed to mimic a deployed setup). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

~~- Set up a Supabase table, grab the api url and anon key , plug that into a .env file with the keynames~~
  ~~- PUBLIC_SUPA_URL - for the api url~~
  ~~- PUBLIC_SUPA_KEY - for the api key~~
  ~~- See tutorial for where those things are.~~
(updated repo with embeded key and url)
  
- Install Netlify's CLI - `npm netlify-cli --save-dev`
- Run `build` (in npm). This is important cause otherwise the behavior will end up being similar to just running the dev server.
- Run `npx netlify dev` to start the Netlify cli.
- The server mimicking a deployed Netlify setup should be running @ `http://localhost:8888/`
- When you visit `http://localhost:8888/` you should hit an http `500`

I've set up a test repo here https://gitlab.com/xoio/supa-netlify-testing

## Expected behavior

Site should load normally. 

## System information

- OS: Windows 10 
- Browser : All
- Version of supabase-js: 2.21.0
- Version of @supabase/auth-helpers-sveltekit : 0.9.4
- Version of Node.js: 18.14.0

---

While edge functions ultimately aren't important for me in this particular situation, this looks like a bug. If it's not, then at the very least, it'd be great to understand what I have to do in the future if I ever make a similar app. 

Thanks! 🍻

**Comment by sortofsleepy** [comment]
Just to add to this - after a little more testing just now I notice I'm seeing some unexpected behavior with how the SvelteKit adapter generates edge functions which may a factor, will file a bug with them as well.

**Comment by sortofsleepy** [comment]
to amend this - I think I figured out why things seemed to work locally, namely that I must not have built my app prior to starting the Netlify CLI, which is a little weird but likely why I thought things were ok.

**Comment by silentworks** [comment]
A `+layout.js` is called on both the client and the server, in this instance we need the document object in order to get the cookie on the client side, since Netlify uses a Deno based edge runtime which probably doesn't have the document object this error will occur. You can remove the `+layout.ts` and your project should build and work, you will need to perform all supabase interactions on the server side using `+layout.server.js`, `+page.server.js` or `+server.js`.
