### ISSUE TITLE
Form Actions Cause cookies.set error in SvelteKit

### ISSUE THREAD

**Issue by jdgamble555** [supabase/auth-helpers#534]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [ ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The app breaks when trying to update a form action item in supabase.

## To Reproduce

I installed `auth-helpers-sveltekit` with no problems, works in other modules with session correctly.

## Expected behavior

I simply add a form action like so:

**+page.server.ts**
```ts
export const actions = {

  updateProfile: async ({ locals: { supabase } }) => {

    supabase.auth.updateUser({ data: {
      full_name: 'some name here'
    }});

  }

} satisfies Actions;
```
**+page.svelte**
```html
<form method="POST" action="?/updateProfile">
  <button type="submit">Update</button>
</form>
```

## System information

- OS: Windows 11
- Browser Chrome
- Version of supabase-js: 2.21
- Version of auth-helpers-sveltekit: 0.9.4
- Version of Node.js: 18.13

```
/node_modules/@sveltejs/kit/src/runtime/server/respond.js:425
                                throw new Error('Cannot use `cookies.set(...)` after the response has been generated');
                                      ^

Error: Cannot use `cookies.set(...)` after the response has been generated
    at event.cookies.set (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:425:11)
    at Object.setItem (file:///C:/web%20projects/code-build-new/node_modules/@supabase/auth-helpers-sveltekit/dist/index.js:152:15)
    at C:\web projects\code-build-new\node_modules\@supabase\gotrue-js\dist\main\lib\helpers.js:128:19
    at Generator.next (<anonymous>)
    at C:\web projects\code-build-new\node_modules\@supabase\gotrue-js\dist\main\lib\helpers.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (C:\web projects\code-build-new\node_modules\@supabase\gotrue-js\dist\main\lib\helpers.js:27:12)
    at setItemAsync (C:\web projects\code-build-new\node_modules\@supabase\gotrue-js\dist\main\lib\helpers.js:127:46)
    at SupabaseAuthClient._persistSession (C:\web projects\code-build-new\node_modules\@supabase\gotrue-js\dist\main\GoTrueClient.js:1058:43)
    at SupabaseAuthClient.<anonymous> (C:\web projects\code-build-new\node_modules\@supabase\gotrue-js\dist\main\GoTrueClient.js:1053:28)
```

Related to https://github.com/supabase/auth-helpers/issues/466

J

**Comment by silentworks** [comment]
You will need to produce a minimal reproducible example of this as I have this working in multiple apps without this issue. You can have a look at one here https://github.com/supabase-community/supabase-by-example/blob/main/user-profile/sveltekit/src/routes/(app)/account/update-email/%2Bpage.server.ts

**Comment by david-plugge** [comment]
You need to await the call so sveltekit waits before generating a response.

```ts
export const actions = {

  updateProfile: async ({ locals: { supabase } }) => {

    await supabase.auth.updateUser({ data: {
      full_name: 'some name here'
    }});

  }

} satisfies Actions;
```

**Comment by jdgamble555** [comment]
Yup, it was not having await that was the problem. Thanks guys.
