### ISSUE TITLE
After authentication with Google, redirect has access token, earlier it used to be just my redirect url.

### ISSUE THREAD

**Issue by roker15** [supabase/auth-helpers#535]
After authentication ,  (**I am using nextjs 13.4 with app directory & @supabase/auth-helpers-nextjs package**) i get URL like this - `http://www.localhost:3000/#access_token=eyJhbGciOiJIUzI1NiIsIn.......` but i am expecting just `http://www.localhost:3000/` as it used to be earlier.. 
Earlier i used to get just redirect url, which was provided during authentication...

```
const signInWithgoogle = async (redirect1: string) => {
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: "google",
      options: {
        redirectTo: redirect1,
      },
    });
  };
```

**Comment by silentworks** [comment]
This is not a bug, if you have auth-helpers setup correctly the `#access_token` would be removed from the URL on redirect. You can see this working in the `next-server-component` example in this repo.

**Comment by roker15** [comment]
> `#access_token` would be removed from the URL on redirect.

I followed same example in repo, but access token is still there. And it is causing due to triggering of   `router.refresh()` inside Supabase Provider, when` onAuthStateChange()` is triggered. 

```
useEffect(() => {
    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange(async (e) => {
  router.refresh()
      
    });
```
