### ISSUE TITLE
nextjs, createMiddlewareSupabaseClient does not auto refresh access token due to `autoRefreshToken:false` in shared server client

### ISSUE THREAD

**Issue by michael-land** [supabase/auth-helpers#539]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The [docs](https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components#configure-middleware) mentions that

> Supabase needs to be able to set cookies and headers to refresh expired access tokens. Therefore, you must call the getSession function in middleware.js in order to use a Supabase client in Server Components or Route Handlers.

it does not work as described.

The `next/createMiddlewareSupabaseClient` is an extension of `shared/createMiddlewareSupabaseClient`. The latter sets autoRefreshToken to false, as seen here: https://github.com/supabase/auth-helpers/blob/main/packages/shared/src/supabase-server.ts#LL49C7-L49C23.

However, the GoTrueClient only refreshes/renews tokens when autoRefreshToken is true and the token will expire within a certain margin (default 10 seconds). This can be observed in the following code snippet: https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L1207-L1217. because autoRefreshToken is false, whenever token expire happen in middleware, it remove token from cookie, which cause a force logout.

note that this issue only occurs when the value of expired_at is between 0 and 10 (due to this check `if ((currentSession.expires_at ?? Infinity) < timeNow + EXPIRY_MARGIN)` https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L1207).  

Additionally, I believe there may be another issue with the GoTrueClient in which the access token is always refreshed upon expiration, regardless of the autoRefreshToken setting. This can be found in the following link: https://github.com/supabase/gotrue-js/issues/677.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. change jwt_expiry to 10 seconds
2. signin
3. refresh the page before token expired.

the above reproduce is based on supabase nextjs appdir example

## Expected behavior

auto refresh access token in nextjs middleware

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by michael-land** [comment]
https://github.com/supabase/auth-helpers/assets/33362998/c695ca21-c93c-4cb5-baad-ba75b92a06f2

To make the video short, in this example, I set `jwt_expiry = 10`, it will refresh on next `getSession()` invoke

**Comment by david-plugge** [comment]
Every time the supabase client uses the session to make a call to the supabase api it calls `getSession` internally which refreshes the session when it´s expired. We explicitly disable `autoRefreshToken` as it uses `setTimeout` which could result in unexpected behaviour (the server already sent the response but the timeout fires and tries to refresh the session after the response is generated).
https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L667

An expiry of 10 seconds is unrealistic. Can you verify if the issue persists when the expiration period is increased to 3 minutes? If it does, please provide a minimal reproduction.

**Comment by michael-land** [comment]
the issue sill exist with jwt-expiry set to 180.

The problem seems to be with the _initialize function of the GoTrueClient, which is located in the GoTrueClient.ts file. On line 244 of this file, there is a call to `_recoverAndRefresh`. 

The following block of code is executed when the expiration time is less than 10 seconds.

https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#LL1207C1-L1223C8

```ts
      // when token expired is less than 10
      if ((currentSession.expires_at ?? Infinity) < timeNow + EXPIRY_MARGIN) {
        if (this.autoRefreshToken && currentSession.refresh_token) {
          const { error } = await this._callRefreshToken(currentSession.refresh_token)

          if (error) {
            console.log(error.message)
            await this._removeSession()
          }
        } else {
          // because autoRefreshToken is false on server side, the token will be delete.
          await this._removeSession()
        }
      } else {
        if (this.persistSession) {
          await this._saveSession(currentSession)
        }
        this._notifyAllSubscribers('SIGNED_IN', currentSession)
      }

```

**Comment by michael-land** [comment]
here is the minimal reproduction repo

https://github.com/michael-land/supabase-issue-539

1. npx supabase start
2. localhost:3000
3. signup
4. wait 5-10 seconds and refresh page

**Comment by michael-land** [comment]
> An expiry of 10 seconds is unrealistic

I understand that it may seem unlikely, but I did spend some time attempting to replicate the issue of my cookie token being deleted unpredictably.

**Comment by michael-land** [comment]
> We explicitly disable autoRefreshToken as it uses setTimeout which could result in unexpected behaviour

It makes sense. Then this issue might be only related to `gotrue` repo

**Comment by j4w8n** [comment]
> > An expiry of 10 seconds is unrealistic
> 
> I understand that it may seem unlikely, but I did spend some time attempting to replicate the issue of my cookie token being deleted unpredictably.
> 
> the potential fix could be
> 
> During the `getSession` process, when verify if the token has expired by taking into account the `EXPIRY_MARGIN`, similar to how it is implemented in the `_recoverAndRefresh` method.
> 
> 
>  from this 
> ```ts
>     const hasExpired = currentSession.expires_at
>       ? currentSession.expires_at <= Date.now() / 1000
>       : false
> ```
> to this
> ```ts
>     const hasExpired = currentSession.expires_at
>       ? currentSession.expires_at <= Math.round(Date.now() / 1000) + EXPIRY_MARGIN
>       : false
> ```

This proposed code has caused other issues in the past, and has had to be reverted.

**Comment by j4w8n** [comment]
> > An expiry of 10 seconds is unrealistic
> 
> I understand that it may seem unlikely, but I did spend some time attempting to replicate the issue of my cookie token being deleted unpredictably.
> 
> the potential fix could be
> 
> During the `getSession` process, when verify if the token has expired by taking into account the `EXPIRY_MARGIN`, similar to how it is implemented in the `_recoverAndRefresh` method.
> 
> 
>  from this 
> ```ts
>     const hasExpired = currentSession.expires_at
>       ? currentSession.expires_at <= Date.now() / 1000
>       : false
> ```
> to this
> ```ts
>     const hasExpired = currentSession.expires_at
>       ? currentSession.expires_at <= Math.round(Date.now() / 1000) + EXPIRY_MARGIN
>       : false
> ```

This proposed code has caused other issues in the past and has had to be reverted.

**Comment by silentworks** [comment]
I've upped the time to 180 instead of 30 and tested this and can't replicate this issue.
