### ISSUE TITLE
session and SupabaseListener not defined

### ISSUE THREAD

**Issue by IoriBranford** [supabase/auth-helpers#546]
# Improve documentation

## Link 

[Supabase Auth with Next.js app directory - Supabase Provider](https://supabase.com/docs/guides/auth/auth-helpers/nextjs-server-components#supabase-provider)

## Describe the problem

The code for `app/layout.*sx` does not define `session` or `SupabaseListener`.

## Describe the improvement

Add definitions for `session` and `SupabaseListener`, or specify any prerequisite tutorials.

**Comment by silentworks** [comment]
A PR has already been opened for this on the supabase/supabase repo https://github.com/supabase/supabase/pull/14424
