### ISSUE TITLE
PKCE error: invalid flow state, no valid flow state found

### ISSUE THREAD

**Issue by KrisBraun** [supabase/auth-helpers#549]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Using the [PKCE auth flow](https://supabase.com/docs/guides/auth/server-side-rendering), `await supabase.auth.exchangeCodeForSession(code)` produces the following error:

```
AuthApiError: invalid flow state, no valid flow state found
```

Inspecting the DB and the [gotrue source](https://github.com/supabase/gotrue/blob/2b8ba6782f9fdb01afdda7ba42eeffb63c0f808a/internal/api/token.go#L599), I can see this is because `user_id` is `NULL` in the `flow_state` table.

## To Reproduce

```
// root.tsx

import {
  createBrowserClient,
  createServerClient,
} from "@supabase/auth-helpers-remix";

...

export default function App() {
  const [supabase] = useState(() =>
    createBrowserClient<Database>(env.SUPABASE_URL, env.SUPABASE_ANON_KEY, {
      auth: { flowType: "pkce" },
    })
  );
  ...
}
```

```
// login.tsx

import { useOutletContext } from "@remix-run/react";
import { SupabaseOutletContext } from "../root";

export default function Login() {
  const { supabase, user } = useOutletContext<SupabaseOutletContext>();

  const signInWithGoogle = async () => {
    await supabase.auth.signInWithOAuth({
      provider: "google",
      options: {
        scopes: [
          "https://www.googleapis.com/auth/calendar.readonly",
          "https://www.googleapis.com/auth/calendar.events.readonly",
        ].join(" "),
        queryParams: {
          access_type: "offline",
          prompt: "consent select_account",
          redirect_uri: `${location.origin}/login/callback`,
        },
      },
    });
  };

  async function signInWithAzure() {
    await supabase.auth.signInWithOAuth({
      provider: "azure",
      options: {
        scopes: [
          "openid",
          "email",
          "user.read",
          "calendars.read",
          "offline_access",
        ].join(" "),
      },
    });
  }

  const logout = async () => {
    await supabase.auth.signOut();
  };

  return (
    <>
      {!user && <button onClick={signInWithGoogle}>Google Login</button>}
      {!user && <button onClick={signInWithAzure}>Outlook Login</button>}
      {user && <button onClick={logout}>Logout</button>}
    </>
  );
}
```

```
// login.callback.tsx

import type { LoaderArgs } from "@remix-run/cloudflare";
import { redirect } from "@remix-run/cloudflare";

import { createServerClient } from "@supabase/auth-helpers-remix";

export const loader = async ({ context, request }: LoaderArgs) => {
  const env = {
    SUPABASE_URL: context.SUPABASE_URL! as string,
    SUPABASE_ANON_KEY: context.SUPABASE_ANON_KEY! as string,
  };

  const response = new Response();

  const url = new URL(request.url);
  const code = url.searchParams.get("code");
  if (typeof code !== "string") return redirect("/login");

  // exchange the auth code for user session
  const supabase = createServerClient(env.SUPABASE_URL, env.SUPABASE_ANON_KEY, {
    request,
    response,
  });
  const { data } = await supabase.auth.exchangeCodeForSession(code);

  return redirect("/", {
    status: 303,
    headers: response.headers,
  });
};
```

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to `/login`, click `Google Login`
2. Go through Google OAuth flow
3. When redirected to `/login/callback`, the follow error is displayed:

```
Unexpected Server Error

AuthApiError: invalid flow state, no valid flow state found
```

## Expected behavior

As mentioned above, inspecting the DB and the [gotrue source](https://github.com/supabase/gotrue/blob/2b8ba6782f9fdb01afdda7ba42eeffb63c0f808a/internal/api/token.go#L599), I can see this is because `user_id` is `NULL` in the `flow_state` table. It's unclear when this would have been set, since this is the initial login, so no user has been created yet.

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: 2.21.0
- Version of auth-helpers-remix: 0.2.0-next.3
- Version of Node.js: n/a (using Cloudflare)

**Comment by silentworks** [comment]
Ok I've seen the issue in your code, you aren't passing the `redirectTo` url. I think you have confused the Supabase `redirectTo` url with the Google `redirect_uri` which are two different things.

```ts
await supabase.auth.signInWithOAuth({
  provider: "google",
  options: {
    redirectTo: `${location.origin}/login/callback`, // this is what you should have had in there
    scopes: [
      "https://www.googleapis.com/auth/calendar.readonly",
      "https://www.googleapis.com/auth/calendar.events.readonly",
    ].join(" "),
    queryParams: {
      access_type: "offline",
      prompt: "consent select_account",
    },
  },
});
```
Also you have some redundant code, since we are using the auth-helpers the PKCE flow is already set for you and you can't actually set `auth` properties of the `createBrowserClient` function. So you can remove the `flowType` stuff from the `createBrowserClient`.

```ts
createBrowserClient<Database>(env.SUPABASE_URL, env.SUPABASE_ANON_KEY)
```

**Comment by KrisBraun** [comment]
@silentworks You're absolutely right! I had though I needed the provider to redirect directly to my endpoint. With that change, this works beautifully. I'm incredibly grateful for your help!

**Comment by kei2e** [comment]
I initially asked [this](https://github.com/orgs/supabase/discussions/16743#discussion-5550943) in the discussions, since I was not certain it was a problem with my setting or a bug. Today I tried reproducing the "User Management App with NextJS" example on my office computer, and I get the exact same error:

```
"AuthApiError: invalid flow state, no valid flow state found"
```

Any idea why I am getting this error?

**Comment by SMUEric1127** [comment]
@kei2e hey I don't know if you have resolved it yet, but if anyone still facing this issue, I just go ahead and remove magic link (Use the default auth ui form), this still send the magic link but it just for verify your email and you would still need a password. This worked for me when I follow the "User Management App with Next JS"

(Please love the comment if it useful, thank you!)

**Comment by andychase** [comment]
I struggled with this for a while but I identified the issue.

I have two urls, the self-hosted supabase (call it https://supabase) and my app (https://myapp). https://supabase is what goes in the NEXT_PUBLIC_SUPABASE_URL environment variable for example.

From the documentation it sounded like I needed to put in github and match in my code this url:

https://myapp/auth/callback

But it turns out I needed to use this url instead:

https://supabase/auth/v1/callback

For github at least, the redirect uri and the callback url needed to be the same or else I got an error.
