### ISSUE TITLE
Cannot disable `detectSessionInUrl` in `createSupabaseLoadClient()`

### ISSUE THREAD

**Issue by probablykasper** [supabase/auth-helpers#553]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The SvelteKit `createSupabaseLoadClient()` function is missing the `auth.detectSessionInUrl` option that the normal Supabase client has. I want to disable it to make sure login is only possible through server-side PKCE.

## Expected behavior

The ability to set the `detectSessionInUrl` option

## System information

- OS: macOS
- Version of supabase-js: 2.22.0
- Version of Node.js: 18.14.2

**Comment by silentworks** [comment]
This is an opinionated library and the auth configuration is not exposed as we provide sane defaults in the environment that the library works in. If you need to do custom stuff then you should just use the `@supabase/supabase-js` and handle all the setup from there.

**Comment by probablykasper** [comment]
I agree it's a sane default, `@supabase/supabase-js` does the same. I'm not suggesting to change the default, sorry if that was unclear. Was hoping to rely on the PKCE that the auth helpers provide

**Comment by probablykasper** [comment]
I do use PKCE through the `next` branch (my bad for not mentioning, could be worth updating the issue template)

What I'd like is to make sure that only server-side PKCE can happen, so that:
1. I can run important server-side code when users log in
2. I will know when I've introduced a bug by pointing to the wrong redirect_url. Currently, login would keep working, so I may not notice

I understand that I could implement my own auth using `@supabase/supabase-js`, but it would be really nice if I could pass `detectSessionInUrl` instead

**Comment by silentworks** [comment]
In order to not complicate the library and keep it opinionated we are going to keep the current setup as is. If you need a more custom setup you should use the normal `@supabase/supabase-js` with a cookie storage adapter.
