### ISSUE TITLE
Supabase website and auth-helper documentation shows different way to create ServerComponentClient?

### ISSUE THREAD

**Issue by roker15** [supabase/auth-helpers#561]
**Regarding nextjs App route set up -** 
In supabase website you can create serverclient like this 

`const supabase = createServerComponentClient<Database>({ cookies })`

Here in auth-helper example you can create like this -
`const supabase = createServerComponentClient<Database>({header, cookies })`

**Comment by roker15** [comment]
> The source of truth is what the website says.

Website also not in sync.. In Auth section and Nextjs Section are different.

**Also i m facing a different problem now**, after using google sign in , i am redirecting my page to home and it shows code appended,  `http://www.localhost:3000/?code=b6db7c07-3f0a-496a-83c5-9fc98294297b` earlier it was just used to be `http://www.localhost:3000, `

**if i am not using `router.refresh` inside `onAuthStatechanged()`, everything is fine. but if i am using `router.refresh` inside `onAuthStatechanged()` , after refreshing i see either access_token or code added after my url.**

Also see here - https://github.com/supabase/supabase-js/issues/770

**Comment by ervasive** [comment]
> Also can you point me to the example that you have seen `const supabase = createServerComponentClient<Database>({header, cookies })` in?

https://github.com/supabase/auth-helpers/blob/main/examples/nextjs-server-components/utils/supabase-server.ts

**Comment by 4ortytwo** [comment]
@silentworks would that still be a good pattern to have `'server-only'` in `layout.tsx` +  `Subscriber` and `Listener` or would you recommend a different approach?

**Comment by dijonmusters** [comment]
'server-only' logs an error during the build if server-only code makes it into the client bundle. With the patterns we have in the docs, this is not a concern. What it is really trying to avoid is the client calling a function that relies on something that is only available server-side - an environment variable not prepended with `NEXT_PUBLIC_`, for example. This is not a problem with Supabase anyway, as we recommend you make the URL and AnonKey public values and secure your database with RLS. If you were using your ServiceRoleKey throughout your application, this may be a problem. But again, with the patterns we have in the docs, there is a clear separation between client and server code.

I guess the short answer is, if you have never seen the error printed in the console, you probably haven't hit the point where you need the package 😆 https://nextjs.org/docs/getting-started/react-essentials#keeping-server-only-code-out-of-client-components-poisoning

The Provider and Listener pattern is no longer required as the `createClientSupabaseClient` returns a singleton instance of Supabase. Previously, you needed to ensure a single instance of Supabase was shared across Client Components, so we needed to use Context, Providers and Hooks to ensure it was a single instance. Now you can just call `createClientSupabaseClient` any where you need a Supabase instance in a Client Component:

```
const supabase = createClientSupabaseClient()
```

**Comment by dijonmusters** [comment]
The Next.js and Next.js Pages examples have now been updated, but as @silentworks said, these are used internally for working on the auth helpers themselves. For an example of consuming the Auth Helpers package, check out [this one](https://github.com/supabase/supabase/tree/master/examples/auth/nextjs) 👍
