### ISSUE TITLE
Sveltekit: Can't do signups with email autoconfirm enabled

### ISSUE THREAD

**Issue by julianpoma** [supabase/auth-helpers#562]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

On my project, I have enabled the email provider with email verifications off. 

Following the examples on the [Sveltekit tutorial](https://supabase.com/docs/guides/getting-started/tutorials/with-sveltekit#building-the-app)
```ts
// +page.svelte
<script>
	export let data;

	async function singup() {
		await data.supabase.auth.signUp({
			email: '...',
			password: '...'
		});
	}
</script>
```

 I get the following error:

```
AuthApiError: PKCE flow is not supported on signups with autoconfirm enabled
```

It seems that the flowType is set to 'PKCE' instead of implicit. I cannot override this since the createSupabaseLoadClient() does not expose the auth configurations.

## Expected behavior

PKCE flowType should not be the default.

## Aditional context

Seems that the issue relies on this recent change: https://github.com/supabase/auth-helpers/pull/507/files#diff-6312d77cdcaf977045a7ed00ad8a5adb2503bca98d59ea42b331d083bd0b6cf3R93

The signup process works perfectly if I use my own supabaseClient from the `@supabase/supabase-js`

```ts
const supabase = createClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
	auth: { flowType: 'implicit' }
});

await data.supabase.auth.signUp({
        email: '...',
        password: '...'
});
```

But since these clients have different configurations on how the sessions are stored, my users are not automatically logged in aftert singup, which is something i expect.

## System information

```
"@supabase/auth-helpers-sveltekit": "^0.10.0",
"@supabase/supabase-js": "^2.22.0"
```

**Comment by silentworks** [comment]
If you need implicit flow please use version `0.9.x` and not `0.10.0`. Going forward we are only supporting the `pkce` flow with the auth-helpers.

**Comment by iwasrobbed** [comment]
@silentworks It's not immediately clear how one should do e2e testing—eg using cypress—with PKCE forcing emails to be confirmed now as part of the flow. Am I missing something here?

**Comment by Davidiusdadi** [comment]
The `auth-helpers` only supporting `PKCE` going forward seems to to mean that one has to actually disable `autoconfirm`.
I had it only enabled it for local development, which now seems to no longer be compatible with the `auth-helpers`.
To disable  `autoconfirm` locally set  `enable_confirmations = true` in the supabase `config.toml`.

For my local E2E tests I had to then "actually click the confirmation link":

```js
cy.visit(`http://localhost:54324/monitor`) // the Inbucket URL you get via "supabase status"
cy.get('tbody > tr:first-child').click()
cy.get(".message-body a[href]").contains("Confirm your email address").click()
```
