### ISSUE TITLE
NextJS: can no longer query two different schemas from the client

### ISSUE THREAD

**Issue by grahamorrell** [supabase/auth-helpers#563]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

In my application I used to create two supabase clients in the browser, one for each of two separate Supabase schemas.  For example : 

const publicClient = createBrowserSupabaseClient<...>({supabaseUrl: xxx, supabaseKey: xxx, options: { db: { schema: 'public' } });
const accessClient = createBrowserSupabaseClient<...>({supabaseUrl: xxx, supabaseKey: xxx, options: { db: { schema: 'access' } });

With the latest version, this no longer seems to work.  The new function (createClientComponentClient) now has this code at the bottom of the function : 

```
	// Create the Supabase client once in the client
	if (!supabase) supabase = _supabase;
```

So my second call (which should be returning a client to query the "access" schema is now returning the original client which queries the "public" schema.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a client component that instantiates two supabase clients using createClientComponentClient pointing to two different schemas
2. Use the second client to try and perform a query in the second schema
3. You'll get a 404 because the second client is actually the first client, pointing to the first schema, where your table doesn't exist

## Expected behavior

Clients either shouldn't be cached at this layer at all - let the user application handle that.  Or only cache them per schema.

## System information

- Version of supabase-js: 2.23.0
- Version of auth-helpers-nextjs: 0.7.0

**Comment by dijonmusters** [comment]
Excellent callout! Thanks for opening this issue! 🙌

There is a PR to add a config option to opt out of the singleton pattern for Client Components: https://github.com/supabase/auth-helpers/pull/571

We believe the default should still be a singleton, as this drastically simplifies  getting up and running with Supabase and the Auth Helpers - no need for Context, Providers and Hooks to ensure a single instance of Supabase is shared across Client Components.
