### ISSUE TITLE
[Next.js] Session is null in middleware.

### ISSUE THREAD

**Issue by tronxdev** [supabase/auth-helpers#564]
```
import { createMiddlewareClient } from '@supabase/auth-helpers-nextjs'
import { NextResponse } from 'next/server'

import type { NextRequest } from 'next/server'
import type { Database } from '@/lib/database.types'

export async function middleware(req: NextRequest) {
  const res = NextResponse.next()
  const supabase = createMiddlewareClient<Database>({ req, res })
  const { data: { session } } = await supabase.auth.getSession()
  console.log(session)
  return res
}
```

When the app accepts an invite via magic link, `session` in `middleware.ts` is null.
I simply followed [Supabase Auth with Next.js](https://supabase.com/docs/guides/auth/auth-helpers/nextjs) instructions.

Environments:
- Next.js@13.4.3
- @supabase/auth-helpers-nextjs@0.7.0
- @supabase/supabase-js@2.22.0

**Comment by dijonmusters** [comment]
Thanks for letting us know! Couple of questions to help us work out what’s going on:

1. have you implemented the new [Code Exchange Route](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#code-exchange-route)  - I’m assuming yes, because it’s in the guide you linked
2. Is this when the middleware runs before the /auth/callback route or after you get redirected back to the app?

**Comment by tronxdev** [comment]
1. I applied the new Code Example Route in my project.
2. In Next.js, `middleware.ts` file is located in the root directory and it is fired for every route. So I believe that middleware runs before the `/auth/callback` route. Logs confirmed that middleware was called before the `/auth/callback` route.

**Comment by dijonmusters** [comment]
This is the expected behaviour. The Code Exchange Route receives the ‘code’ as a search param and exchanges it for the users session.  Therefore, the session does not yet exist when the middleware runs for the Code Exchange Route.

**Comment by tronxdev** [comment]
@dijonmusters In `/auth/callback` route, it receives NULL as `code` so that it doesn't generate any session.

**Comment by fuaditrockz** [comment]
i get actually same issue like this.
