### ISSUE TITLE
Needs to reference new createMiddlewareClient function

### ISSUE THREAD

**Issue by scott-wojan** [supabase/auth-helpers#565]
https://github.com/supabase/auth-helpers/blob/6e349e23039942120bf7b81f8e2b40d50f5b2f7b/examples/nextjs/middleware.ts#L9

This is referencing deprecated functionality.

**Comment by dijonmusters** [comment]
Thanks for letting us know. It’s on the list 👍 the one in this repo is used for internal development of the auth helpers and is not always up to date. 

This is the best one to use as a reference: https://github.com/supabase/supabase/tree/master/examples/auth/nextjs
