### ISSUE TITLE
createRouteHandlerClient - Session is null in App Router GET Method

### ISSUE THREAD

**Issue by heyfromapp** [supabase/auth-helpers#566]
# Bug report

## Describe the bug

In NextJS 13 app, using middleware and route handler manage to manage the session and db fetch. In the middleware, I am able to get the session info. But in the GET method and using createRouteHandlerClient is giving session null.

In the same route, POST method is returning the session.

Middleware

```
export async function middleware(req) {
	
	const res = NextResponse.next();
	const supabase = createMiddlewareClient({ req, res });
	const {
		data: { session },
	} = await supabase.auth.getSession();
	// console.log("Middleware User", session);
	return res;
}
```

Api Route with GET and POST method handlers

```
export async function GET(request, params) {

	const supabase = createRouteHandlerClient({ headers, cookies });

	console.log(
		"Whats session uid",
		request.url,
		await supabase.auth.getSession()
	);

      return NextResponse.json({ });
	
}
```

```
export async function POST(request, params) {

	const supabase = createRouteHandlerClient({ headers, cookies });

	console.log(
		"Whats session uid",
		request.url,
		await supabase.auth.getSession()
	);

      return NextResponse.json({ });
	
}
```
	

## Expected behavior

await supabase.auth.getSession() to return session info.

## UPDATE

When I log the URL and session, I noticed that Its a problem for all the API fetch from React server component. In middleware, all the GET methods originate from fetch is having session as null. 

When the page loads and all other chunks and assets fetch's are having session info.

**Comment by Rykuno** [comment]
I second this. The `signup` works but it fails on session refresh and `login`.

**Comment by 0nn0** [comment]
Running into the same issue where session is null in an api route

**Comment by grahamorrell** [comment]
We ran into the same thing, but I'm not sure its an auth-helpers bug.  Looks like if you do a fetch or axios.get/post from a React Server Component the cookies (and hence session) are not automatically set as they would be if running in the browser context.  

We resolved it by manually adding the cookie from the RSC code : 

`
    const { data: myData } = await axios.get(
      `${myURL}`,
      {
        headers: {
          cookie: headers().get('cookie')
        }
      }
    );
`

But I'd be keen to hear if there is a better/cleaner way.

**Comment by silentworks** [comment]
This is not a bug, it's the same as #585 and the solution is noted here by @grahamorrell or if you are using the fetch api you can view the answer on the other issue. https://github.com/supabase/auth-helpers/issues/585#issuecomment-1595195420
