### ISSUE TITLE
Cookies missing in Nextjs with app directory if set or refresh session in middleware

### ISSUE THREAD

**Issue by iMuFeng** [supabase/auth-helpers#575]
# Bug report

- [-] I confirm this is a bug with Supabase, not with my own application. 
- [-] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Cookies missing in Nextjs with app directory if set or refresh session in middleware

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Run `git clone https://github.com/iMuFeng/nextjs-app-cookie`
2. Run `cd nextjs-app-cookie && pnpm i && pnpm dev`
3. Open http://127.0.0.1:3000
4. Create a new cookie named "cookie1" manually in the console with any value (like abc), and then refresh this page.

## Expected behavior

There should display the value of "cookie1"

## Screenshots
![TinySnap-2023-06-03-16 31 02](https://github.com/supabase/auth-helpers/assets/1407009/308b7375-0364-48d6-8daf-90a13bca89a7)
![TinySnap-2023-06-03-16 31 11](https://github.com/supabase/auth-helpers/assets/1407009/8fbeddf5-371f-4ab7-8a0a-1497250006b4)

## System information

- Version of @supabase/auth-helpers-nextjs: 0.7.1
- Version of nextjs: 13.4.4
- Version of Node.js: 20.0.0

## Additional context

Nextjs has a bug where the cookies from the response are parsed by `nextjs/headers` `cookies` instead of those from the request.

```
// Remove this line will help
// https://github.com/supabase/auth-helpers/blob/d33aa1b96b5d1b9684ae7fc50ecd86c24d6c066c/packages/nextjs/src/middlewareClient.ts#L58
res.headers.append('cookie', newSessionStr)
```

**Comment by smalik02** [comment]
Can confirm this is causing issues. Try to set any cookie with next.js api route handler is reset if using the middleware wrapper `createMiddlewareClient`.

**Comment by florianjuengermann** [comment]
Same problem

**Comment by florianjuengermann** [comment]
I fixed it for my use case by manually parsing the header:

```javascript
import { headers } from 'next/headers';

const cookieStr = headers().get('cookie') ?? 'x=0';
const cookies = Object.fromEntries(
  cookieStr.split(';').map((cookie) => {
    const [key, value] = cookie.split('=');
    return [key.trim(), value.trim()];
  })
);
const value = cookies[NAME];
```

**Comment by florianjuengermann** [comment]
Actually, this solution is also not very reliable. Haven't fully figured out when it fails but it does not work reliably either.

**Comment by florianjuengermann** [comment]
I found a potential cause & solution: caching!
The server component is cached and might not show the cookies for that reason. I added
```javascript
export const revalidate = 0;
```

to my server component and now I see the cookie with `next/headers` `cookies()`. Not 100% tested yet though.

**Comment by imownbey** [comment]
I believe these lines will always overwrite all of the cookies sent to the server in the request? https://github.com/supabase/auth-helpers/blob/main/packages/nextjs/src/middlewareClient.ts#L48-L61

**Comment by paddyjoneill** [comment]
Are there any workarounds for this? I'm experiencing this same problem myself, I have a second cookie set but the server never receives it when I'm logged in and have the supabase cookie set. 

If I'm not logged in and don't have the supabase cookie the other cookie reaches the server.

I've tried copying my cookie from the request and then adding it to the response but that doesn't seem to work either.

**Comment by silentworks** [comment]
I'm looking into this now and making the change requested by the OP would cause another issue. The PR that introduced this issue states that cookies won't be available in Server Components on first render if we don't append `cookie`. https://github.com/supabase/auth-helpers/pull/551 I'll look into this a bit more to find a solution that works for both cases.

**Comment by silentworks** [comment]
It would seem that PR was before the Next team had finalized some features with the App router. I'm going to test out removing that line and testing it in a few scenarios. If it doesn't cause any unforseen side-effects then I'll try and get a version out by early next week.

**Comment by silentworks** [comment]
Just to keep you all updated, I'm still looking into this and running some tests.

**Comment by vhpx** [comment]
Any updates on this issue?
