### ISSUE TITLE
[UI] Support phone verification

### ISSUE THREAD

**Issue by ColeTownsend** [supabase/auth-helpers#58]
Relatively similar to the email and magic link workflows, Supabase [supports phone auth](https://supabase.com/docs/guides/auth/auth-twilio). 

<img width="788" alt="image" src="https://user-images.githubusercontent.com/987654/160528629-22bc6137-10b3-4228-96d7-b712c6d6f836.png">

I'd love to see Supabase auth add support for this as it builds out more providers!

Thanks so much for all your work. Truly one of the easiest auth integrations I've ever done.

**Comment by thorwebdev** [comment]
Thanks for the kind words, yes, I think that's a good idea 👍

**Comment by thorwebdev** [comment]
Since auth UI has been pulled out into it's own repo, I've moved this issue here: https://github.com/supabase-community/auth-ui/issues/34
