### ISSUE TITLE
signInWithOAuth doesn't redirect user to OAuth provider when used in nextjs ServerComponents/ServerActions

### ISSUE THREAD

**Issue by gualcasas** [supabase/auth-helpers#580]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If you create a server component or server action with nextjs and try to call `signInWithOAuth`, the user is never redirected to the OAuth provider page to authenticate themselves. Looking at supabase's code:

```ts
  private async _handleProviderSignIn(
    provider: Provider,
    options: {
      redirectTo?: string
      scopes?: string
      queryParams?: { [key: string]: string }
      skipBrowserRedirect?: boolean
    }
  ) {
    const url: string = await this._getUrlForProvider(provider, {
      redirectTo: options.redirectTo,
      scopes: options.scopes,
      queryParams: options.queryParams,
    })
    // try to open on the browser
    if (isBrowser() && !options.skipBrowserRedirect) {
      window.location.assign(url)
    }

    return { data: { provider, url }, error: null }
  }
```

I assume the `isBrowser()` check fails when we run this in a server environment.
If I do in my own function:
```ts
    async function handleDiscordSignIn() {
        "use server";
        const supabase = createServerActionClient({ cookies });
        const { data } = await supabase.auth.signInWithOAuth({
            provider: "discord",
            options: {
                redirectTo: "http://localhost:3000/auth/callback",
            },
        });
        if (data.url) {
            redirect(data.url);
        }
    }
```
the user is redirected, but it took me a bit to get to that conclusion.
I don't know if supabase should handle the redirect if the supabaseClient was created using `createServerActionClient` or if the docs should specify how to handle this case.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## Expected behavior

The user should be redirected to the oauth provider's site to authenticate themselves or the docs should specify how to handle this case.

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by alexcraig043** [comment]
> This is not a bug but more of a documentation issue. We will add this to the documentation, but until then I'll keep this issue open. The redirect can happen in the browser easily because `window` is available to all browsers, however on the server every framework uses a different method of redirecting a user hence why you the developer have to use the method your framework provides to do the redirect.

Has it been added to the documentation? I can't seem to find it.

**Comment by silentworks** [comment]
I've opened a PR with documentation for this https://github.com/supabase/supabase/pull/15806

**Comment by alexcraig043** [comment]
Sweet thank you

**Comment by silentworks** [comment]
This has now been documented in the Troubleshooting section of our GitHub discussions. https://github.com/orgs/supabase/discussions/15862
