### ISSUE TITLE
No storage option exists to persist the session

### ISSUE THREAD

**Issue by joshuabaker** [supabase/auth-helpers#583]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Getting the below warning/error when following current [documentation](https://supabase.com/docs/guides/auth/auth-helpers/nextjs-pages) for the Next.js auth helpers.

> No storage option exists to persist the session, which may result in unexpected behavior when using auth.
> If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.

[Source of error (GoTrueClient.ts#L177-L182)](https://github.com/supabase/gotrue-js/blob/abd33391f00a647bd749adedcd618832a1a1275c/src/GoTrueClient.ts#L177-L182)

Due to the change in how auth codes are handled (server side vs previously being in browser) it’s unclear if sessions are being properly persisted.

## Expected behavior

That the client would handle this for us out of the box.

## System information

- OS: macOS
- Version of supabase-js: 2.4.0
- Version of Node.js: 18

## Additional context

- Same issue resolved for Nuxt: nuxt-modules/supabase#188
- [Gary’s issue report on the GoTrue client](https://github.com/supabase/gotrue-js/issues/539)
- [Discord discussion regarding issue in Nuxt](https://discord.com/channels/839993398554656828/1113542747643715584)

**Comment by magick93** [comment]
I'm also getting this error in Sveltekit.

**Comment by j4w8n** [comment]
What version of the auth helper are you using?

**Comment by joshuabaker** [comment]
```js
"@supabase/auth-helpers-nextjs": "^0.7.2",
"@supabase/auth-helpers-react": "^0.4.0",
"@supabase/supabase-js": "^2.4.0",
```

**Comment by j4w8n** [comment]
Thanks @joshuabaker 

Does the error indicate which part of the code is throwing the error?

What's weird is that `auth-helpers-shared` is designed to detect these things and handle the proper options for you. And they all implement storage, so that's even more confusing.

**Comment by joshuabaker** [comment]
Clearly something isn’t getting passed through to GoTrue somewhere though as that’s where [the error originates from](https://github.com/supabase/gotrue-js/blob/abd33391f00a647bd749adedcd618832a1a1275c/src/GoTrueClient.ts#L177-L182).

The code we have in `/src/pages/api/auth/callback.js` is exactly as shown in [the docs](https://supabase.com/docs/guides/auth/auth-helpers/nextjs-pages#code-exchange-api-route).

```js
import { createPagesServerClient } from "@supabase/auth-helpers-nextjs";

export default async function handler(req, res) {
  const { code } = req.query;

  if (code) {
    const supabase = createPagesServerClient({ req, res });
    await supabase.auth.exchangeCodeForSession(String(code));
  }

  res.redirect("/");
}
```

I can see in the library that an adaptor is [passed by default](https://github.com/supabase/auth-helpers/blob/0d7f9d27acd378a2581a6c0dd555a9b56d73a2a3/packages/nextjs/src/pagesServerClient.ts#L98), but the error is still occurring, which suggests a fault in how this is passed along. I’ve looked but cannot figure out where this is.

It’s possible the error is further upstream if it’s happening in [Sveltekit](https://github.com/supabase/auth-helpers/issues/583#issuecomment-1585146582) as well as, apparently, still an issue in [Nuxt](https://github.com/nuxt-modules/supabase/issues/188#issuecomment-1574675473).

**Comment by j4w8n** [comment]
Can you provide a minimal repo with the issue?

**Comment by j4w8n** [comment]
The Nuxt issue is separate, because it's not tied to the official helper packages. There's a new [PR](https://github.com/nuxt-modules/supabase/pull/194) that will hopefully cleanup the last bit of this for Nuxt.

As for Sveltekit, maybe it's still being affected, but I can't reproduce it; because I just setup a test for that the other day. @magick93 are you experiencing this with the latest versions of the auth helper?

**Comment by jstdk** [comment]
I am getting this error in NodeJS / Typescript since today.

**Comment by j4w8n** [comment]
> I am getting this error in NodeJS / Typescript since today. 

Are you using straight-up node, or some framework with it?

**Comment by jstdk** [comment]
@j4w8n, no frameworks, just NodeJS

**Comment by j4w8n** [comment]
@jstdk I know you're commenting on the auth-helpers repo, but I just need to double-check: you're using an auth-helper, correct?

**Comment by jstdk** [comment]
@j4w8n, sorry, think I'm not. I use Supabase Auth (via supabase-js npm package) on NodeJS and have the same issue.  I guess that is not considered a helper like for Next or SvelteKit. I will highlight the issue with Supabase Auth then.

**Comment by j4w8n** [comment]
@jstdk no need. You simply need to pass in this option to your `createClient` function.

```js
{
  auth: {
    persistSession: false
  
}
```

**Comment by joshuabaker** [comment]
Just to be clear, that will prevent storing the session in the browser, if that’s what’s being used here. If everything is server side disabling that feature is fine.

**Comment by j4w8n** [comment]
@joshuabaker do you have a min repo for your issue?

**Comment by j4w8n** [comment]
> Just to be clear, that will prevent storing the session in the browser, if that’s what’s being used here. If everything is server side disabling that feature is fine.

yep, they're using node so we're good there.

**Comment by j4w8n** [comment]
I'll be pretty busy with the day job today, but if you have a min repo with the issue, I'll test it when I can.

**Comment by silentworks** [comment]
I just tested in my example projects and can't replicate this issue. You can follow the instructions in the readme of this project and let me know if you are seeing the issue https://github.com/supabase-community/supabase-by-example/tree/main/reset-flow/nextjs-pages

**Comment by gragland** [comment]
Seeing this issue after a fresh install of a project that's pinned to `@supabase/supabase-js` `2.7.1`. Looks like there was a breaking change in a dependency somewhere.

**Comment by iwasrobbed** [comment]
fwiw: seeing the same in Next.js after upgrading today:

```
    "@supabase/auth-helpers-nextjs": "^0.7.1",
    "@supabase/auth-helpers-react": "^0.4.0",
    "@supabase/auth-ui-react": "^0.4.2",
    "@supabase/auth-ui-shared": "^0.1.6",
    "@supabase/supabase-js": "^2.25.0",
```

and dev deps

```
    "@types/": "supabase/supabase-js",
    "supabase": "^1.64.8",
```

We're manually creating a couple of server-side auth clients but setting `persistSession: false` on those, but then we're using the convenience auth helpers (e.g. `createClientComponentClient`) and that seems to be where the errors are from

**Comment by silentworks** [comment]
@gragland this repo is about the auth-helpers and your issue would be unrelated as I think you are just using supabase-js on its own as you've mentioned.

**Comment by silentworks** [comment]
@iwasrobbed the auth helpers doesn't need a storage option to be passed to it. The auth helpers are based on a cookie storage option which is passed to it by default. I can't replicate the issue so not able to investigate it. Please provide a minimal reproducible repository with the issue.

**Comment by joshuabaker** [comment]
I’ve found the issue after a fair bit of searching. I can provide a reproduction, but it turns out that importing another client in the request causes this.

```js
import { supabaseAdmin } from "@/lib/supabase.admin";
import { createPagesServerClient } from "@supabase/auth-helpers-nextjs";

export default async function handler(req, res) {
  const supabase = createPagesServerClient({ req, res });

  await supabase.auth.signOut();

  // Custom secured logic using supabaseAdmin client

  res.redirect("/");
}
```

The issue here is that there are occasions where we might want to act as the logged-in user (i.e. the `createPagesServerClient` client) _and_ do something administrative (i.e. with the service key).

**Comment by j4w8n** [comment]
> I’ve found the issue after a fair bit of searching. I can provide a reproduction, but it turns out that importing another client in the request causes this.
> 
> ```js
> import { createClient } from "@supabase/supabase-js";
> import { createPagesServerClient } from "@supabase/auth-helpers-nextjs";
> 
> const supabaseAdmin = createClient(
>   process.env.NEXT_PUBLIC_SUPABASE_URL,
>   process.env.SUPABASE_SERVICE_KEY
> );
> 
> export default async function handler(req, res) {
>   const supabase = createPagesServerClient({ req, res });
> 
>   await supabase.auth.signOut();
> 
>   // Custom secured logic using supabaseAdmin client
> 
>   res.redirect("/");
> }
> ```
> 
> The issue here is that there are occasions where we might want to act as the logged-in user (i.e. the `createPagesServerClient` client) _and_ do something administrative (i.e. with the service key).

Yep, that would cause the warning. Just pass in some auth options to that client, and you'll be good. `persistSession` is the only mandatory one, but I like to set all three on a native server client.

```js
const supabaseAdmin = createClient( process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false
  }
} );
```

**Comment by j4w8n** [comment]
Sometimes I wish there was something like `env: string` as part of these auth options. If you pass `server` then it would set these three options to false for you. But that could lead to more confusion than it's worth.

**Comment by joshuabaker** [comment]
Thanks, @j4w8n. I better understand how that should be working now. Appreciate your weighing in. 🙏🏻 

Tend to agree with your point around complexity too.

I poured over the documentation on this one. Wondering if a warning box or similar might be helpful (“If you’re using only on the server…”) or perhaps adjusting the warning message itself. Clearly a few people falling foul of this as is.

**Comment by iwasrobbed** [comment]
@silentworks fwiw this was happening because we assumed `createClient` would default into persisting sessions (like its code docs say it should) but apparently it wasn't so we switched to using the auth-helpers for all areas of the code

Old code:

```
import { createClient } from '@supabase/supabase-js'

const url = process.env.NEXT_PUBLIC_SUPABASE_URL as string
const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string

export function getSupabaseClient() {
  return createClient(url, key)
}
```

New code:
```
import { createClientComponentClient } from '@supabase/auth-helpers-nextjs'

export const supabaseBrowserClient = () => {
  return createClientComponentClient<Database>()
}
```

**Comment by j4w8n** [comment]
> @silentworks fwiw this was happening because we assumed `createClient` would default into persisting sessions (like its code docs say it should) but apparently it wasn't so we switched to using the auth-helpers for all areas of the code
> 
> Old code:
> 
> ```
> import { createClient } from '@supabase/supabase-js'
> 
> const url = process.env.NEXT_PUBLIC_SUPABASE_URL as string
> const key = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string
> 
> export function getSupabaseClient() {
>   return createClient(url, key)
> }
> ```
> 
> New code:
> ```
> import { createClientComponentClient } from '@supabase/auth-helpers-nextjs'
> 
> export const supabaseBrowserClient = () => {
>   return createClientComponentClient<Database>()
> }
> ```

This may not be well-documented, but persistSession means there should be some kind of storage to persistent the session to. Which isn't usually the case for server-side. With a browser, it uses localStorage by default. Mobile is another beast and usually needs some kind of storage to be passed in.

The auth helpers use custom cookie storage.

**Comment by bradydowling** [comment]
> Mobile is another beast and usually needs some kind of storage to be passed into the supabase client.

For anyone else looking for this for RN, I was struggling to find out what this actually means in practice but the docs ([here](https://supabase.com/docs/reference/javascript/initializing) and then click React Native options on the right) indicate this:

```
import { createClient } from '@supabase/supabase-js'
import AsyncStorage from "@react-native-async-storage/async-storage";

const supabase = createClient("https://xyzcompany.supabase.co", "public-anon-key", {
  auth: {
    storage: AsyncStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false,
  },
});
```

Haven't tried it yet but hopefully it works.

**Comment by TheThirdRace** [comment]
For anyone using the `GoTrueClient` instead of the default `supabase-js` client (bundle size reasons), you can fix this by adding this option when creating the client:

```ts
export const auth = new GoTrueClient({
        ... // your other options
	persistSession: typeof window !== 'undefined'
})
```

The problem happened because I use the same code to create the client on server and in browser. The server part doesn't support storage; thus it displayed the message... see this [commit](https://github.com/supabase/gotrue-js/commit/46640661a9f9771bef6ac6354bea0f576509a6e0)

Until the day where the `supabase-js` client will tree shake the options we're not using (in my case storage and realtime), I beg the Supabase dev team to start thinking about the impacts of their solutions outside the `auth-helpers` 🙏🙏🙏
