### ISSUE TITLE
`useUser` is always `null` on first load

### ISSUE THREAD

**Issue by joshuabaker** [supabase/auth-helpers#586]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

We’re using `useUser` to conditionally display user data. The `initialSession` is passed via server side props to `SessionContextProvider` in the `_app.jsx`, however, the context isn’t correctly passing this value down to the hook.

## To Reproduce

Below is an example of the protected route users are redirected to after logging in. The `initialSession` prop is passed through as expected, however, the `user` value from the hook is `null`.

```jsx
import { createPagesServerClient } from "@supabase/auth-helpers-nextjs";
import { useUser } from "@supabase/auth-helpers-react";

export default function Protected({ initialSession }) {
  const user = useUser();

  return JSON.stringify({
    initialSessionUser: initialSession?.user,
    hookUser: user, // null
  });
}

export async function getServerSideProps(context) {
  const supabase = createPagesServerClient(context);

  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: {
      initialSession: session,
    },
  };
}
```

## Expected behavior

That the `useUser` hook would return `initialSession.user` from the context.

## System information

- OS: macOS
- Version of supabase-js: 2.4.0
- Version of Node.js: 18

**Comment by joshuabaker** [comment]
Similar to #412.

**Comment by joshuabaker** [comment]
### Reproduction
[joshuabaker/supabase-issue](https://github.com/joshuabaker/supabase-issue/tree/ca97a1d7e42cad783cd355f8c4e69ac56f810ad8)

1. Duplicate `.env.example` and populate
2. Install and run
3. Navigate to the `/projected` path

**Comment by dimoFeeld** [comment]
Had the same problem. Apparently you cannot use useUser from react when using the nextjs helpers. You either pick the nextjs helpers or the react library. Basically you need to do your own custom context. 

```
"use client";

import { createContext, useContext, useEffect, useState } from "react";
import { createClientComponentClient } from "@supabase/auth-helpers-nextjs";

const Context = createContext(undefined);

export default function SupabaseProvider({ children, supaSession }) {
  const [supabase] = useState(() => createClientComponentClient());
  const [session, setSession] = useState(supaSession);
  const [user, setUser] = useState(null);
  const [userProfile, setUserProfile] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchUserProfile() {
      let profile = null;
      if (session && session.user) {
        profile = await supabase
          .from("profiles")
          .select("*")
          .eq("id", session.user.id);
      }

      setUser(session?.user ?? null);
      setUserProfile(profile?.data[0] ?? null);
      setLoading(false);
    }

    if (session) {
      fetchUserProfile();
    }

    const {
      data: { subscription: authListener },
    } = supabase.auth.onAuthStateChange(async (event, currentSession) => {
      // Fetch user profile on session change
      let profile = null;
      if (currentSession && currentSession.user) {
        profile = await supabase
          .from("profiles")
          .select("*")
          .eq("id", currentSession.user.id);
      }

      setSession(currentSession);
      setUser(currentSession?.user ?? null);
      setUserProfile(profile?.data[0] ?? null);
      setLoading(false);
    });

    return () => {
      authListener?.unsubscribe();
    };
  }, [supabase]);

  return (
    <Context.Provider value={{ supabase, session, user, userProfile, loading }}>
      <>{children}</>
    </Context.Provider>
  );
}

export const useSupabase = () => {
  const context = useContext(Context);

  if (context === undefined) {
    throw new Error("useSupabase must be used inside SupabaseProvider");
  }

  return context;
};
```

**Comment by joshuabaker** [comment]
Thanks, @dimoFeeld. Long time! Hope you’re good. 😊

The context and hook are exported from `@supabase/auth-helpers-react`. The Next.js helpers just help with constructing the Supabase client, which could come from anywhere.

Checking the code further, I think the issue here is that the context provider is unsetting the session on mount, before it’s had a chance to be populated client side.

https://github.com/supabase/auth-helpers/blob/6e5b5b37dacd07ca74f7486419dda6b10bf14730/packages/react/src/components/SessionContext.tsx#L58-L85

**Comment by joshuabaker** [comment]
This is a design issue.

The `SessionContextProvider` is mounted on the login page, where the `initialSession` will always be `undefined`, so therefore gets passed to the `useState` call as `null`. As that state has been read when it was mounted on the login page, it will always resolve to `null` on subsequent renders.

As an interim fix, we’ve added a `key` prop to the context provider to force a re-render.

```jsx
<SessionContextProvider
  key={pageProps.isLoginPage ? 0 : 1}
  supabaseClient={supabaseClient}
  initialSession={pageProps.initialSession}
>
```

The actual solution here is to refactor how the server-side session is handled in the provider. The server session should not be discarded after the first render.

**Comment by silentworks** [comment]
Thank you once again for this and also for providing an example repo for me to test the issue out, this has been really helpful. A new release 0.4.1 should be out with your fix.
