### ISSUE TITLE
createPagesServerClient is not a function

### ISSUE THREAD

**Issue by vastava** [supabase/auth-helpers#588]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I have copied the example code from the [auth example for nextjs with pages router](https://supabase.com/docs/guides/auth/auth-helpers/nextjs-pages), and am getting the following error when invoking ``createPagesServerClient``.

`TypeError: (0 , _supabase_auth_helpers_nextjs__WEBPACK_IMPORTED_MODULE_7__.createPagesServerClient) is not a function`

I also deleted node modules, and re-ran npm install, but am still seeing the same error. Version info down below

## To Reproduce

This is the shell code of my pages/login.js file, which is basically the same as the example code I linked earlier.

```
import { Auth } from '@supabase/auth-ui-react';
import { useUser, useSupabaseClient } from '@supabase/auth-helpers-react';
import { useEffect, useState } from 'react'
import { createPagesServerClient } from '@supabase/auth-helpers-nextjs';

export default async function LoginPage(props) {
  return (
    <div>some content</div> 
  )
}

export async function getServerSideProps(ctx) {
  // Create authenticated Supabase Client
  const supabase = createPagesServerClient(ctx)
  // Check if we have a session
  const {
    data: { session },
  } = await supabase.auth.getSession()

  if (!session)
  return {
    redirect: {
      destination: '/',
      permanent: false,
    },
  }

  const { data } = await supabase.from('profiles').select('*')

  return {
    props: {
      initialSession: session,
      user: session.user,
      data: data ?? [],
    },
  }
}

```
## Screenshots
<img width="719" alt="Screen Shot 2023-06-17 at 10 37 05 AM" src="https://github.com/supabase/auth-helpers/assets/37812945/0e550740-b773-4489-b225-b86c09350431">

## Version information
    "@supabase/auth-helpers-nextjs": "^0.6.1",
    "@supabase/auth-helpers-react": "^0.3.1",
    "@supabase/auth-ui-react": "^0.3.6",
    "@supabase/auth-ui-shared": "^0.1.4",
    "@supabase/supabase-js": "^2.21.0",

**Comment by jaocfilho** [comment]
The same is happening here too.

I updated to what would be the correct version of the function `createServerComponentClient` and it is working, but I'm getting this error.

```
Cannot find module '@supabase/auth-helpers-nextjs' or its corresponding type declarations.
```

**Comment by silentworks** [comment]
You are using an old version of the library which doesn't have that function. This isn't an issue. The documentation you are referencing uses the latest version of the library which is 0.7.x.
