### ISSUE TITLE
Update `hooks.server.ts` guide now that sveltejs/kit#8061 is closed

### ISSUE THREAD

**Issue by probablykasper** [supabase/auth-helpers#592]
# Chore

## Describe the chore

The SvelteKit auth helpers guide has the following code in `src/hooks.server.ts` for the SupabaseClient setup:

```ts
  return resolve(event, {
    /**
     * There´s an issue with `filterSerializedResponseHeaders` not working when using `sequence`
     *
     * https://github.com/sveltejs/kit/issues/8061
     */
    filterSerializedResponseHeaders(name) {
      return name === 'content-range';
    }
  });
```

https://github.com/sveltejs/kit/issues/8061 was fixed in SvelteKit 1.15.11, so this should probably be updated.

cc @david-plugge

**Comment by madeleineostoja** [comment]
I just tried removing this (I'm on `v1.22.1` of sveltekit) and it still threw what I imagine is the same error it was introduced to fix:

```
{
  message: 'Error: Failed to get response header "content-range" — it must be included by the `filterSerializedResponseHeaders` option: https://kit.svelte.dev/docs/hooks#server-hooks-handle
}
```

Adding back the `filterSerializedResponseHeaders` call fixed the issue

**Comment by david-plugge** [comment]
@madeleineostoja you still need `filterSerializedResponseHeaders` but the comment saying that there is an issue should get removed.

**Comment by silentworks** [comment]
Docs updated.
