### ISSUE TITLE
Delete cookie on signout and check if cookies exist, otherwise don't call supabase api

### ISSUE THREAD

**Issue by Darren120** [supabase/auth-helpers#596]
# Chore

Delete cookie on signout and check if cookies exist, otherwise don't call supabase api

## Describe the chore

Right out signing out doesn't delete the cookie.  Plz delete it, and in the supabase.auth.getSession, checks if cookie exist, otherwise don't get session and just return no session / error

**Comment by silentworks** [comment]
Closing as no example of the issue was shown nor any steps to reproduce it.
