### ISSUE TITLE
Sveltekit: Logout action not applied (?)

### ISSUE THREAD

**Issue by wiesson** [supabase/auth-helpers#599]
https://github.com/supabase/auth-helpers/blob/6e5b5b37dacd07ca74f7486419dda6b10bf14730/examples/sveltekit/src/routes/(app)/%2Blayout.svelte#L11-L15

Can someone explain the code above to me? If we want to logout, the `result.type` is `redirect`, therefore we invalidate the auth. But the line below never gets applied to actually redirect (?)

I guess it should be like this:

```Javascript
if (result.type === 'redirect') {
  await invalidate('supabase:auth');
  await applyAction(result); // Redirect will be executed
}
```

**Comment by silentworks** [comment]
Yes your example code is correct, we will update the one in the repo soon.
