### ISSUE TITLE
createRouteHandlerClient auth-helpers v0.7.2 only works with public schema?

### ISSUE THREAD

**Issue by Jarvisbruder** [supabase/auth-helpers#601]
With the deprecated "createSupabaseRouteHandlerClient" (auth-helpers v0.6.1) it was possible to specify a schema as option like this:

          const supabase = createSupabaseRouteHandlerClient({
            cookies,
            options: {db: { schema: 'private'} } 
          }) 

     const { data, error } = await supabase
     .from('tableName')  
     .select('*')

... but with the latest "createRouteHandlerClient"  (auth-helpers v0.7.2) I get the error "public.tableName" does not exist. It seems that it is not possible to pass a different schema as option anymore.

Is it something that still has to be fixed? thx!
(note: I tried also to call the schema later with << .from("private.tableName") >> but it doesn't work)

**Comment by silentworks** [comment]
Please provide an example code as you did for 0.6.1 for 0.7.2. I don't think this is something we changed in 0.7.2 but need to see your code to understand this better.

**Comment by BorisBarzotto** [comment]
i only can have access with this:
```
  const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{
     db:{schema:"general"}
   })
```
dont know how to specify this with createClientComponentClient, nor createRouteHandlerClient, etc

thx

**Comment by silentworks** [comment]
The auth-helpers interface allows you to select any DB schema you wish to use, but do note that a schema that is not exposed to your API won't work from any supabase client.

```ts
const supabase = createRouteHandlerClient({ cookies: () => cookies() }, {
  options: {
    db: { schema: 'private' }
  }
});
```

You have to use SQL to enable certain grants when using a custom schema, please don't attempt this if you don't understand SQL well enough. https://supabase.com/docs/guides/api/using-custom-schemas
