### ISSUE TITLE
React Native iOS PKCE is not supported on devices without WebCrypto API support, please add polyfills

### ISSUE THREAD

**Issue by ninoM** [supabase/auth-helpers#603]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm trying to use Github login on my react native (expo) app and this code
```js
const { error } = await supabase.auth.signInWithOAuth({
    provider: "github",
});
```
is giving me an `error` saying `Unexpected error from Github SignIn:  [Error: PKCE is not supported on devices without WebCrypto API support, please add polyfills]`

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. In a React Native expo app, import in `@supabase/auth-helpers-react`
2. get `supabase` client from  `useSupabaseClient` from previous import.
3. Try the code above

## Expected behavior

Should not return an error when calling the method using `provider: "github"`

## Screenshots

<img width="827" alt="image" src="https://github.com/supabase/auth-helpers/assets/2021570/ea60eff4-6887-46ec-b10c-2edcc6bcee34">

## System information

- MacOS
- iPhone 14 Pro (on device local test via expo)
- Version of supabase-js: 2.20.0
- Version of @supabase/auth-helpers-react: 0.3.1

**Comment by silentworks** [comment]
This is not a bug, you need to add a polyfill. Also you shouldn't be using auth helpers with React Native, you should just use the normal `@supabase/supabase-js`.

**Comment by kav** [comment]
It's not unreasonable to want to use `SessionContextProvider` or `useUser` for example in React Native. I know that's expanded scope but it's worth considering. I'd love to replace my home grown wrappers with supabase shared code

**Comment by silentworks** [comment]
@kav PRs are welcomed. I'm not familiar enough with React Native to work on this myself.
