### ISSUE TITLE
SvelteKit Auth helper: PKCE flow doesn't work with generateLink (type magiclink)

### ISSUE THREAD

**Issue by peachp** [supabase/auth-helpers#610]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
I migrated from v0.9 to v0.10 following this guide, reviewing my auth code overall, not just the migration part.
https://supabase.com/docs/guides/auth/auth-helpers/sveltekit

but this:
```
const genLink = await supabase.auth.admin.generateLink({
      type: 'magiclink',
      email: email,
      options: {
         redirectTo: '.../callback'
      }
    })
```
doesn't seem to work anymore. 
`genLink.data.properties.action_link` doesn't contain the `code` parameter, which I assume should be present for `exchangeCodeForSession` in the callback server-side code.

What am I doing wrong?

## To Reproduce
1. Generate a magic link with `auth.admin.generateLink` via Supabase JS client with Service Key
2. Sent it via custom email service to the user (we use Postmark)
3. User clicks on the link
4. User is redirected to the `callback` route with `exchangeCodeForSession`
5. `url.searchParams.get('code')` returns nothing

I inspected the generated URL as present in the email sent to the user and it has the correct `redirect_to` parm, but doesn't have the `code` parm.

UPDATE: I also made sure to include this, when creating the client, but no luck:
```
auth: {
    flowType: 'pkce',
  },
```

## Expected behavior
Authenticate user upon clicking on the link directly on the server, as intended by the new PKCE flow.
It was working fine previously with `generateLink` just to be clear.

## System information
- Version of supabase-js: latest
- Version of SvelteKit Auth Helper: v0.10

**Comment by j4w8n** [comment]
Based on what I see in the code, this method doesn't support pcke flow. I don't know if it's planned.

**Comment by nathancahill** [comment]
Running in to this issue as well. Flow is hardcoded to `pcke` in the client and the "url is unsupported"

**Comment by tobiassern** [comment]
Did anyone of you got this to work by updating @supabase/gotrue-js ? I updated it to 2.45.0 but I am still not receiving the code.

**Comment by imbhargav5** [comment]
No I didn’t get it to work either.

**Comment by kamerat** [comment]
For me, using the signInWithOtp works with the callback going to /auth/callback for the `supabase.auth.exchangeCodeForSession()`. 

However, as also described above, when using auth.admin.generateLink as following:

```js
await supabaseAdmin.auth.admin.generateLink({
        type: 'magiclink',
        email,
        options: {
            redirectTo: `${url.origin}/auth/callback`
        }
    })
```

it seems the callback to /auth/callback does not contain any search params. Instead, I get #access_token hash on the url and it still does not trigger onAuthStateChange. - It does not log in the user.

**Comment by MitjaBezensek** [comment]
Also update to the latest version but it still does not work.

**Comment by nathancahill** [comment]
Indeed, same story here.

**Comment by kamerat** [comment]
A temporary workaround is to manually set the user session based on the access token:

```js
const searchParams = new URLSearchParams($page.url.hash.replace('#', '?'))

const { error } = await supabase.auth.setSession({
    access_token: searchParams.get('access_token'),
    refresh_token: searchParams.get('refresh_token')
})
```

However, I'd much more like this to be fixed so it works the intended way.

**Comment by cadmeandev** [comment]
bump!

**Comment by kbsali** [comment]
thanks @kamerat for the work around! I remember doing exactly this "trick" 1.5 years ago with SvelteKit, this time with next.js.

Hope we can get an update soon to fix the issue.

**Comment by silentworks** [comment]
We have published a new guide on how to handle this from the email perspective and framework side of things. Note that this guide does not mention `supabase.auth.admin.generateLink()` but the same setup will still work. Here is a link from the part that you would need to follow https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr#create-api-endpoint-for-handling-tokenhash

**Comment by wyozi** [comment]
Thanks to the guide mentioned by @silentworks, I figured it out and documented the process here: https://catjam.fi/articles/supabase-generatelink-fix

**Comment by vongohren** [comment]
> We have published a new guide on how to handle this from the email perspective and framework side of things. Note that this guide does not mention `supabase.auth.admin.generateLink()` but the same setup will still work. Here is a link from the part that you would need to follow https://supabase.com/docs/guides/auth/server-side/email-based-auth-with-pkce-flow-for-ssr#create-api-endpoint-for-handling-tokenhash

So the documentation points to changing the invitation link to doing something manually. This make sure the endpoint recieves the right data. But documentation says that verifyOtp online needs an option with two fields, but in reality it needs an option with three fields. Depending on the type. If email, it needs the email address itself.

The [blog post](https://catjam.fi/articles/supabase-generatelink-fix) mentioned above does also not work in my case. I tried using the generall strategy to fit for sveltekit but to no luck

The work around did also not work for me as I primarily work on the server side and was hoping to reach the server first

**Comment by silentworks** [comment]
@vongohren I'm not sure what the blog post you linked to contains but my link to the guide is what you should follow. I also have a working example in my waiting-list project which uses SvelteKit and the `verifyOtp` method https://github.com/silentworks/waiting-list/blob/main/src/routes/auth/confirm/%2Bserver.ts#L22

**Comment by vongohren** [comment]
@silentworks thanks for the reply! As for blog post, it was the post above mine by wyozi, that tried to elaborate on what is going on.

As for your code, you are using verifyOtp, without any email or phone value? How is this possible? I get an error? Is it because of my version of the library?

The only different think I do from you is that i generateLink(), type:invite, and take the token hash from there and send as an email through [an i18n email](https://blog.mansueli.com/creating-customized-i18n-ready-authentication-emails-using-supabase-edge-functions-postgresql-and-resend) function.

But that should not make any difference?

What is the expected outcome? The user loads the link, the server verifys and gives user a session so he can access authroized urls right?

**Comment by silentworks** [comment]
Closing this one out as I believe it has been resolved by the link to the guide I posted above.

**Comment by vincentjflorio** [comment]
Thank you @wyozi -- were are still using the /pages router and no server components and were able to adapt your example relatively easily!
