### ISSUE TITLE
useUser not returning created_at property, although type says it does

### ISSUE THREAD

**Issue by adamcohenhillel** [supabase/auth-helpers#612]
# Bug report

- [ V] I confirm this is a bug with Supabase, not with my own application. 
- [ V] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The context `useUser` from `@supabase/auth-helpers-react` returns an object that is not aligned with the documented type (and also different from what supebase js client actually returns)

<img width="519" alt="image" src="https://github.com/supabase/auth-helpers/assets/633840/798d38e0-bf35-41fe-95fc-69427c2b00dd">

<img width="519" alt="image" src="https://github.com/supabase/auth-helpers/assets/633840/1ebbc2d2-0365-429f-a4e6-3181aa943efa">

but if I use supabase.auth.getUser(), I do get the right type

## To Reproduce

Import and use `const user = useUser();` from `"@supabase/auth-helpers-react";` and print the attributes of the not-null user object

## Expected behavior

Expected behavior is to have the same attributes as the documented type

## Screenshots

See above

## System information

- OS: macOS
- Browser : chrome
- Version of supabase-js:
"@supabase/auth-helpers-nextjs": "^0.7.1",
"@supabase/auth-helpers-react": "^0.4.0",
"@supabase/supabase-js": "^2.24.0",
    
- Version of Node.js: node 18

**Comment by IsomerX** [comment]
I can work on this one @adamcohenhillel  please assign it to me.

**Comment by adamcohenhillel** [comment]
hey @IsomerX - I can't seem to be able to assign the issue..

**Comment by J0** [comment]
Hey, going to close this issue as we've moved from Auth-helpers to SSR. If needed, please bring discussion to #744 

Let me know if there are any concerns though
