### ISSUE TITLE
Supabase session is able to be overwritten

### ISSUE THREAD

**Issue by AndrewCathcart** [supabase/auth-helpers#616]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

Not 100% on this being a Supabase bug, but if not the documentation seems a tad lacking?

## Describe the bug

Following along with a tutorial which makes use of Supabase for auth, as well as this auth-helpers dep.

Logging in works fine - I get an auth-token named sb-tbvswgcbrilqlaxdsxii-auth-token
- it doesn't look like this cookie is Secure, or has a SameSite policy?

When interacting with stripe, e.g. creating a checkout session or a billingPortal session, it looks like stripe is overwriting this supabase session cookie.

When we return from stripe, the only supabase related cookie we have is sb-tbvswgcbrilqlaxdsxii-auth-token-code-verifier
- I've tried searching through the docs and I can't find any specific docs describing how to deal with this cookie

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://next13-spotify.vercel.app/ (https://github.dev/AntonioErdeljac/next13-spotify/)
2. Login
3. Click play on any video, it should initiate the stripe test checkout flow
4. Once you return to the main app, you're no longer logged in

## Expected behavior

Supabase auth should be able to handle redirects from other websites that initiate some separate session flow?

## System information

- OS: Windows
- Browser (if applies) Chrome
- Version of supabase-js: 
```
    "@supabase/auth-helpers-nextjs": "^0.7.0",
    "@supabase/auth-helpers-react": "^0.4.0",
    "@supabase/auth-ui-react": "^0.4.2",
    "@supabase/auth-ui-shared": "^0.1.6",
    "@supabase/supabase-js": "^2.23.0",
```
- Version of Node.js: v18.16.0

**Comment by j4w8n** [comment]
> it doesn't look like this cookie is Secure, or has a SameSite policy?

The clients have cookie options you can pass-in. You can find which parameter to pass them in, depending on what client you're using, [here](https://github.com/supabase/auth-helpers/tree/main/packages/nextjs/src)

**Comment by AndrewCathcart** [comment]
> 

That might actually be it, good spot @silentworks
