### ISSUE TITLE
SvelteKit Auth: `data === null` in `LayoutLoad` when visiting non-existing route (404)

### ISSUE THREAD

**Issue by brunobely** [supabase/auth-helpers#618]
# Bug report

- [x] I confirm this is a bug with Supabase *(auth helper guide docs)*, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After following the SvelteKit guide for setting up auth, visiting a non-existing route causes `data` to be `null` in `LayoutLoad`.

## To Reproduce

Follow this guide to set up Supabase auth in SvelteKit: https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#client-side

Visit a route that results in a 404 error. Observe the following error logged to the console:
```
+layout.ts:15 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'session')
    at load (+layout.ts:15:25)
    at load_node (client.js?v=e326a2b6:526:40)
    at async load_root_error_page (client.js?v=e326a2b6:848:23)
    at async server_fallback (client.js?v=e326a2b6:1165:11)
    at async navigate (client.js?v=e326a2b6:1003:24)
```

```ts
// src/routes/+layout.ts
import { createSupabaseLoadClient } from '@supabase/auth-helpers-sveltekit';
import type { LayoutLoad } from './$types';
import {
  PUBLIC_SUPABASE_ANON_KEY,
  PUBLIC_SUPABASE_URL,
} from '$env/static/public';

export const load: LayoutLoad = async ({ fetch, data, depends }) => {
  depends('supabase:auth');

  const supabase = createSupabaseLoadClient({
    supabaseUrl: PUBLIC_SUPABASE_URL,
    supabaseKey: PUBLIC_SUPABASE_ANON_KEY,
    event: { fetch },
    // The next line throws this error when there's a 404.
    // Uncaught (in promise) TypeError: Cannot read properties of null (reading 'session').
    serverSession: data.session,
  });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  return { supabase, session };
};

## Expected behavior

The guide should cover handling the error case. I'm not sure what handling it would look like, otherwise I would make a suggestion.

**Comment by silentworks** [comment]
The guide won't cover what's already covered by SvelteKit's guide itself. This is outside of the scope of this guide.

**Comment by brunobely** [comment]
I did some more investigation and looks like this is the culprit: https://github.com/sveltejs/kit/issues/10157

I had to disable SSR due to this issue which causes FOUC: https://github.com/supabase/auth-ui/issues/46
