### ISSUE TITLE
Supabase Next.js Auth example callback bug

### ISSUE THREAD

**Issue by arobert93** [supabase/auth-helpers#619]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I've been following this [Next.js Auth example](https://supabase.com/docs/guides/auth/auth-helpers/nextjs#managing-sign-in-with-code-exchange) and I think that it is not working properly. I do get the `code` as a query string when `/callback` is beign called, but if I try to reuse the same confirmation URL, I get redirected with an error as a `URL fragment` such as:

http://localhost:3000/auth/supabase/callback#error=unauthorized_client&error_code=401&error_description=Email+link+is+invalid+or+has+expired

This is very confusing because we cannot handle the fragment (#) in a Next.js Route since URL fragments are not being sent to the server. With the current Supabase redirect implementation, I believe that `/callback` path should be a `Page client component` and not `Route`. By doing so we can use both query string and fragment params.

Also, please check the file paths. For example `app/login.tsx` should actually be `app/login/page.tsx`.

**Comment by silentworks** [comment]
Can you provide a reproducible example repo showing this issue please? if you are using Supabase with NextJS you should be using the `@supabase/auth-helpers-nextjs` as the guide you linked to states.

**Comment by Integerous** [comment]
Same issue here -> `localhost:3000/?error=server_error&error_description=Multiple+accounts+with+the+same+email+address+in+the+same+linking+domain+detected%3A+default`

I got the above URL when I try to sign in via Github with the same email already signed in via Google.
Is there any temporal workaround by any chance?
