### ISSUE TITLE
Middleware to protect routes

### ISSUE THREAD

**Issue by arobert93** [supabase/auth-helpers#622]
I've tried using this example:

```ts
import { createMiddlewareClient } from '@supabase/auth-helpers-nextjs'
import { NextResponse } from 'next/server'

export async function middleware(req) {
  const res = NextResponse.next()
  const supabase = createMiddlewareClient({ req, res })
  await supabase.auth.getSession()
  return res
}
```

But I find it really difficult to understand how should I check if the user can access the requested url.

If I add the check as:

```ts
export async function middleware(req) {
  const res = NextResponse.next()
  const supabase = createMiddlewareClient({ req, res })
  const { data: { session }, error } = await supabase.auth.getSession()

  const isAdmin = session?.user?.user_metadata?.role === 'admin';

  if (!isAdmin && req.nextUrl.pathname === '/admin') {
    return NextResponse.redirect(new URL('/login', req.nextUrl.origin))
  }

  return res
}
```

I believe this is invalid because the client instance will use the `res` to update the token cookie with the refreshed value so it won't be transmited in case of redirect. Is that correct? How are we supposed to handle this case?

Thank you!

**Comment by silentworks** [comment]
This isn't an issue in the codebase. Please open a GitHub discussion about this https://github.com/supabase/supabase/discussions
