### ISSUE TITLE
SvelteKit - ReferenceError: global is not defined

### ISSUE THREAD

**Issue by wattsjs** [supabase/auth-helpers#624]
# Bug report

- [X] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When importing `import { createSupabaseLoadClient } from '@supabase/auth-helpers-sveltekit';` (typically in the `layout.ts` file according to the guide), I am hitting a `ReferenceError - global is not defined`. Seems to be from line 660 in the `node-fetch` package which Supabase has forked? I have a different project that is using the original `node-fetch` and I don't see the error.

Seems like it is importing some node libs in the client import

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create fresh sveltekit project
2. Add auth-helpers
3. Create boilerplate `layout.ts` file with an ``import { createSupabaseLoadClient } from '@supabase/auth-helpers-sveltekit';`

## Expected behavior

No error

## Screenshots

![Screenshot 2023-08-23 at 21 44 40@2x](https://github.com/supabase/auth-helpers/assets/60246116/36da76e4-5c84-4db0-a268-2eccfa21f70e)
![Screenshot 2023-08-24 at 12 53 07@2x](https://github.com/supabase/auth-helpers/assets/60246116/9a2e8f2a-b189-4bc1-ab74-ab1c6ba0c9b1)

**Comment by wattsjs** [comment]
Seems related https://github.com/supabase/node-fetch/issues/2

**Comment by david-plugge** [comment]
> Reverting to supabase-js 2.32.0 fixes the issue

If so the issue should be moved over to the supabase-js repo
