### ISSUE TITLE
SvelteKit - Loss of Type Information in Data Returned from createSupabaseServerClient

### ISSUE THREAD

**Issue by farimir** [supabase/auth-helpers#625]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using the createSupabaseServerClient function from the @supabase/auth-helpers-sveltekit package in a SvelteKit +page.server.ts file, the type of the fields from a selected database table is not preserved. All fields come in as any type.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Set up a SvelteKit project and install needed dependencies
2. Create a hooks.server.ts file with content as above in your src directory. Make sure to replace the placeholders for the Supabase URL and keys with your actual values and create $lib/database.types accordingly.
3. Create a new .env file in your root directory and define your Supabase URL and key like below. Replace the placeholders with your actual values:
```
PUBLIC_SUPABASE_URL="your-supabase-url"
PUBLIC_SUPABASE_ANON_KEY="your-supabase-anon-key"
```
4. Inside your hooks.server.ts use the createSupabaseServerClient function with Supabase URL and key:
```
event.locals.supabase = createSupabaseServerClient<Database>({
        supabaseUrl: PUBLIC_SUPABASE_URL,
        supabaseKey: PUBLIC_SUPABASE_ANON_KEY,
        event,
    })
```
5. Use Supabase client defined in hooks.server.ts in a +page.server.ts to select and fetch fields from the 'clients' table. This +page.server.ts should be under a directory that matches the privateRoutePrefix.
```
const {data} = await event.locals.supabase
    .from('clients')
    .select(
      `id, 
      name, 
      type, 
      status, 
      phone_number, 
      deleted_at`,
    )
    .is('deleted_at', null)
```

## Expected behavior

Each field in the resulting data should maintain its corresponding type as defined in the database.

## Screenshots

![image](https://github.com/supabase/auth-helpers/assets/6318472/878e6191-6576-451d-8755-651a251f4c37)

## System information

- OS: [macOS]
- Version of supabase-js: [2.33.1]
- Version of Node.js: [18.16.1]

**Comment by david-plugge** [comment]
Thank you for reporting the issue.

However, I cannot reproduce it, so please provide an actual reproduction.

**Comment by farimir** [comment]
> Thank you for reporting the issue.
> 
> However, I cannot reproduce it, so please provide an actual reproduction.

@david-plugge, thank you for looking into this but the problem was my side!  Sometimes you just need to do the reproduction yourself to hightlight your issue.  I had the wrong import in my app.d.ts.  Sorry for wasting your time.
