### ISSUE TITLE
After authentication with Google, redirect has "access token", earlier it used to be just my redirect url.

### ISSUE THREAD

**Issue by roker15** [supabase/auth-helpers#627]
After authentication with Google , **(I am using nextjs 13.4 with app directory & @supabase/auth-helpers-nextjs package)** I get URL like this - `http://www.localhost:3000/#access_token=eyJhbGciOiJIUzI1NiIsIn.......` but i am expecting just http://www.localhost:3000/ as it used to be earlier..
Earlier i used to get just redirect url without any access_token, which was provided during authentication...

```
const signInWithgoogle = async (redirect1: string) => {
    const { data, error } = await supabase.auth.signInWithOAuth({
      provider: "google",
      options: {
        redirectTo: redirect1,
      },
    });
  };
```
After little bit of debugging i found out that it is happening due to `router.refresh()` inside onauthstatechage(),

**Comment by silentworks** [comment]
You shouldn't be getting the hash # in the url if you are using the version of auth-helpers you state here. The only way you would be getting this hash is if you are using the normal `@supabase/supabase-js` client along with the `auth-helpers` which you shouldn't be doing. You can see examples of how to handle this in this repo https://github.com/supabase-community/supabase-by-example
