### ISSUE TITLE
Unable to sign up users due to PKCE  error - developing locally using Sveltekit.

### ISSUE THREAD

**Issue by jeremypeters** [supabase/auth-helpers#634]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Unable to sign users up - get the error "PKCE flow is not supported on signups with autoconfirm enabled". I'm developing locally using Sveltekit and https://github.com/supabase/auth-ui.

Looks like the issue has been resolved for Next https://github.com/supabase/auth-helpers/issues/569 but it's difficult to discern from all the comments what the actual status of the issue is and the action required.

## Screenshots

![Screenshot 2023-09-10 at 16 27 58](https://github.com/supabase/auth-helpers/assets/1882972/05fb5320-07fa-4608-ab3a-a5768fc403d1)

## System information

- Version of supabase-js: 2.26.0
- Version of Node.js: 18.17.0

**Comment by silentworks** [comment]
I've left a comment about which comment has the fix in the second to last comment in that issue. I'm leaving it here again and will be closing this issue too https://github.com/supabase/auth-helpers/issues/569#issuecomment-1703159422.

**Comment by jeremypeters** [comment]
@silentworks Can confirm it's working now after following your instructions, many thanks.
