### ISSUE TITLE
Middleware is not refreshing cookie using next auth helpers

### ISSUE THREAD

**Issue by cristianstu** [supabase/auth-helpers#635]
- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Middleware is not refreshing cookie using next auth helpers after upgrading to 0.7.4 from 0.6.1

## To Reproduce

1. npx create-next-app -e with-supabase
2. Log-in, cookie es set.
3. Refresh the page, cookie is never updated.

## Expected behavior

The cookie max-age changes.

## System information

- OS: Ubuntu 23.04
- Browser chrome, firefox
- Version of supabase-js: 2.33.2
- Version of Node.js: 18.17.1

**Comment by silentworks** [comment]
Cookie max-age doesn't change, the JWT inside the cookie is what gets updated. The max-age is set to something like 10 years or something like that so this isn't something that would refresh. However your JWT should get refreshed, I've tested this earlier based on another issue on here and that indeed does work as expected.

**Comment by cristianstu** [comment]
> Cookie max-age doesn't change, the JWT inside the cookie is what gets updated. The max-age is set to something like 10 years or something like that so this isn't something that would refresh. However your JWT should get refreshed, I've tested this earlier based on another issue on here and that indeed does work as expected.

I've changed via de cookieOptions the maxAge option (it is accepted) to 3hs. So even if jwt changes, cookie will not be sent after 3hs. It was changing before v0.6.x.

**Comment by cristianstu** [comment]
Also, I'm not seeing the JWT refreshed anyway.

**Comment by silentworks** [comment]
You will need to provide a minimal reproducible repository with this issue as I'm not able to replicate this on my end.

**Comment by cristianstu** [comment]
@silentworks If cookie max-age doesn't change anymore, what is the recommended way to make session expires after 1h of inactivity now?

**Comment by silentworks** [comment]
The cookie max-age has no relation to your JWT expiry time. Actually you shouldn't even be modifying the cookie max-age as we are only using the cookie as a storage mechanism hence why we set it to a far future date. If the cookie max-age is being set to something else you could end up with unexpected behavior where the cookie expires while your JWT expiry time hasn't been reached. This would in effect log your user out unexpectedly.

**Comment by cristianstu** [comment]
@silentworks Thank you for your help. I know that, and I'm taking care about that.

My problem with the token expiry time is that it gets automatically renewed and I don't want that in some cases (like after some time of inactivity) So I was doing that with the cookie until now and it was fine. Maybe I should handle it in another way, just not sure if if is supported or I should do it manually.

**Comment by silentworks** [comment]
Ah right got you. Yeah if this was supported in the past it shouldn't have been, I'm going to explicitly add the functionality in the code to ignore `max-age` as it's not something we should support with our use case.
