### ISSUE TITLE
getSession() returning null inside of Route Handler

### ISSUE THREAD

**Issue by rajdtta** [supabase/auth-helpers#636]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

For some reason, using `supabase.auth.getSession()` inside of my route handlers is returning a null session consistently, even though its usage inside of my `middleware.ts` & root `layout.tsx` files both correctly return the active session.

I've spent a couple hours at this point trying to debug the issue, but I haven't been able to figure out what's causing the issue.

## To Reproduce

```ts
// route.ts
import { createRouteHandlerClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { NextRequest } from "next/server";

export const dynamic = "force-dynamic";

export const GET = async (req: NextRequest) => {
  try {
    const supabase = createRouteHandlerClient({ cookies });
    const session = await supabase.auth.getSession();
    console.log("DIRECT SUPABASE CALL");
    console.log(session);

    // Session is always returning null

    ...
  } catch (e: any) {
    ...
  }
};
```

```ts
// middleware.ts
import { NextRequest, NextResponse } from "next/server";
import { createMiddlewareClient } from "@supabase/auth-helpers-nextjs";

export async function middleware(req: NextRequest) {
  const res = NextResponse.next();
  const supabase = createMiddlewareClient({ req, res });
  const session = await supabase.auth.getSession();
  console.log(session);

  // Session is properly returned
}
```

## Expected behavior

I would expect `getSession()` to return my active session (as it does inside of `middleware.ts`)

## Screenshots

![layout.tsx getSession()](https://i.raj.wtf/imgs/YdXZkukcmcQta99RLUkbCyn4iD6.png)
![route.ts getSession()](https://i.raj.wtf/imgs/Z5IpK9vKQsxJBUxyVyP8CPa49j1.png)

## System information

- OS: macOS
- Browser: Arc (Chromium)
- Version of supabase-js: 2.33.2 (also tried it on v2.33.1. no difference)
- Version of auth-helpers-nextjs: 0.7.4
- Version of Next.js: 13.4.19
- Version of Node.js: 20.5.1 (from `node --version`)

**Comment by silentworks** [comment]
Can't replicate this, you will need to provide a minimal reproducible example repo with the issue. The tests I've done in the screen recording is using the code from here https://github.com/supabase-community/supabase-by-example/tree/main/reset-flow/nextjs

https://github.com/supabase/auth-helpers/assets/79497/b3961382-0ef2-4245-8d14-940b6c76ce55

**Comment by silentworks** [comment]
The issue @rajdtta was having is that he is making a request to the route handler using the Fetch API, but the Fetch API doesn't forward the headers when making a request to a route handler. You have to manually forward those headers over, the answer is in our GitHub discussions troubleshooting section https://github.com/orgs/supabase/discussions/15859
