### ISSUE TITLE
Middleware auth.getSession returns null when Third Party Provider is used (Google)

### ISSUE THREAD

**Issue by panstabolitis** [supabase/auth-helpers#645]
# Bug report

## Describe the bug
I am currently using the Google Provider from Supabase but createMiddlewareClient returns null when called. 

## To Reproduce
While using Google Provider
```js
    const res = NextResponse.next()

    const supabase = createMiddlewareClient({ req, res })
    
    const {
        data: { session },
    } = await supabase.auth.getSession()
```

## Expected behavior

Expected: Returns session
Reality: Returns null

## System information

- OS: macOS 13.3.1 (a) (22E772610a)
- Version of supabase-js: 2.36.0
- Version of Node.js: v18.17.0

**Comment by silentworks** [comment]
Can't replicate, please provide a reproducible repository with the issue. There is a working example repository here https://github.com/supabase-community/supabase-by-example/tree/main/oauth-flow/nextjs

**Comment by panstabolitis** [comment]
> Can't replicate, please provide a reproducible repository with the issue. There is a working example repository here https://github.com/supabase-community/supabase-by-example/tree/main/oauth-flow/nextjs

Hey!

I've uploaded the repo, let me know :)

https://github.com/panstabolitis/temp-supa-next

**Comment by panstabolitis** [comment]
> You aren't using the `auth-helpers` in that repo so this is the wrong place to open that issue. You should be using the auth-helpers when using Next.js like the example repo I pointed you to.

Yes I am using them? I am importing the MiddleWareClient in middleware.ts

**Comment by j4w8n** [comment]
> Yes I am using them? I am importing the MiddleWareClient in middleware.ts

But you're defining a custom client with `createClient` in your `lib` folder, then using that in your Profile component. If you're going to use auth helpers, you need to use their client functions exclusively. The only exception is if you're creating a client with the `service_role` key.

**Comment by panstabolitis** [comment]
> > Yes I am using them? I am importing the MiddleWareClient in middleware.ts
> 
> But you're defining a custom client with `createClient` in your `lib` folder, then using that in your Profile component. If you're going to use auth helpers, you need to use their client functions exclusively. The only exception is if you're creating a client with the `service_role` key.

Apologies, I understand now
