### ISSUE TITLE
createPagesBrowserClient with custom cookieOptions doesn't work properly

### ISSUE THREAD

**Issue by solsonl** [supabase/auth-helpers#648]
I am trying to use this API (v.0.8.1)

```
createPagesBrowserClient({
      cookieOptions: {
        maxAge: REA_COOKIE_MAX_AGE,
        domain: ".test.com",
        secure: true,
        sameSite: "lax",
      }
    })
```

Expected:
Cookie should have at least these below values:
```
        domain: ".test.com",
        secure: true,
        sameSite: "lax",
```

But when I run test in domain www.test.com (for example), the cookie is created with these values:
```
value: this is correct
domain: "www.test.com",
secure: false
sameSite: "",
```

Could you please take a look at this issue?

Thank you

P.s. Not sure if this is related, I also call this on middleware (without cookieOptions):
```
const supabase = createMiddlewareClient({ req: request, res });
  await supabase.auth.getSession();
```

**Comment by ElectricCodeGuy** [comment]
They worked fine this morning. When I try and build now It no longer allows me to build. I get this:
`✓ Creating an optimized production build    
 ✓ Compiled successfully
   Linting and checking validity of types  ..Failed to compile.

./node_modules/@supabase/auth-helpers-shared/dist/index.d.ts:3:40
Type error: Cannot find module 'cookie' or its corresponding type declarations.

  1 | import * as _supabase_supabase_js from '@supabase/supabase-js';
  2 | import { SupabaseClientOptions, GoTrueClientOptions, Session } from '@supabase/supabase-js';
> 3 | import { CookieSerializeOptions } from 'cookie';
    |                                        ^
  4 | export { parse as parseCookies, serialize as serializeCookie } from 'cookie';
  5 | import { GenericSchema } from '@supabase/supabase-js/dist/module/lib/types';
  6 | `

**Comment by minhhieple97** [comment]
I got same issue.

**Comment by joa-queen** [comment]
Same issue. When adding `cookieOptions`, cookie is not being set at all.

**Comment by silentworks** [comment]
If you add cookieOptions to one client, you have to add it to all clients. So you would need to do the same with `createMiddlewareClient` and `createPagesServerClient` too.
