### ISSUE TITLE
Starter Auth Helpers with Nextjs App Router doesn't work

### ISSUE THREAD

**Issue by absolutegravitas** [supabase/auth-helpers#652]
# Bug report

- [X ] I confirm this is a bug with Supabase, not with my own application. 
- [X ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Starter App using nextjs app router doesnt work.

## To Reproduce

1. Go to 'https://supabase.com/docs/guides/auth/auth-helpers/nextjs?language=ts'
2. Follow instructions under Automatic Configuration
3. Run yarn dev (with correct environment variables)
4. Attempt sign up with new user (email) and password
5. Page reloads with message "could not authenticate user" no browser console errors, no terminal errors

## Expected behavior

1 - supabase user is created in auth schema
2 - user creation is confirmed.

## Screenshots
![image](https://github.com/supabase/auth-helpers/assets/124488796/6a597024-c333-46d3-8a40-bed1da6807d8)

![image](https://github.com/supabase/auth-helpers/assets/124488796/8204a9cb-8bcf-468b-b6e0-80caca67c096)
![image](https://github.com/supabase/auth-helpers/assets/124488796/9dd53027-ca9e-4247-9977-87bfad3bc9c6)

## System information
@supabase/auth-helpers-nextjs": "^0.8.1",
@supabase/supabase-js": "^2.38.1",
node 20.8.0

**Comment by silentworks** [comment]
Can't replicate, please provide a reproducible example repo with the issue you are having. Also note we've updated the Next.js template in recent times so please try it out again.

**Comment by absolutegravitas** [comment]
hey @silentworks closing this as it was answered / resolved in the main supabase repo i created - TLDR for anyone running into this, wrong SMTP config results in this (generic) error on the frontend.
