### ISSUE TITLE
Update import on nextjs-pages index

### ISSUE THREAD

**Issue by dougkeefe** [supabase/auth-helpers#660]
# Chore
Update the import to auth-helper-nextjs for the clarity of the example 

## Describe the chore
Modify index.tsx import from:
import {
	Session,
	createPagesBrowserClient,
	createPagesServerClient
} from '@/../../packages/nextjs/dist';

to
import {
	Session,
	createPagesBrowserClient,
	createPagesServerClient
} from '@supabase/auth-helpers-nextjs';

## Additional context
This should provide added clarity and consistency in the example provided.

**Comment by silentworks** [comment]
Can you point me to where you've found this example code please?

**Comment by dougkeefe** [comment]
examples/nextjs-pages/pages/index.tsx
