### ISSUE TITLE
@supabase/ssr middleware issue

### ISSUE THREAD

**Issue by 0x-Legend** [supabase/auth-helpers#673]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using auth-helpers-nextjs, I was able to do code exchange for session in the middleware if the authentication was called from client side. But I am not able to do this anymore after migrating to the new ssr package.

## To Reproduce

1. Clone and run ssr example:  'https://github.com/0x-Legend/Nextjs-14-Supabase-Starter/tree/middlewareCodeExchange/ssr'
2. Navigate to '/login/client'
3. Sign in with Google
4. You will be redirected to the home page but no session present

5. Clone and run auth-helpers-nextjs example: 'https://github.com/0x-Legend/Nextjs-14-Supabase-Starter/tree/middlewareCodeExchange/auth-helpers-nextjs'
6. Navigate to '/login/client'
7. Sign in with Google
8. You will be redirected to the home page and a session will be present

## Expected behavior

SSR package middleware should mimic the behavior of what auth-helpers-nextjs does. Should be able to exchange code for session in middleware like we used to be able to (when signing in from client).

## System information

- OS: macOS 14.0
- Browser: Chrome
- Version of @supabase/ssr: 0.0.7
- Version of @supabase/auth-helpers-nextjs: 0.8.5

## Additional context

- This is only for when supabase.auth.signInWithGoogle() is called from the client.
- In the example repo branches, I have only set up Google OAuth for this demo, the remaining auth methods all redirect to the auth/callback route that the Supabase docs recommend.
- This repo is built off the nextjs with-supabase example.

**Comment by silentworks** [comment]
I see the issue is in the `middleware.ts` inside of the starter template. If you change it to this it will work the same as the `auth-helpers` setup.

```ts
import { createServerClient, type CookieOptions } from '@supabase/ssr'
import { type NextRequest, NextResponse } from 'next/server'

export const createClient = (request: NextRequest) => {
  // Create an unmodified response
  const response = NextResponse.next({
    request: {
      headers: request.headers,
    },
  })

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return request.cookies.get(name)?.value
        },
        set(name: string, value: string, options: CookieOptions) {
          // If the cookie is updated, update the cookies for the request and response
          request.cookies.set({
            name,
            value,
            ...options,
          })
        },
        remove(name: string, options: CookieOptions) {
          // If the cookie is removed, update the cookies for the request and response
          request.cookies.set({
            name,
            value: '',
            ...options,
          })
        },
      },
    }
  )

  return { supabase, response }
}
```
The issue the original code has is that the new response that was being created isn't returned from this function hence there is no way for Next.js to know the response has a cookie attached to it.

**Comment by 0x-Legend** [comment]
This seems to work. 

So is the example on the template and also the [docs](https://supabase.com/docs/guides/auth/server-side/creating-a-client?environment=middleware) incorrect? A little confused as to the logic.

**Comment by silentworks** [comment]
Ok let me clear up what is happening here with this change and what side effects this change causes. Server components in Next.js reads from the `Cookie` header and not the `Set-Cookie` header, so with the change I've given above if the next page you redirect to is a server component page you won't be able to read the cookie on that page. One of the reasons why we don't suggest you doing the callback logic/exchangeCodeForSession inside of a middleware is that it's now hidden away from anyone working on the app, you now pollute your middleware with logic not intended for it, you also end up in the state I mentioned above due to the change necessary for the cookie to work in the middleware.

The docs and template aren't incorrect, you are just using it in a way not intended hence the change I gave you to make it work in that scenario. This isn't a auth-helpers/ssr issue, it's a understanding of how Next.js works issue.

**Comment by 0x-Legend** [comment]
Thank you for explaining this further @silentworks! I’ll stick to the recommended approach.

**Comment by dumaron** [comment]
I made the same mistake, and needed to learn how to fix that by trial and error by experiment. Even if it's not a supabase/ssr issue, maybe it could benefit from having some hints or docs somewhere. jm2c!

**Comment by silentworks** [comment]
@dumaron I think we've documented our recommended approach. Any other approach by a developer would be left down to that developer as that would be outside of what we recommend, we cannot cover every approach a developer might take with every framework out there so I don't believe this is part of our responsibility from a library author's perspective.

**Comment by dejongyeong** [comment]
Hi all, I'd like some help on the middleware. It seems like when I want to get the session of the current logged-in user, it always returns `null`. 

```
export const sbMiddleware = (request: NextRequest) => {
  // create an unmodified response
  let response = NextResponse.next({ request: { headers: request.headers } });

  const supabase = createServerClient(
    env.NEXT_PUBLIC_APP_URL!,
    env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return request.cookies.get(name)?.value;
        },
        set(name: string, value: string, options: CookieOptions) {
          request.cookies.set({
            name,
            value,
            ...options,
          });
          response = NextResponse.next({
            request: {
              headers: request.headers,
            },
          });
          response.cookies.set({
            name,
            value,
            ...options,
          });
        },
        remove(name: string, options: CookieOptions) {
          request.cookies.set({ name, value: "", ...options });
          response = NextResponse.next({
            request: { headers: request.headers },
          });
          response.cookies.set({ name, value: "", ...options });
        },
      },
    },
  );

  return { supabase, response };
};
```

```
export const getCurrentSession = async (supabase: SupabaseClient) => {
  const {
    data: { session },
  } = await supabase.auth.getSession();

  return session;
};
```

```
export function withAuthentication(middleware: NextMiddleware) {
  return async (request: NextRequest, event: NextFetchEvent) => {
    // create an unmodified response
    const { supabase } = sbMiddleware(request);

    // redirect user if no current session
    const session = await getCurrentSession(supabase);
    if (!session) {
      return NextResponse.redirect(new URL("/", request.url));
    }

    return middleware(request, event);
  };
}
```

Main middleware file in NextJS 14
```
import { chain } from "./middlewares/chain";
import { withAuthentication } from "./middlewares/withAuthentication";
import { withAuthorization } from "./middlewares/withAuthorization";
import { withSupabase } from "./middlewares/withSupabase";

const middlewares = [withSupabase, withAuthentication, withAuthorization];

export default chain(middlewares);

// protected routes
export const config = { matcher: ["/dashboard/:path*", "/users/:path*"] };
```

Looking forward to any guidance!

**Comment by augchan42** [comment]
I'm a little confused, as the sample code I see does set cookie info and returns a response (https://supabase.com/docs/guides/auth/server-side/creating-a-client?environment=middleware)

So is there no need to use the above code sample anymore or is there still a need?  As I do see when doing google login I'm redirected and I see cookies are set in the browser, but I'm not certain a session is available.  Sorry I'm new to auth.
