### ISSUE TITLE
supabase/ssr v0.0.7 stopped defaulting `httpOnly` cookie option to `false`, breaking access to cookies from client-side code

### ISSUE THREAD

**Issue by j4w8n** [supabase/auth-helpers#681]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After upgrading from v0.0.4 to v0.0.9, my test app partially broke, post-login, and wouldn't render html that relied on there being a `session`.

Turns out the cookie is being set with `httpOnly` set to `true`. I tracked this down to a change in v0.0.7 (https://github.com/supabase/auth-helpers/commit/fc8ccfd44de3c544ca02e1ecd56ec72ea3479989).

I was able to make things work by passing `cookieOptions: { httpOnly: false }` into `createServerClient()`.

## To Reproduce

Upgrade @supabase/ssr to v0.0.7 or higher

## Expected behavior

Either add `httpOnly: false` back into `src/utils/constants.ts` or update the documentation for the server clients of affected frameworks.

## Additional Context

I'm using SvelteKit, which defaults `httpOnly` to `true`. I'm unsure how other frameworks handle this.

**Comment by silentworks** [comment]
We really shouldn't be setting this as I believe this is something each framework and developer should handle. But looking at `auth-helpers` it seems we were setting this to `false` in all cases so it's only right to continue that here.

**Comment by j4w8n** [comment]
I'm good with either solution. Just gotta document it if needed. Either way, it's vital that it be `false` for the browser client to work in the browser, right?

**Comment by AlbertMarashi** [comment]
@silentworks is this the same issue as https://github.com/supabase/auth-helpers/issues/684 ?

Mine also had a HTML hydration issue which caused the app to not render due to missing session
