### ISSUE TITLE
SvelteKit Broken: `.getSession()` returning null in client-side but returning session in serverside (min reproducible example) with Google SSO

### ISSUE THREAD

**Issue by AlbertMarashi** [supabase/auth-helpers#684]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

So auth code exchange for session is working correctly because the server is able to create/get a session from it

but the client `.getSession()` returns a null session

I believe it has something to do with the new cookie chunking feature that was recently added and has broken everything

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. `git clone https://github.com/AlbertMarashi/supabase-auth-error.git`
2. set up test database w/ env variables as per documentation example
3. enable google SSO on test database (& create google app)
4. setup wildcard redirect url approval in supabase
5. run `npm run dev` to start local dev server
6. visit `/` url on dev server, click the button to be redirected to Google sign in
7. the app should redirect to back to home, notice how the session is logged correctly in the server, but returns null on client-side
8. This is a bug 

## Expected behavior

Session should be available on both client side and server side, but is only available on the server. This is obviously problematic.

I have followed the documentation guide for setting up the `@supabase/ssr` package and this has errors

## Screenshots

![image](https://github.com/supabase/auth-helpers/assets/17972275/418f5143-afbf-4878-8a9d-885e25563666)

**Comment by AlbertMarashi** [comment]
The docs I followed are here:

https://supabase.com/docs/guides/auth/server-side/creating-a-client?framework=sveltekit&environment=layout

**Comment by j4w8n** [comment]
Sounds like [this](https://github.com/supabase/auth-helpers/issues/681) issue.

**Comment by AlbertMarashi** [comment]
@j4w8n it does indeed. This seems like a bug or documentation issue with Supabase. Following the guide should not lead to this sort of issue.

Oddly it only happens with OAuth and not with email & password logins. Is that the case with you

**Comment by olsommer** [comment]
I even was not able to get a valid session with email/pw. #681 helped. 

I added that one line and it's working again. 
```typescript
event.locals.supabase = createServerClient<Database>(
    PUBLIC_SUPABASE_URL,
    PUBLIC_SUPABASE_ANON_KEY,
    {
      cookies: {
        get: (key) => event.cookies.get(key),
        set: (key, value, options) => {
          event.cookies.set(key, value, options);
        },
        remove: (key, options) => {
          event.cookies.delete(key, options);
        },
      },
      cookieOptions: { httpOnly: false },
    },
  );
```

**Comment by j4w8n** [comment]
They released a fix. v0.0.10

**Comment by AlbertMarashi** [comment]
Awesome
