### ISSUE TITLE
@supabase/ssr fails with OAuth

### ISSUE THREAD

**Issue by sroussey** [supabase/auth-helpers#690]
# Bug report
- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

git clone https://github.com/sroussey/test-supabase
\# add your key stuff to .env
npm run dev
\# navigate to /login
\# Choose one, in this case Google
\# See error: Access blocked: Authorization Error (Invalid parameter value for code_challenge_method: 's256' is not a valid CodeChallengeMethod)

## Expected behavior

Ability to login via OAuth

## Screenshots

<img width="488" alt="image" src="https://github.com/supabase/auth-helpers/assets/127349/37b8d595-4c23-4e0b-8d77-02bd8b6cb0c4">

## Additional context

The test repo was created using `npx create-next-app -e with-supabase` and just adding links to use OAuth. Maybe such a thing should be added to the base template.

**Comment by sroussey** [comment]
So... I have had google working for a long time. Using:

"@supabase/auth-helpers-nextjs": "^0.6.1",
"@supabase/auth-helpers-react": "^0.3.1",
  
It works fine. I tried upgrading, but then I got the same failure. I tried switching to ssr and got this same failure. That is why I created this simple example.

I believe the failure started when the libs changed to start using PKCE.

**Comment by iboss-ptk** [comment]
I'm having the same issue with `"@supabase/ssr": "^0.0.10"`. doing this will not have the error but I don't think it's the way to go..

```js
const supabase = createBrowserClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
		global: {
			fetch
		},
		cookies: {
			get(key) {
				if (!isBrowser()) {
					return JSON.stringify(data.session);
				}

				const cookie = combineChunks(key, (name) => {
					const cookies = parse(document.cookie);
					return cookies[name];
				});
				return cookie;
			}
		},
		auth: {
			// change flow type to implicit
			flowType: 'implicit'
		}
	});
```

**Comment by iboss-ptk** [comment]
ok so with local supabase `http://localhost:54321/auth/v1/authorize?provider=google&code_challenge=<base64encodedstring>&code_challenge_method=s256` fail but `code_challenge_method=S256` works.

We might need to fix [this line](https://github.com/supabase/gotrue-js/blob/c9296bbc27a2f036af55c1f33fca5930704bd021/src/GoTrueClient.ts#L2078) from `supabase/gotrue-js` for google provider, haven't tested with other provider though.

**Comment by iboss-ptk** [comment]
related issue: https://github.com/supabase/gotrue-js/issues/770

**Comment by J0** [comment]
Hey team,

Thanks for reporting the issue and for supplying a test repository - I'm having a slight issue with replicating this though - [this](https://share.cleanshot.com/jk78vz16) is what it looks like on my end.

The `code_challenge_method` param is intended for Supabase Auth and not for `Google`. There was a known issue in April where the `code_challenge_method` param was not sanitized which lead to the error. It was patched in late April/early May and we haven't observed repeat instances since then

Could I trouble you to try clearing both `package-lock.json` and `node_modules` and reinstalling after?

Alternatively, if there's a staging environment or another test repository where we can replicate this we can take a look further. 

Thanks

**Comment by sroussey** [comment]
When setting up a staging server, I don't see the issue.

So maybe my local version of supabase is out of date? Is there a way to check?

**Comment by sroussey** [comment]
> So maybe my local version of supabase is out of date? Is there a way to check?

I never use `npx supabase start/stop` so it never updates (I start and stop docker instead). I imagine many people do this. 

You might put in some check that the client and server versions are compatible or something.

**Comment by J0** [comment]
Hey @sroussey,

Sorry for the delayed reply - was away for the holidays. Happy New Year and thanks for looking into the issue. For Auth one can check against the [releases page](https://github.com/supabase/gotrue/releases) against what's on the Docker container to see that it's up to date. 

We're looking into alternative solutions and will relay to CLI team. Thanks for the feedback!
