### ISSUE TITLE
@supabase/ssr@0.0.10 - supabase.auth.signOut() does not work

### ISSUE THREAD

**Issue by phenomen** [supabase/auth-helpers#692]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I migrated from SvelteKit Auth Helper to SSR Helper and everything seems fine except signing user out. `supabase.auth.signOut()` does nothing -user stay signed in.

In the Network tab I see a Request to `https://my-supabase-instance.supabase.co/auth/v1/logout?scope=global` with an empty Response.

## To Reproduce

1. Follow SSR docs at https://supabase.com/docs/guides/auth/server-side/migrating-to-ssr-from-auth-helpers?framework=sveltekit
2. Add Sign Out button with function:
```
export let data: PageData;
let { supabase } = data;
$: ({ supabase } = data);

async function handleSignOut() {
  await supabase.auth.signOut();
  goto('/auth');
}
```

## System information
- Google Chrome
- @supabase/supabase-js: 2.38.4
- @supabase/ssr: 0.0.10
- @sveltejs/kit: 1.27.2
- svelte: 4.2.5
- vite: 4.5.0

**Comment by j4w8n** [comment]
I'm not experiencing any issues. I see no response to the POST on my network tab either, but everything is working.

Is the redirect happening?

**Comment by phenomen** [comment]
> I'm not experiencing any issues. I see no response to the POST on my network tab either, but everything is working.
> 
> Is your redirect happening?
> 
> supabase-js 2.38.4 supabase/ssr 0.0.10 sveltekit 1.27.5 svelte 4.2.3 vite 4.5.0

Redirect is happening but user is not logged out. User session still exist.

**Comment by j4w8n** [comment]
So does the auth cookie still exist in the browser?

**Comment by phenomen** [comment]
> So does the auth cookie still exist in the browser?

Yes. Nothing in Session storage / Cookies changes.

**Comment by j4w8n** [comment]
If you manually delete the cookies, are you able to log back in?

**Comment by phenomen** [comment]
> If you manually delete the cookies, are you able to log back in?

Yes. OAuth (Google) login works flawlessly. If I delete cookies manually, I can sign in back with no issues.

**Comment by JoshGatto** [comment]
I was running into the same issue in my next.js project, what fixed it for me was placing the set and remove code blocks in my supabase server file like the example https://github.com/vercel/next.js/blob/canary/examples/with-supabase/utils/supabase/server.ts

**Comment by j4w8n** [comment]
To @JoshGatto 's point, what does your client creation code look like?

**Comment by briankintz** [comment]
I've been digging into this problem with SvelteKit. It looks like the issue comes when calling `signOut()` in the browser when using the example code [in the docs for configuring the root layout load](https://supabase.com/docs/guides/auth/server-side/creating-a-client?environment=layout&framework=sveltekit#creating-a-client), specifically the cookie `get` function:

```js
const supabase = createBrowserClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
  global: {
    fetch,
  },
  cookies: {
    get(key) {
      if (!isBrowser()) {
        return JSON.stringify(data.session)
      }

      const cookie = combineChunks(key, (name) => {
        const cookies = parse(document.cookie)
        return cookies[name]
      })
      return cookie
    },
  },
})
```

This returns all the chunks combined, which tricks the [deleteChunks](https://github.com/supabase/auth-helpers/blob/main/packages/ssr/src/utils/chunker.ts#L65) function into returning early before actually deleting all the chunks:

```js
export async function deleteChunks(
  key: string,
  retrieveChunk: (name: string) => Promise<string | null | undefined> | string | null | undefined,
  removeChunk: (name: string) => Promise<void> | void
) {
  const value = await retrieveChunk(key);

  if (value) {
    await removeChunk(key);
    return;
  }

  for (let i = 0; ; i++) {
    const chunkName = `${key}.${i}`;
    const chunk = await retrieveChunk(chunkName);

    if (!chunk) {
      break;
    }

    await removeChunk(chunkName);
  }
}
```

The client expects the function to only return a single cookie entry and deals with chunking itself, so I fixed the problem by removing the extra use of `combineChunks()` when creating the browser client:

```js
const supabase = createBrowserClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
  global: {
    fetch,
  },
  cookies: {
    get(key) {
      if (!isBrowser()) {
        return JSON.stringify(data.session)
      }

      const cookie = parse(document.cookie)
      return cookie[key]
    },
  },
})
```

**Comment by phenomen** [comment]
> I've been digging into this problem with SvelteKit. It looks like the issue comes when calling `signOut()` in the browser when using the example code [in the docs for configuring the root layout load](https://supabase.com/docs/guides/auth/server-side/creating-a-client?environment=layout&framework=sveltekit#creating-a-client), specifically the cookie `get` function:
> 
> ```js
> const supabase = createBrowserClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
>   global: {
>     fetch,
>   },
>   cookies: {
>     get(key) {
>       if (!isBrowser()) {
>         return JSON.stringify(data.session)
>       }
> 
>       const cookie = combineChunks(key, (name) => {
>         const cookies = parse(document.cookie)
>         return cookies[name]
>       })
>       return cookie
>     },
>   },
> })
> ```
> 
> This returns all the chunks combined, which tricks the [deleteChunks](https://github.com/supabase/auth-helpers/blob/main/packages/ssr/src/utils/chunker.ts#L65) function into returning early before actually deleting all the chunks:
> 
> ```js
> export async function deleteChunks(
>   key: string,
>   retrieveChunk: (name: string) => Promise<string | null | undefined> | string | null | undefined,
>   removeChunk: (name: string) => Promise<void> | void
> ) {
>   const value = await retrieveChunk(key);
> 
>   if (value) {
>     await removeChunk(key);
>     return;
>   }
> 
>   for (let i = 0; ; i++) {
>     const chunkName = `${key}.${i}`;
>     const chunk = await retrieveChunk(chunkName);
> 
>     if (!chunk) {
>       break;
>     }
> 
>     await removeChunk(chunkName);
>   }
> }
> ```
> 
> The client expects the function to only return a single cookie entry and deals with chunking itself, so I fixed the problem by removing the extra use of `combineChunks()` when creating the browser client:
> 
> ```js
> const supabase = createBrowserClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
>   global: {
>     fetch,
>   },
>   cookies: {
>     get(key) {
>       if (!isBrowser()) {
>         return JSON.stringify(data.session)
>       }
> 
>       const cookie = parse(document.cookie)
>       return cookie[key]
>     },
>   },
> })
> ```

Thanks! This fixed my issue and sign out now works correctly.

**Comment by briankintz** [comment]
> Does that fix break sign in? because I believe it was added because there were some sign in issues without it as far as I was aware

It doesn't in my app and I can't see why it would. All usages in `createBrowserClient.ts` and `createServerClient.ts` are wrapped with the chunking methods, so the get/set/delete methods only ever operate on individual chunks.

**Comment by phenomen** [comment]
> Hmm it didn't seem to break sign in for me

Neither for me - with this fix, both sign-in and sign-out work fine.

**Comment by PaperPrototype** [comment]
Ok, so here is why SSR is singOut is failing. If you reload the page after calling signOut it should work.
But we can be fancy and the Auth helpers documnentation can help

https://supabase.com/docs/guides/auth/auth-helpers/sveltekit#setting-up-the-event-listener-on-the-client-side

```js
<!-- src/routes/+layout.svelte -->
<script lang="ts">
  import { invalidate } from '$app/navigation'
  import { onMount } from 'svelte'

  export let data

  let { supabase, session } = data
  $: ({ supabase, session } = data)

  onMount(() => {
    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((event, _session) => {
      if (_session?.expires_at !== session?.expires_at) {
        invalidate('supabase:auth')
      }
    })

    return () => subscription.unsubscribe()
  });
</script>

<slot />
```

This solved my problem :) singOut and login and all the client side functions work now

**Comment by AlbertMarashi** [comment]
@PaperPrototype that onMount code fixed my issues. I know it was in the previous package, but it appears the docs are missing that step

**Comment by briankintz** [comment]
> Not really sure what problem is caused by the cookies here, but that was not the problem.

It is definitely a problem (at least for the original issue here), but only if the `sb-xxx-auth-token` cookie is chunked. In that case, the internal call to `storage.removeItem` [returns early without actually deleting the cookie chunks](https://github.com/supabase/auth-helpers/blob/main/packages/ssr/src/utils/chunker.ts#L74), which keeps the user signed in.

You are right about needing to `invalidate` the auth data, but that's a separate issue from the cookie problem.

**Comment by PaperPrototype** [comment]
@briankintz Ah, my bad, in that case should I change the cookie code to the what you show above? I checked and as far as I can tell the cookie gets deleted.

(screenshot of the cookie)
<img width="563" alt="Screenshot 2023-12-07 at 1 00 49 PM" src="https://github.com/supabase/auth-helpers/assets/48071553/18e1de20-c319-495e-884e-edc8f1bd7bee">

**Comment by alexbaramilis** [comment]
I have tried both with and without combineChunks but it doesn't make a difference for me. My log out works most of the time, but sometimes (and I can't figure out why) it doesn't log me out on the first attempt. But it always works on the second attempt. I also have the onAuthStateChange code since I'm coming from auth-helpers. (You should add that to the ssr documentation btw because it's really confusing for old and new people)

**Comment by silentworks** [comment]
@briankintz is correct in what he stated here and we've merged his PR which fixes this issue. Do note you much do a redirect (using `goto` if client side code or `redirect` if server side code) in your app after calling the `signOut` method. @phenomen let me know if the solution provided in the updated docs is working for you. Also anyone else replying here unless you provide a minimal reproducible repository it will be hard for us to reproduce what you are experiencing as folloing the changes suggested fixed the issue on our side and we are no longer having that issue.

**Comment by phenomen** [comment]
@silentworks I copy-pasted everything from the guide and Sign In / Sign Out works now without any additional modifications. 

Just a small thing I had to do - change instances of `throw redirect` to just `redirect` in the [SvelteKit OAuth example](https://supabase.com/docs/guides/auth/server-side/oauth-with-pkce-flow-for-ssr?framework=sveltekit) (SvelteKit 2.0 change). But that's a different guide and not relevant to the original issue, so I'm closing it as fixed.

**Comment by williamlmao** [comment]
> I was running into the same issue in my next.js project so not sure if it applies but in case it does, what fixed it for me was placing the set and remove code blocks in my supabase server file like the example https://github.com/vercel/next.js/blob/canary/examples/with-supabase/utils/supabase/server.ts

this worked for me!

**Comment by PaperPrototype** [comment]
I updated the packages and it seems to have been resolved

**Comment by trasgoverde** [comment]
> ```js
> const supabase = createBrowserClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
>   global: {
>     fetch,
>   },
>   cookies: {
>     get(key) {
>       if (!isBrowser()) {
>         return JSON.stringify(data.session)
>       }
> 
>       const cookie = parse(document.cookie)
>       return cookie[key]
>     },
>   },
> })
> ```

Solved my issue, Thanks
