### ISSUE TITLE
Authentication fails on Twitter (X) when the username includes "@" or "-"

### ISSUE THREAD

**Issue by masa5714** [supabase/auth-helpers#700]
"@supabase/ssr": "^0.0.10",

# Bug report

- Authentication fails on Twitter when the username contains "@" or "-".
- Users who do not have "@" or "-" in their username authenticate successfully.

Failed pattern names:
- masato@japan
- masato - japan

Success pattern names:
- masato

# Memo

I remember having a similar issue in the past.
Here's the link: https://github.com/supabase/auth-helpers/pull/102

**Comment by kangmingtay** [comment]
hey @masa5714, what error do you observe?
