### ISSUE TITLE
Sveltekit 2.0 cookie API change

### ISSUE THREAD

**Issue by Hugos68** [supabase/auth-helpers#706]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Recently Sveltekit 2.0 was released with a breaking change for the Cookie API, specifically the ``set`` function, instead of ``CookieSerializeOptions`` as the third parameter you now are required to specifiy a path, so the type should be: ``CookieSerializeOptions & { path: string }`` as the third parameter. @supabase/ssr doesn't currently support this because it gives a type error when trying to use the guide/example snippet for the ``hooks.server.ts`` file (see screenshot below)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a brand new sveltekit project: ``npm create svelte@latest``
2. Go through the setup, what you choose is not important
3. Go to: https://supabase.com/docs/guides/auth/server-side/creating-a-client?framework=sveltekit&environment=hooks
4. Copy the snippet and paste it into the ``src`` folder of your newly created sveltekit project
5. Observer the type error it gives

## Expected behavior

I would expect the ``event.cookies.set(key, value, options);`` line to not type error.

## Screenshots

![image](https://github.com/supabase/auth-helpers/assets/63101006/1032a4fe-3178-419c-8df9-4677289502b1)

## System information

- OS: Irrelevant
- Browser: Irrelevant
- Version of supabase-js: 2.39.0
- Version of Node.js: 18.18.0

## Additional context

You can read about the change in sveltekit 2.0 here: https://kit.svelte.dev/docs/migrating-to-sveltekit-2#path-is-required-when-setting-cookies.

I also found a workaround that works for now:
```ts
	event.locals.supabase = createServerClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
		cookies: {
			get: (key) => event.cookies.get(key),
			set: (key, value, options) => {
				event.cookies.set(key, value, {...options, path: '/' });
			},
			remove: (key, options) => {
				event.cookies.delete(key, {...options, path: '/' });
			}
		}
	});
```

**Comment by brucey0x** [comment]
Thanks for this suggestion Hugos! I ran into the same type error today.

I see this is planned to be resolved, which is great.

**Comment by probablykasper** [comment]
This issue is still around. #712 made a change to `@supabase/auth-helpers-sveltekit`, not `@supabase/ssr`

**Comment by Hugos68** [comment]
@silentworks Please reopen

**Comment by Hugos68** [comment]
I created one anyways because I was already prototyping it anyways, if you agree that the docs should be changed please discuss any further feedback on the PR itself, if not feel free to close it.

**Comment by Hugos68** [comment]
All is fixed now, the docs got the proper example shown

**Comment by kvetoslavnovak** [comment]
Does it really work?
I am getting this in console:  `''sb-xx..xx-auth-token' cookie does not exist for /, but was previously set at . Did you mean to set its 'path' to '/' instead?`

**Comment by kvetoslavnovak** [comment]
This is what works for me:

```js
	event.locals.supabase = createServerClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
		cookies: {
			get: (key) => event.cookies.get(key),
			/**
			 * Note: You have to add the `path` variable to the
			 * set and remove method due to sveltekit's cookie API
			 * requiring this to be set, setting the path to an empty string
			 * will replicate previous/standard behaviour (https://kit.svelte.dev/docs/types#public-types-cookies)
			 */
			set: (key, value, options) => {
				event.cookies.set(key, value, { ...options, path: '/' });
			},
			remove: (key, options) => {
				event.cookies.delete(key, { ...options, path: '' });
			}
		}
	});
```

**Comment by Hugos68** [comment]
Oh I think you're right, it should be ``/`` not `''`, I'll make a PR.

**Comment by kvetoslavnovak** [comment]
Thank you. Maybe the comment might be changed as well ` ... setting the path to '/' ...`

**Comment by Hugos68** [comment]
Sigh, I really forgot that huh, I'll make a quick PR, thanks for noticing!

**Comment by kvetoslavnovak** [comment]
Thank you. 

By the way, do you know why there is ` ... depends('supabase:auth')  ...`  in [+layout.ts example](https://supabase.com/docs/guides/auth/server-side/creating-a-client?framework=sveltekit&environment=layout)?
I guess it should be used to invalidate. But it seems it is not used anywhere.  
Unfortnnatelly prevous  auth helpers seemed to work better. Ffor example if you had more tabs open it synced all of them nicely. With this SSR  when user logs out the cookies are deleted in all tabs but the UI in other tabs does not refresh accordingly.

**Comment by Hugos68** [comment]
Actually no clue, seems like it might not be neccesary

**Comment by Hugos68** [comment]
And what you are referring too can still easily be achieved!

**Comment by kvetoslavnovak** [comment]
I have spent whole yesterday with no  luck. In Auth Helpers this was no issue at all.

**Comment by kvetoslavnovak** [comment]
So I changed some patterns in official documentation. Now everything works correctly. I will update how to correct SK SSR documentation later on. The main isssue that the documentaton misses how to set up call to invalidate('supabase:auth');

**Comment by kvetoslavnovak** [comment]
> And what you are referring too can still easily be achieved!

I have succeded. Here is working implementaton [tutorial](https://dev.to/kvetoslavnovak/supabase-ssr-auth-48j4) properly calling needed invalidation . 

I also made a proposal to enhance the documentation for SvelteKit Supabase SSR https://github.com/supabase/auth-helpers/issues/742
