### ISSUE TITLE
ssr not obeying redirectTo

### ISSUE THREAD

**Issue by sroussey** [supabase/auth-helpers#710]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The redirectTo param here:

```
const { data, error } = await supabaseClient.auth.signInWithOAuth({
      provider,
      options: {
        redirectTo: getURL(),
      },
    });
```

Does not result in a redirect.

## To Reproduce

1. goto https://embarc-8e6ubad6g-sroussey.vercel.app/signin
2. use google signin
3. see next request is ok:
<img width="934" alt="image" src="https://github.com/supabase/auth-helpers/assets/127349/90d31a0c-b03f-4b62-92ec-d86cebed7dab">
4. see next request is ok:
<img width="934" alt="image" src="https://github.com/supabase/auth-helpers/assets/127349/9ac505c3-3ad4-464a-8ad6-9bb24ca8e93a">
5. Not sure if this is ok or not: 
<img width="934" alt="image" src="https://github.com/supabase/auth-helpers/assets/127349/a4639efd-910d-4c75-8d5b-c0bd776a4ba2">
6. Then redirects to home page of domain, not good. 

## Expected behavior

Should end with code at url /signin/callback

**Comment by dijonmusters** [comment]
The `auth-helpers` and `ssr` packages use the PKCE auth flow, which requires an auth code to be exchanged for the users session before redirecting to the page you want the user to land on after the authentication process completes.

Check out [this one](https://supabase.com/docs/guides/auth/server-side/oauth-with-pkce-flow-for-ssr#create-api-endpoint-for-handling-the-code-exchange) for creating the code exchange route and setting the redirectTo to `/auth/callback`, then [this one](https://supabase.com/docs/guides/auth/server-side/oauth-with-pkce-flow-for-ssr) for an example of using a query param called "next" to declare where you want the user to be redirected to after the entire authentication flow completes 👍
