### ISSUE TITLE
why cookieOptions needs CookieMethods? - @supabase/ssr

### ISSUE THREAD

**Issue by pstachula-dev** [supabase/auth-helpers#711]
Why we cannt create cookie options for `createBrowserClient` ?

I currently need to create an entire implementation of cookies serializer, but I would like to change just the cookie domain to be consistent with the serverClient.

```
 return createBrowserClient(ENV.SUPABASE_URL, ENV.SUPABASE_ANON_KEY, {
    cookieOptions: {
      domain: 'xxx'
    }
  });
```

Error:
```
 Property 'cookies' is missing in type '{ cookieOptions: { domain: string; }; }' but required in type '{ cookies: CookieMethods; cookieOptions?: CookieOptionsWithName | undefined; isSingleton?: boolean | undefined; }'.ts(2345)
```

**Comment by j4w8n** [comment]
This is a known issue. I'm unsure when it'll be addressed.

https://github.com/supabase/auth-helpers/issues/682#issuecomment-1805611404

**Comment by J0** [comment]
Let's track on #682
