### ISSUE TITLE
the cookies option doesn't seem to be doing anything

### ISSUE THREAD

**Issue by JorensM** [supabase/auth-helpers#721]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Setting the CRUD functions for the `cookies` option doesn't seem to be doing anything. The functions never get called.

## To Reproduce

![supabase cookies option](https://github.com/supabase/auth-helpers/assets/17122123/f70bae96-a36a-4bb1-b4f3-ec933fdadd2c)

In this code I posted you can see that I've simply added `console.log`s to the setter/getter/remover. Yet the console never logs any of those messages. I should also note that I'm using a custom storage handler in the `auth` option. I should also say that I *know* that the Supabase client uses the auth storage to store cookies. Which then begs the question: why do we have a separate `cookie` CRUD object if it's not being used? Currently TypeScript says that this property is required, which seems redundant considering that the client is using the storage defined in `auth` to manage cookies, and considering that the getters/setters never get called anyway. I'd expect at the very least for the `cookies` property not to be required.

## Expected behavior

I'd expect for either:

a) the `cookies` functions to be called
b) the `cookies` property to be optional

## Screenshots

See screenshot of my Supabase config above.

## System information

- OS: Windows 10
- Browser: Chrome
- Version of supabase-js: 2.39.3
- Version of supabase/ssr: 0.0.10
- Version of Node.js: 20.8.0

## Additional context

I'm moving away from supabase/ssr because I found out that it only uses cookies for storing the session and doesn't offer any alternatives, which won't work for me because I'm writing an app with React Native, which doesn't support cookies. But just thought I'd share this small bug with you.

**Comment by KyleFontenot** [comment]
I'm pretty confident `get`, `set`, and `remove` should be synchronous instead of async. If you remove `async` do you still get the same results?

**Comment by contactjavas** [comment]
Framework like [unjs/h3](https://h3.unjs.io/) that's also used by [solid-start](https://docs.solidjs.com/solid-start/) (via vinxi, I think) is using `async` to access the session.

- Solid-Start session doc: https://docs.solidjs.com/solid-start/advanced/session
- h3 session doc: https://h3.unjs.io/examples/handle-session

It will be problematic with the `cookies` options in Supabase-SSR's `createServerClient` API.

**Comment by hf** [comment]
This is expected. `createServer/BrowserClient` implement their own storage option. So if you already set your own, your custom option (`AsyncStorage`) wins.
