### ISSUE TITLE
supabase/ssr export error in browser

### ISSUE THREAD

**Issue by Aietes** [supabase/auth-helpers#725]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using supabase/ssr in Nuxt, provided via a Nuxt module, I get the following error in the browser:

```
Uncaught SyntaxError: The requested module '/_nuxt/node_modules/.pnpm/cookie@0.5.0/node_modules/cookie/index.js?v=d88ad7de' does not provide an export named 'parse'
```

It comes from `packages/ssr/src/utils/helpers.ts`, where cookie helper functions are imported:

```ts
export { parse, serialize } from 'cookie';
```

Is there anything I can do about it? The issue seems to be that I'm using ssr in a ESM module, and the helper functions are CommonJS. There seem to be a [pull request](https://github.com/jshttp/cookie/pull/154) in the cookie library, but it's not merged yet, and ssr would still need to update the dependency.

## Expected behavior

No module export error in the browser.

## System information

- OS: macOS
- Browser: chrome, safari
- Version of supabase-js: 2.39.3 (ssr 0.0.10)
- Version of Node.js: v21.6.1

**Comment by Aietes** [comment]
I worked around the issue by pre-bundling the package using optimizeDeps in Vite. This fixes the error, I believe Vite fixes the imports/exports during the build.

**Comment by phillipmohr** [comment]
Is this fixed? I'm using Nuxt 3 and I upgraded to `"@nuxtjs/supabase": "^1.4.0"` and `"@supabase/supabase-js": "^2.45.3"` but still getting this error.

**Comment by peterhel** [comment]
@phillipmohr I've been tackling the same issue with nuxt3. I just got it working by deleting `node_modules` and `package-lock.json`, then clearing the versions from package.json:
``` 
    "dependencies": {
        "@nuxtjs/supabase": "",
        "@supabase/ssr": "",
        "@supabase/supabase-js": "",
       ....
   }
```
npm install and npm run dev. BOOM! works (on my machine). Hope it helps!

**Comment by phillipmohr** [comment]
> @phillipmohr I've been tackling the same issue with nuxt3. I just got it working by deleting `node_modules` and `package-lock.json`, then clearing the versions from package.json:
> 
> ```
>     "dependencies": {
>         "@nuxtjs/supabase": "",
>         "@supabase/ssr": "",
>         "@supabase/supabase-js": "",
>         ....
>     }
> ```
> 
> `npm install` and `npm run dev`... BOOM! works (on my machine). Hope it helps!

Unfortunately no luck for me :( i'm using pnpm though. When I try to run `pnpm i` after setting the versions to `""` I'm getting an error.

Can you let me know what versions of `nuxt`, `@nuxtjs/supabase`, `@supabase/ssr` and `@supabase/supabase-js` you are using?

**Comment by phillipmohr** [comment]
I "fixed it" by downgrading. I've done some digging and in the docs here: https://supabase.nuxtjs.org/changelog#v1.3.1 I found this entry: _We're now using the [@supabase/ssr](https://supabase.com/docs/guides/auth/server-side/creating-a-client) library under the hood 🎉 ([#357](https://github.com/nuxt-modules/supabase/issues/357))_ for version 1.3.1. 

So I downgraded to v1.2.2 and the error is gone. 

I'm not sure if the issue should be addressed here or in the Supabase nuxt module?

**Comment by Aietes** [comment]
@phillipmohr This should probably be addressed in the Nuxt module. We are using our own version of the supabase nuxt module now, in which we have adapted the latest supabase/ssr changes, which handles ssr and auth quite differently than before. https://github.com/floatingpixels/supabase-nuxt

**Comment by rafadpedrosa** [comment]
@phillipmohr I think we had the same issue. I downgraded as you mentioned and it works. Unfortunately, I don't have time to go deeper, but I would like to understand why... 

Anyway, given that you managed to find the solution/have a better understanding of the problem, about that: 

> I'm not sure if the issue should be addressed here or in the Supabase nuxt module?

Just open in both and add references. If it's not related to the repo, the community/contributors will say so :)
