### ISSUE TITLE
Failed to set cookie when OAuth username includes non-ASCII characters

### ISSUE THREAD

**Issue by SDuck4** [supabase/auth-helpers#729]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The OAuth authentication flow was processed in accordance with [this guide](https://supabase.com/docs/guides/auth/server-side/oauth-with-pkce-flow-for-ssr), but some users were not authenticated.
I've looked into it and found that when set up cookies in Supabase, it doesn't filter the non-ASCII characters in OAuth user information, so the cookies don't set up properly.

I solved it by customizing cookie method as follows, but I think it's a fundamental problem that needs to be solved in this library.

```ts
set(name: string, value: string, options: CookieOptions) {
  const nonAsciiRegex = /[^\x00-\x7F]/g;
  const valueNonAscii = value.replaceAll(nonAsciiRegex, "");
  cookieStore.set({ name, value: valueNonAscii, ...options });
},
```

These are the names that failed to create cookies while testing.
- Алиса
- カリーム
- 關聖

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Sign-in with OAuth that has non-ASCII username

## Expected behavior

- Non-ASCII usernames are also typically set to cookies.

## System information

- OS: macOS, Windows, iOS, Android
- Browser: chrome
- Version of supabase-js: 2.39.0 and ssr is 0.0.9
- Version of Node.js: 18.19.0

**Comment by kangmingtay** [comment]
@SDuck4 we've recently patched this issue in #726, can you please try this again with the latest supabase/ssr version ?
