### ISSUE TITLE
Multiple GoTrueClient instances when using `supabase/ssr` and `@supabase/auth-helpers`

### ISSUE THREAD

**Issue by bombillazo** [supabase/auth-helpers#739]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

As recommended by the Supabase docs, we started using the new SSR library to handle our Next.js auth clients int he front end. However, we still need access to the regular auth hooks provided by auth-helpers, such as the `useSession` hook. So we now have both libraries installed at the same time.

This causes unexpected issues where the auth tokens suddenly get erased and other weird behavior.

## To Reproduce

1. install both "@supabase/ssr" and ""@supabase/auth-helpers-react"
2. create a next page with a hook like `useSession` and also create an ssr browser client
3. load a page and check the console.

## Expected behavior

No issues with the library

## Screenshots

![image](https://github.com/supabase/auth-helpers/assets/44002321/edbc4ffd-6b28-45c3-be7a-5bcc7a94c62c)

## System information

- Browser (if applies)chrome, firefox
- Version of supabase-js: 2.39.3

**Comment by kvetoslavnovak** [comment]
What is the point to use both libraries? Official documentation says that you should use only one or another, not both.

**Comment by bombillazo** [comment]
/ssr does not have the `useSession`, `useUser` hooks

**Comment by bombillazo** [comment]
closing, no longer popping up
