### ISSUE TITLE
[supabase/ssr] Missing hooks for `useSupabaseClient`, `useUser`, `useSession`

### ISSUE THREAD

**Issue by bombillazo** [supabase/auth-helpers#744]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

The documentation recommends that we migrate away from the old `auth-helpers` lib in favor of the `ssr` library, but the library is still missing essential hooks for fetching the client and user auth data.

## To Reproduce

N/A

## Expected behavior

To replace `auth-helpers` with `ssr` the hooks available before would be available also in the `ssr` package.

## System information

- Version of supabase-js: 2.39.3

**Comment by silentworks** [comment]
Can you please provide an example of what these hooks look like? there were never any `useSupabaseClient`, `useUser`, `useSession` hooks in the `@supabase/auth-helpers-nextjs` library at all, these were only available in the `@supabase/auth-helpers-react` library which you should still be able to use with the `@supabase/ssr` library.

**Comment by bombillazo** [comment]
Hey, I never said they were part of `@supabase/auth-helpers-nextjs`, we use them from `@supabase/auth-helpers-react`. Nevertheless, the docs state we should move from `auth-helpers` in general:

<img width="917" alt="image" src="https://github.com/supabase/auth-helpers/assets/44002321/0f3cac21-625d-4a18-a58c-57119b28377a">

Hence, this issue since the `ssr` lib does not provide the hooks that we get from `@supabase/auth-helpers-react`. Perhaps it's the docs that should be updated if these hooks are not intended to be part of the SSR package.

**Comment by mariomeissner** [comment]
+1 to this. `@supabase/auth-helpers-react`'s `useSession`/`useUser` are essential parts of an authentication provider to simplify usage within React. If this repository is being deprecated, the new one should provide similar tooling.

**Comment by mariomeissner** [comment]
If the intention is not to deprecate `@supabase/auth-helpers-react` but only `@supabase/auth-helpers-nextjs`, then this is not being communicated properly in this repository nor in the Supabase docs.

Additionally, the updated Auth documentation with `@supabase/ssr` does not mention anything about `@supabase/auth-helpers-react`, even though it would be extremely useful to do so.

**Comment by bombillazo** [comment]
Hello all, I made a new issue in the ssr repo to see if we get more visibility/traction. Feel free to follow that issue instead of this one.

**Comment by JimmyLv** [comment]
For friends who have been struggling with `@supabase/ssr` for many days, it's not your fault; it's the supabase team that made us waste time. `@supabase/auth-helpers-react` is not magical and I created a simple compatible way and added explanations:

```ts
import { Session } from '@supabase/supabase-js'
import { useEffect, useState } from 'react'
import { createClient } from '~/utils/supabase/component'

// Component - Runs on the client. Reads cookies from browser storage.
// Behind the scenes, createBrowserClient reuses the same client instance if called multiple times, so don't worry about deduplicating the client yourself.
// This is why SessionContext is no longer needed, you can remove @supabase/auth-helpers-react
export function useSupabaseClient<T>() {
  const supabase = createClient<T>()

  return supabase
}

// This method retrieves the current local session (i.e local storage).
// Since the unencoded session data is retrieved from the local storage medium, do not rely on it as a source of trusted data on the server.
// It could be tampered with by the sender. If you need verified, trustworthy user data, call getUser instead.

// https://github.com/SamuelSackey/nextjs-supabase-example/blob/main/src/lib/supabase/use-session.ts
export function useSession() {
  const [session, setSession] = useState<Session | null>(null)

  useEffect(() => {
    const supabase = createClient()

    const getSession = async () => {
      const {
        data: { session },
      } = await supabase.auth.getSession()

      setSession(session)
    }

    getSession()
  }, [])

  return session
}

// const { data: { user } } = await supabase.auth.getUser()
// This method fetches the user object from the database instead of local session.

// Should always be used when checking for user authorization on the server. https://supabase.com/docs/reference/javascript/auth-getuser
// On the client, you can instead use getSession().session.user for faster results. getSession is insecure on the server.

// https://github.com/SamuelSackey/nextjs-supabase-example/blob/main/src/components/user-information.tsx#L7
export function useUser() {
  const user = useSession()?.user

  return user
}

```
