### ISSUE TITLE
Server-Side Auth with Magic Link does not set auth token cookie

### ISSUE THREAD

**Issue by jj0b** [supabase/auth-helpers#750]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using Magic Link the `sb-localhost-auth-token` cookie never gets set. Instructions here are for a **local development** setup. Interestingly I have tested with my Supabase project url and anon key and the cookie does get set in that case.

## To Reproduce

I have created a repository to demonstrate this bug at [https://github.com/jj0b/server-side-auth-magic-link](https://github.com/jj0b/server-side-auth-magic-link).

My repo is built based off of the instructions on the [Setting Up Server-Side Auth For Next.js](https://supabase.com/docs/guides/auth/server-side/nextjs) page in the Supabase docs. 

1. Start `Supabase` with:

```
supabase start
```

2. Copy anon key you get back after starting Supabase and put it into an `.env.local` file with the following:

```
NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=<your_supabase_anon_key>
```

3. Run the development server:

```bash
npm run dev
```

4. Open [http://localhost:3000](http://localhost:3000) to confirm the app is running.

5. Now go to [http://localhost:3000/login](http://localhost:3000/login), enter any email (doesn't matter as the Magic Link will be sent to Inbucket, not your email) and click the Magic Link button.

6. Go to Inbucket at [http://127.0.0.1:54324](http://127.0.0.1:54324) and follow the Magic Link.

7. Now that you are back in the app, open the inspector to the Application tab, then view the cookies under the storage section. You will notice that there is no `sb-localhost-auth-token` cookie set.

8. Attempt to open [http://localhost:3000/private](http://localhost:3000/private) and notice that you can't view that page. 

This is the code for `app/private/page.tsx`:

```typescript
import { redirect } from 'next/navigation';

import { createClient } from '@/utils/supabase/server';

export default async function PrivatePage() {
  const supabase = createClient();

  const { data, error } = await supabase.auth.getUser();
  if (error || !data?.user) {
    redirect('/');
  }

  return <p>Hello {data.user.email}</p>;
}
```

Without the `sb-localhost-auth-token` cookie set `supabase.auth.getUser()` cannot get any data, so the user is redirected to `/`.

## Expected behavior

After following the Magic Link to the app the `sb-localhost-auth-token` cookie should be set and `supabase.auth.getUser()` should be able to get the user.

## System information

- OS: macOS Sonoma 14.3.1
- Browser: Chrome 122.0.6261.112
- Version of supabase-js: [2.39.8]
- Version of supabase/ssr: [0.1.0]
- Version of Node.js: [21.5.0]

**Comment by jj0b** [comment]
I figured out the issue, and it was ME. 

The problem was that in my config.toml my site_url and additional_reidrect_urls were using 127.0.0.1 but I was accessing my app on localhost. 

Updating to this fixed my issue:

```
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000/auth/confirm"]
```

I now get the auth token cookie!

Hope this helps anyone else who runs into this problem.

**Comment by Sof2222** [comment]
I had a similar issue but the issue was not the redirect but the fact I was in dev mode.
In dev mode:
- I had to log in twice to get the cookie set (like do the magic otp twice) -> auth-token-code-verifier would be set the first time and then auth-token would be set the second time
In build though both were set properly.

Was really weird... and I don't really know why but at least there is a simple workaround and it seems it only happens in sys/dev not prod
