### ISSUE TITLE
Support for custom Search Params in the `redirectTo` option URL

### ISSUE THREAD

**Issue by 413n** [supabase/auth-helpers#96]
I have a `middleware` using `withAuthMiddleware` that redirects the user to the homepage with a custom Search param and seems to not be supported because I get to this broken link: `http://localhost:3000/%3Ferror=notAuthorized?redirectedFrom=%2Fprotected%2Fpage`

My code
```javascript
import { withMiddlewareAuth } from "@supabase/auth-helpers-nextjs/middleware";

export const middleware = withMiddlewareAuth({
  redirectTo: "/?error=notAuthorized",
});
```

Debugging the code, I found the part below where we can see that the `redirectTo` is set as `pathname` and then a SearchParam is set. This is the part that could be more flexible.

https://github.com/supabase-community/auth-helpers/blob/9b4225133a5f3a617819570bd172af3cdb8ac7cb/packages/nextjs/src/middleware/withMiddlewareAuth.ts#L142-L159

## Proposal

What if we check that the redirectTo is an instanceof URL (https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) and eventually avoiding setting it to the pathname but using that to set the SearchParam?

Or eventually an additional check should be done to initialize the given URL string

**Comment by thorwebdev** [comment]
This will be enabled via https://github.com/supabase/auth-helpers/pull/364
